# Q2D: A Novel Approach to Measure Deliberative Quality at a Citizen Conference on Taxation

<!--
The respectful give and take of deliberative citizen participation is expected to change political views, though in which way, and how to measure it, is less clear. 
On the one hand, conventional survey research offers rigorous and advanced analytics, but is marred by deductive operationalizations and often falls short of a convincing measure of communicative rationality. 
Qualitative approaches, on the other hand, leave much to the researcher's discretion, and risk conflating a measure of deliberative quality with the researcher's substantive theory of justice or reason.
-->
Dryzek and Niemeyer have shown that Q methodology can be a productive *mixed* method to study deliberative democracy: It offers a holistic, and operantly defined, yet quantitatively rigorous view on political subjectivity.

Using data gathered before and after the 2014 week-long CiviCon Citizen Conference on taxation, hosted by the author, I suggest several novel approaches to measure deliberative quality using Q methodology.
Following traditional Q methodology, principal components were extracted and rotated from 79 item-cases across 17 people-variables to distill three ideal-typical viewpoints shared by participants. 
Before the conference, citizens expressed *resentful*, *radical* and *moderate* viewpoints, including some apparent inconsistencies. 
After the conference, citizens shared *decommodifying*, *pragmatic* and *critical* viewpoints and displayed a simpler, lower-dimensional structuration of viewpoints.

Such results are meaningful and encouraging for the use of Q in deliberation, but fall short of testing a treatment effect, because before- and after-factor models are extracted and rotated separately.
To tease out the effects of deliberation, I therefore also apply a newly developed 2-dimensional Q analysis (Q2D), based on three-mode Principal Components Analysis (nPCA) by Tucker and Kroonenberg.
Results can be meaningfully interpreted using Q2D, indicating that participation in the Citizen Conference has increased substantive consistency of political viewpoints, seemingly meeting a demanding standard for deliberative democracy. 
<!--On the other hand, a unified longitudinal factor model may also unreasonably restrict the change of subjectivity during deliberation. 
Analyzed separately, there is some evidence that before and after factor models are, in fact, incongruent.
-->

Political subjectivity has been conceptualized by Dryzek and Niemeyer to involve *beliefs* and *values*, as well as *preferences*.
These are conceptually *independent dimensions* and the very status of some assertion as either value or belief is often contested, and thereby part of political subjectivity proper.
Here, too, Q2D can significantly improve upon conventionally analyzed, repeated Q studies by yielding *jointly extracted and rotated*, two-dimensional ideal viewpoints vis-a-vis the *same* items, readily interpretable in terms of meta-consensus and intersubjective rationality.

Algorithms and visualizations in open-source R-code are presented, conceptual limitations of Q2D are discussed and compared to alternative analytical approaches to Q data in empirical deliberative democracy research.
