# Abstracts {-}

## English {-}

> Why, in the most prosperous of economies, are we plagued by widening inequality, underfunded states and persistent unemployment?  
> Why, in the most enlightened of times, are we thoroughly confused about governing our mixed economies and perilously disaffected with the results our democratic rule produces? 
 
> **What if** there were alternative taxes, which afforded us more attractive tradeoffs between economic efficiency, equity and sustainability or other ends  
> **What if** we *could* agree on such alternative taxes, but *would not*, because we lacked the necessary information or suitable fora, and because our capacity for mutual reason-giving had been diminished by alienating inequality or clouded by special interest?

Everyone pays taxes, and **taxation** affords us citizens some democratic control over the mixed economy, yet we often poorly understand it.
Reasoning with one another may strengthen our **democracy**, but little is known how such a deliberative ideal fares on abstract policy or how deliberative quality might be measured.

The first [CiviCon Citizen Conference](http://www.civicon.de) tests in a **quasi-experiment** how deliberating policy as abstract as taxation might work, and how people's thinking on taxation might change as a result.
During the week-long conference, 16 diverse, self-selected citizens were tasked to design a tax system "from scratch", choosing among possible combinations of base schedule.
They participated in [learning phases](https://github.com/civicon/samuelson), deliberated in moderated small group and plenary sessions, met with experts and held a concluding press conference.

Before and after the conference, citizens sorted 79 statements on taxation and  economics according to their subjective viewpoint.
Following **[Q methodology](https://en.wikipedia.org/wiki/Q_methodology)**, sorts were factor analyzed to extract ideal-typical viewpoints shared by participants.
Before the conference, citizens expressed *resentful*, *radical* and *moderate* viewpoints, including some apparent inconsistencies between *beliefs*, *values* and *preferences* on taxation.
After the conference, citizens shared *decommodifying*, *pragmatic* and *critical* viewpoints and displayed a simpler, lower-dimensional structuration of viewpoints.

Results indicate that indeed, deliberation changes people's thinking on taxation, strengthening their viewpoint consistency and better structuring their subjectivities.
Results also indicate that deliberating abstract policy can be meaningful: While citizens considered themselves ill-prepared yet to recommend *a* tax, they felt more confident in deciding on tax policy and advocated for more and longer citizen participation on such abstract matters.

Long-form deliberation may or may not yield *rational consensus* on taxation or other complex economic policy, but at least, it should help reduce the rough-and-tumble of economic ideologies to fewer, deeper and *reasonable disagreements*, more amenable to last resort majority decisions.
