# First-Order Abstractions {#abstractions}

<!-- this works well for pragmatism:
> "Vain is the word of a philosopher which does not heal any suffering of man. For just as there is no profit in medicine if it does not expel the diseases of the body, so there is no profit in philosophy either, if it does not expel the suffering of the mind."
- Epicurus -->

<!-- %add on "property" Simons' argument that it's 90 percent background conditions, and Offes (2009 via Bosch) addition that rents of cooperation (cf game theory) can, by definition, not be accrued to any one PARTICULAR participant. -->

## Optimality

A system is efficient if it maximizes outputs for given inputs.

<!-- %somewhere in McCaffery:
%Ramsey optimal tax literatre:
%"inverse elasticity" rule.
%This can lead to perverse ideas:
%working wifes is ok, but low wages for immigrants with hig hwork ethic? -->

But exactly *what* should be maximized?
Efficiency norms vary and can conflict.
I present here three popular definitions in increasing order of strength.
[^1]
Earlier entries are subsets of later entries, as visualized in .

Pareto Efficiency.

:   \phantomsection
    [\[sec:pareto\]]{#sec:pareto label="sec:pareto"}
    An allocation is pareto-optimal, when no one can be made better off *without making someone else worse off*.
    Pareto optimality, is, in fact not a pure efficiency norm but includes an equity component, too.

Kaldor-Hicks Efficiency.

:   \phantomsection
    [\[sec:kaldor-hicks\]]{#sec:kaldor-hicks label="sec:kaldor-hicks"} An allocation is Kaldor-Hicks efficient, when no one can be made better off without making someone else worse off *by the same or a greater amount* of disutility [@Kaldor1939; @Hicks1939].
    It can also be described as a pareto-optimal outcome where sufficient compensatory sidepayments can be made from the winners to the loosers.

Social Welfare Optimum.

:   \phantomsection
    [\[sec:swo\]]{#sec:swo label="sec:swo"} The pure efficiency norm is given by the utilitarian slogan "The greatest good for the greatest many" [@Mill1863].
    It knows no equity at all, but is concerned only with the sum total.
    It is also known as a social welfare optimum in game theory (for example, @Oye-1985-aa).

\centering
![Selected Efficiency Norms, Where Area Equals Utility[]{label="fig:Efficiencies"}](efficiency-norms){#fig:Efficiencies width="100%"}

I choose as the weakest of these efficiency norms and note whenever a stronger efficiency norm is required for an argument.
Pareto efficiency is also widespread efficiency norm that is convenient for its link to (page ).

#### In Dubio Pro Mercatus.

The above posited perfect markets can be shown to work Adam @Smith-1776-lq's *Invisible Hand* [-@Smith-1776-lq].
More formally, the first theorem of welfare economics states that any competitive equilibrium will be Pareto optimal:
no one could be made better off, without making someone else worse off[^2].

For () efficiency, the burden of proof then lies on state interventions in . [\[sec:perfect-competition\]](#sec:perfect-competition){reference-type="ref" reference="sec:perfect-competition"}
It follows that a tax should affect market interactions as little as possible.

#### Minimize Deadweight Losses

The efficiency loss that *does* occur when taxes alter market interactions is called a deadweight loss (DWL), illustrated in .
It arises as follows:
consumers and producers both reduce their buying and selling, as consumers face higher and producers lower prices.
This reduces the welfare, or surplus of consumers and producers.
Some of this loss is transferred to government.
The net that is not recouped as tax revenue is the deadweight-loss of taxation.

A desirable tax should have a minimal deadweight loss.
[\[des:minimal-DWL\]]{#des:minimal-DWL label="des:minimal-DWL"}

A desirable tax will maintain and strengthen incentives to maximize private, unobserved effort in work and investment.
[\[des:Incentives\]]{#des:Incentives label="des:Incentives"}

##### Reformulations of DWL.

The idea of the DWL of taxation can be reformulated in a number of ways.

Factor Unemployment

:   refers to DWLs in markets of factors of production, when tax wedges cause incomplete employment of labor or capital.
    This problem is particularly dire in the indivisible supply of low-productivity labor, where entire strata of workers may be unable to find gainful employment at post-tax wages.
    This problem of is further discussed in and addressed in desideratum [\[des:low-price-floor\]](#des:low-price-floor){reference-type="ref" reference="des:low-price-floor"}.

Taxes are Anti-Growth.

:   A sophisticated version of this sentiment will also argue that widespread DWLs waste economic resources in the medium and long run.

Neutrality.

:   The DWL of a tax can also be described as its impact on a hypothetical, before-tax, pareto optimal market.
    An efficient, desirable tax is neutral in the sense of leaving pre-tax relative prices unchanged [@McCaffery2005 849].


    <!-- %note, improve language-wise:
    %DWL is the opposite of gains from trade.

    %the question is:
    %why is the DWL here, and not in some other section, namely do ability?
    %this figure happens earlier as fig:DWL -->

    <!-- %note somewhere that this applies only to revenue generation and redistributive taxation;
    %pigouvian is the opposite -->

<!-- this is about economic imagination, akin to sociological imagination, gans 1988 public Sociology
a household, but with a case of millions -->

<!-- all of this is a priori stuff; there is no calibration or empirical stuff in here -->

<!-- it's very important to concentrate on a few, however pragmatic these might be.
if you're not concentrating, you're talking about nothing (or everything) -->

<!-- provisionally accept homo oec + abstractions -->


<!-- ### What's special about deliberating tax choice?

- Tax offers/demands very structured choices: there are essentially only 4x3 broad tax types (see tax table in drafts).
  Different from, for example, a deliberation on “racial tensions”, deliberating tax choice is more close-ended.
- Tax expertise is easily politicized, because:
	- Tax cannot be reduced to an empirical question, both because inframarginal data is not available, and because macroeconomics is incompletely understood.
	- Tax cannot be reduced to a consequentialist inquiry, because people (may) care about other normative claims, too (e.g. fairness).
- Tax cannot be easily (if at all) dumbed down to subsets of tax choice (e.g. VAT vs PIT), or subsets of abstractions (e.g. only “bastard keynesianism”) for two reasons:
	1. Any such reduction would violate the spirit of deliberation; citizens could not set their own agenda.
	2. Any such reduction may well fail to elucidate my hypothesized misunderstandings: ßI imagine “understanding tax” as a bucket, which, if leaky will drain to the lowest level. For example, if deliberators would discuss most aspects of taxation, but skip over the limits (!) of price controls, they may well opt for price controls in lieu of, or in addition to taxation. -->

## Axiology

<!-- %discuss somewhere:
%vertical vs.\ horizontal equity (\citealt{Mankiw-2004-aa}:
%255);
%this is key for a rule-of-law, fair tax.
%It's also the same norm as gleiches wird gleich, unterschiedlich unterschiedlich behandelt, somewhere in the German Basic Law.
%Find out where. -->

<!-- %here, I still have to write a bit on distributive justice
	%http://en.wikipedia.org/wiki/Justice#Theories-of-distributive-justice
	%http://en.wikipedia.org/wiki/Distributive-justice
	%compare them, explain why I go for Rawls

%In philosophy, the term "maximin" is often used in the context of John Rawls's A Theory of Justice, where he refers to it (Rawls (1971, p.
%152)) in the context of The Difference Principle.
%Rawls defined this principle as the rule which states that social and economic inequalities should be arranged so that "they are to be of the greatest benefit to the least-advantaged members of society".
%In other words, an unequal distribution can be just when it maximizes the mininum benefit to those who have the lowest allocation of welfare-conferring resources (which he refers to as "primary goods").[5][6]
	%note that this is only loosely related to the maximin use otherwise used. -->

Second, Rawls suggests two distributive norms, the *difference principle* and the *fair equality of opportunity*.
[^3]
Under the *difference principle*, differences in endowments as well as subsequent social and economic inequalities are acceptable only if their granting also benefits the least fortunate.
[^4]
If inequities cannot be thereby justified, such undeserved differences (by birth or other random allocations) in endowment should be corrected by intervention for *fair equality of opportunity*.

This latter norm of fair equality of opportunity is a pure equity norm on the equality of inputs.

The difference principle is more complicated.
It combines equity and efficiency norms.
It is that weak pareto optimum (WPO),
[^5]
which maximizes the minimum payoff (maximin) in outcomes.
illustrates the two Rawlsian norms of distributive justice in context.

\centering
![Selected Distributive Norms and Rawlsian Distributive Justice (in green)[]{label="fig:distributive-norms"}](distributive-norms){#fig:distributive-norms width="100%"}

#### Why Rawls?

Any comprehensive discussion of distributional justice is beyond the scope of this thesis.
@Rawls-1971 *Theory of Justice* is presented here for four reasons.

First, *justice as fairness* serves as a convenient cut-off point on a (crudely) imagined continuum of theories of distributive justice from left to right, from egalitarianism to utilitarianism and liberitarianism.
[^6]
It is assumed that all allocative norms "left of" Rawls [such as @Cohen2000], stressing equity over efficiency will strictly prefer the PCT over the status quo.
Conversely, theorists on the right end of the imagined continuum (for instance, @Nozick1974) may not share all of the normative foundations of the PCT, or even prefer it over the status quo.

Second, the *difference principle* is (page ) when I argue the normative superiority of the progressive taxation of consumption.

Thirdly, in arguing that the PCT is the perfect tax, I attempt to establish it as an *reflective equilibrium* [@Rawls-1971 49] emerging from a pragmatic-spirited back-and-forth between what is , and what is @McCaffery2005 [856].

Fourth, @Rawls-1971' *Theory of Justice* ([-@Rawls-1971]) is an end-state theory of distributive justice [@Fried1999 1007], not a procedural prescription (for example @Dahl-1989-aa).
A political process, aside from @Rawls-1971ian liberty, is not prescribed in its own right.
It merely serves as an *independent* variable in ,explaining and criticizing why it may have failed to deliver the superior allocative outcome.

#### Implications for Tax Design.

Two desiderata for tax design emerge from @Rawls-1971's Theory of Justice.

First, the principle of *fair equality of opportunity* introduces equity as a goal for taxation.
It is a general and unspecific norm.
Translating it into a desideratum for tax design hinges on an empirical assessment of opportunity
in the real world.
A specification of this norm must therefore await an inspection of the (page ) in modern society. [\[sec:inequality-dynamics\]](#sec:inequality-dynamics){reference-type="ref" reference="sec:inequality-dynamics"}

Second, the *difference principle* provides a more straightforward guideline for redistributive taxation.
It implies that taxation should exempt from redistribution economic inequality if, and to the extent that, it makes the least fortunate better off.
This may occur when able people require economic to exert maximum efforts (desideratum [\[des:Incentives\]](#des:Incentives){reference-type="ref" reference="des:Incentives"}).
Because axiomatically assumed perfectly competitive markets can be shown to be pareto optimal, it follows that:

[\[des:difference-principle\]]{#des:difference-principle label="des:difference-principle"}
A desirable tax exempts from redistribution economic inequality if, and to the extent that, it makes the least fortunate better off.

Generally, for axiomatically assumed *homo economicus* to , she needs incentives.
Desideratum [\[des:Incentives\]](#des:Incentives){reference-type="ref" reference="des:Incentives"} is closely related to desideratum [\[des:minimal-DWL\]](#des:minimal-DWL){reference-type="ref" reference="des:minimal-DWL"} ().


[^1]: The selected efficiency principles are all cardinal, rather than ordinal in definition, and do all not consider the aggregation problem commonly known as *diminishing utility to wealth* [@Hicks1946].
    While these are substantial shortcomings, they do not concern me in the efficiency discussion of the perfect tax.
    Respective *equity* implications are discussed in sections [\[sec:diminishing-marginal-utility\]](#sec:diminishing-marginal-utility){reference-type="ref" reference="sec:diminishing-marginal-utility"} () and [\[sec:positional-race\]](#sec:positional-race){reference-type="ref" reference="sec:positional-race"} ().

[^2]: Demonstrated first graphically by [@Lerner1944], mathematically by [@Lange1934], [@Debreu1954] and others.

[^3]: These two distributive norms follow the equal liberty principle in *lexical* order, meaning that no distributive improvements can justify infringements of equal liberties.

[^4]: [@Rawls-1971 122] warns that this calculus must not only include strictly economic payoffs, but must also take into account the intangible correlates of social inequality as societal and cultural participation, as well as confidence.

[^5]: An allocation is weakly pareto optimal when no other allocation is *strictly* preferred by everyone.
    A strong pareto optimum, by contrast, requires only that all individuals will receive same *or* higher payoffs.

[^6]: A right-hand pole comprising of utilitarian *and* libertarian ideals obviously reveals the futility of any one-dimensional scaling of theories of allocative justice.


## Ontology

<!-- As if economics were true

Milton Friedman argued that for economic models is does not matter whether assumptions are realistic, or whether actors understand them – but whether predictions are borne out, and whether actors behave *as if they had some given theory in mind*.
An instructive example for this would be a billard player who does not know the laws of physics in any case, but behaves *as if* s/he understood them.
This is the example from Friedman.

Paul Pfleiderer via Econtalk on Russ Ruberts points out that this depends on *continuous* and *instantaneous* feedback – so these are repetetitive games, with quick feedback.
So something like the 10k hours rules might apply.
Paul Pfleider then applies this to capital structure decisions by firms – a lot of research on this.
How do firms decide this?
The problem that we have is that very similar firms objectively have very different capital structures, and we don't know why.
So the solutions suggested by economists are incredibly complex – but there's a catch: CEOs make very few capital structure decisions, and they don't get immediate feedback (none).
So the 10k hour learning kind of rule does not at all apply.

... so I need to make some kind of pragmatic argument out of this. -->


## Optimality


## Incidence

<!-- civicon quote (for the incidence day): the curious task of economics is to .. -->


## Circular Flow


## Natural Personhood

<!-- %\subsection{Natural Persons}

%The first complication of taxation is actually a clarification:
%redistribution is only meaningfully defined between \emph{natural} persons, that is, actual human beings.
%William \citeauthor{Vickrey1947} begins his classic \emph{Agenda for Progressive Taxation}:
%``Genuinely progressive taxation is necessarily personal taxation'' (\citeyear{Vickrey1947}:
%1).

%comment here somehow on the foundational argument:
%that you are entitled to whatever you earn in uncoerced exchange --- or are you?

%also comment here somehow on where that relies on the state
	%in protection of property rights for private consumption
	%in protection of land etc.
%for control
	%na this isn't so good.

%we know from earlier desiderata, we want it to be progressive, but just how and why we want that is less clear.
%that's why this is about fairness, not just equity. -->

### Corporations


### Families


## Haig-Simons Identity of Income


## Savings norms

<!-- ## Fried 1992
this appears to be re mccaffery

There are three arguments, says Fried 965 why savers and spenders ought to be treated the same, and she says, they're all flawed
1) Abstinence ideas: savers and spenders ought tob ear equivalent tax burdens because they have equivalent wealth ex post, once the costs of deferreing consumtpion are accounted for
this is, in fact, as fried notes 967, an improved income tax.
the abstinence justification is: you have costs when deferring consumptions, psychic costs. OR: you have less utility for the remaining lifetime
2) Bradford: savers and spenders ought to bear equivalent tax burdens, whether or not they are in equivalent positions ex post, because they face equivalent choices ex ante
3) savers and spenders ought to bear the equivalent tax burdens because they are entitled to preserve the relative ex post advantages, whether equivalent or not, that they enjoy in a no-tax world.
now here is a key argument (971) she argues that the abstinence theory is wrong, because we never compensate for pscychic cost of at the margin-leisure, we don't do this for workers, they work at the margin of where they are indifferent between working and not working. But we don't reward them enduring the psychic cost of working, we just tax them anyway. So they will include this in their rationales for working more. Her argument is: then why do it for the psychic cost of saving?!?
here's a tentative solution: we do that for workers, actually, and we should: it's the base-rate of only consumption, which I think we should continue -->


<!-- Schumpeter 1918
- reads like today!
- cite SChumpeter: the confusion and non-scientific/ideological nature seems very interesting, p. 99
- 103: argues that once there is a state, *anything* could be a matter for the public; now I am not so sure, there are still economic considerations (economies of scale, etc.)
- 104: that's a good thought – it's ahistorical to think of previous times as hyper-private, without the state – because this *functional differentiation* simply had not happened yet.
- 105: that's a good point: that the crisis must be fundamental, related to the foundational logic – maybe we have that today with the dual crises of the welfare state
- 108: such a great notion how the democracies are saddled with the old baggage of feudalism! It was the princes state that was assimiliated (as far as possible by democracies)
- notice that this 108ff schumpeter makes the same argument as could be made about post-communist welfare states: they *were no* welfare *states* under socialism, because the economy and state were *one* undifferentiated realm
- 114: not sure how we can practically have a monopoly tax, but some things work out great – the land value tax! Schumpeter also recommends it!
- 116: fantastic keynes-esque quote on the end of history in tax
- 124: the whole war debt thing is a bit of magical thinking ...
- 131: more keynesian optimism on the future end of history

Comment: Schumpeter might really be thinking about the laffer curve: past regime does not work because costs of extraction are prehibivey,  so you need a new system.
In away, schumpeter really thinks AS WE MUSt of tax state as interfacing the mixed economy. -->

<!-- from seligman 20: 20: look again into Buchanan, and relate it to Nagel/murphy the myth of ownership: maybe both looking from the right AND the left, infinite regress ensues – (this is hard to say). TODO actually this is still pretty loose, I think probably think about this in a more careful way. The bottom line would be something like this: buchanan talks about the fiscal illusion, which requires a prior of private property, which is difficult to talk about without reference to the institutions that actually allow private property and commerce. On the other hand, talking about the advantage of public goods only makes sense once you talk about -->


<!-- Buchanan 1967

TODO Cite Buchanan on fiscal illusion in diss, and the italians he cites, seems quite similar.

- hereagain the myth of ownership strikes hard: it is VERY hard to price the "real" cost of public goods, almost circularly.
- either way, infinite regress ensues.
- i'd like to hear him argue against the LVT or PCT
- I agree with much of this: financial transaction tax really is a tax that's widely loved because no one knows who pays it. -->

<!-- Thorndike Address

Thorndike is interested in the arguments on fairness, not the answers (that's interesting, that's great for CiviCon!)

Consent, Compliance and Confession.

Question: how about the compliance on illiquid tax, especially within the PIT (on accrual or realisation)

Look back into Macomber, what the ruling says, maybe get back to Ajay (it seems that Macomber did *not* introduce realisation-based evaluation).

- We should do relate this to social/epistemic/individual preferences *explicitly* (if we can)
- We should explicate the external validity (real world?), increase the complexity (effort, capital)
- We should try and relate this to Kahnemann/Tversky research program.
- [Lucy Barnes](https://www.kent.ac.uk/politics/staff/canterbury/barnes.html) was quite interested in this stuff


> relate to Kahnemann/Tversky work on bounded rationality: which behavioral biases work here?

It's not clear to me how these biases translate to more complex tax scenarios.
McCaffery and Baron have tried this, but only on very, very simple models.
Loss Aversion probably plays a role. -->

<!-- ## mcCaffery: misunderstandings

is right indeed "the canonical understanding of consumption taxes changes under consistently progressive rates. No longer are prepaid and postpaid consumption taxes - taxes on wages and spending, respecitbely - equivalent. Postpaid consumption taxes can and do burden the yield to capital, and not in an arbitrary, random way. Far from it: A progressive postpaid consumption tax emerges as the fairest and least arbitrary of all comprehensive tax systems, precisely because it chooses to make its decisions about the appropriate level of progressivity at the right time. In doind so, it burdens some but not all uses of capital and its yield. and for normatively attractive reasons". (812)
wow.
"This traditional view has generated an impoverished choice set for tax, consisting of a badly flawed status quo on the one hand and a flat consumption tax of some sort on the other. Under the guiding light of the traditional view, we are heading ever closer towards a flat wage tax." 812
"Under progressive tax rates a postpaid, cash-flow or (all equivalently) spending tax is not equivalent to a yield-exempt or wage tax" 813

governing dynamics of inequality.
"Genuinely progressive taxation is necessarily personal taxation" (Vickrey 1947 "Agenda for Progressive taxation" as cited in MCCafferty 830)

if you want read more on this by Mirrleess, Bankman and Griffith, as cited in McCafferty 835 and elsewhere


Hobbes and smith come down for consumption taxes. Both the father of economics and the father of the state
Hobbes, Leviathan 386-87
[T]he equality of imposition, consisteth rather in the equality of that which is consumed than of the riches of the persons that consume the same. For what reason is there that he which laboureth much, and sparing the fruits of his labour, consumeth little, should be more charged than he that living idlely, getteth little, and spendeth all he gets, seeing the one hath no more protection from the commonwealth than the other? But when the impositions are laid upon those things which men consume, every man payeth equally for what he useth, nor is the commonwealth defrauded by the luxurious waste of private men.
Smith
Every tax ought to be levied at the time, or in the manner, in which it is most likely to be convenient for the contributor to pay it.... Taxes upon such consumable goods as are articles of luxury, are all finally paid by the consumer, and generally in a manner that is very convenient for him. He pays them little by little, as he has occasion to buy the goods. As he is at liberty too, either to buy, or not to buy, as he pleases, it must be his own fault if he ever suffers any considerable inconveniency from such taxes. Smith supra note 54 in cafferty
McCaffery says the USA mistake came from mistaking the Haigs-Simon definition: "an is had become an ought" (emphgasis in original. 840 MccFfery
this comes from Andrew's' idea that the most sophisticated reason for the PCT would be principled nontaxation of the yield to capital. That is the wrong reason! It is taxed, too. just differently.
yields to capital are taxed, and only there where they elevate living standards (that's vertical quity) as opposed to horizontal equity between saving, then spending
McCaffery makes this very point that progressivity, even though desired, is disappearing because of the choice of really bad tax choice.

848: "Advocates of redistributive taxes must wake up and realize that their end is in jeopardy on account of their poor choice of means: they are fighting, and losing, the wrong war."
Neutrality in comparison to a no-tax world seems nice, but is a problematic thing.

if you avoid distortion of the saving-spending decision, you skew the work-leisure tradeoff.
comment on this!
neutrality, or rather, fairness, narrowly understood as economic welfarist perspective (the optimal tax literature) is bad.
1) judgment of fairness need to take the pretax status quo as normatively appropriate
2) optimal welfare-maximizing tax answer may clash with ordinary moral intutions and reflective normative commitments

Make the point of lumpy earner, steady earner and trust fund baby *878) compare to the other tersm used for the same thing.
note, as McCaffery does on 883 that private markets can also solve the consumer durables smoothing problem: leasing, reanting.
the income tax problem for the propertied classes gets even worse because of the "wait until realiziation" and the "wait until debt is repaid" problem - bth may never happen for the super rich (this is McCaffery 888) (at least this shifts the time problem, and may make it very problematic. in the US, the fact that things canthat are inherited can be sold at fair market value free of tax makes this an even bigger problem. This is an extension of the CIT problem actually, a problem that maters for all things where accretions are not immediatley realized. "Tax planning 101 is elegantly simple: buy, borrow, die" (890)
this can't be easily solved, it's an admoinositratove nightmare.
hence the backstop of the estate and gift tax.
this is it: DYSFUNCTIONS OF THE BACKSTOPS. Dysfunctional backstoppers of PIT: CIT, PIT.
nice quote "THings in tax today are bad" (McCaffery 893)

899: "Together with the basic tax planning of buy/borrow/die, lower tax rates on capital realizations and corporate dividends, cash-value life insurance, and the taxation of home-ownership, the new developments in retirement savings help to move tax towards a world in which citizens will pay taxes on their wages, under a compressed rate structure, and never again. This is the world of prepaid consumption, or wage, taxation"
people arbitrage their way toward a falt, wage-tax.


"Corporations are legal fictions".
 the key moral intuition, and Rawlsian reflective equilibrium is this: it seems fair and appropriate to burden capital ransactions when these facilitate or enable a better lifestyle, reflecting a greater "ability to pay" or more "benefits received" from the social compact. But it does not seem fair and appropriate to burden capital transactions when they are used simply and sensibly to move around in time uneven labor market earnings." 921

 "People treat a plan as realistic when it approximates what already exists and as utopican when it departs from current arrangements. Only proposals that are hardly worht fighting for - reformist tinkering - seem practicable" (Roberto Managebrai Unger, False Necesseity 12 1987 as cited in McCaffery 938)

 > "A progressive postpaid consumption tax emerges as the fairest and least arbitrary of all comprehensive tax systems, precisely because it chooses to make its decisions about the appropriate level of progressivity at the right time. In doing so, it burdens some but not all uses of capital and its yield, and for normatively attractive reasons."
 > Edward J. McCaffery (2005: 812).

 There are three types of taxes
 1. Income taxes (including capital incomes)
 2. Prepaid consumption taxes (VAT), or, equivalently, payroll taxes, or, equivalently social contributions (such as statutory health insurance, unemployment insurance, pensions, etc. in Germany)
 3. Postpaid, progressive consumption taxes ("The Perfect Tax"), based on a cash flow account of spending (Consumption = Income - Savings / aka Haig-Simons definition of income).

 There are two savings norms (as in: what exactly is saving?)
 1. Ordinary Savings Norm: saving is just postponed consumption, "smoothed out" over the lifetime. Nominal interest is just a compensation for postponement (think: inflation, risk, growth, discounting of the future). Incomes from savings (= capital incomes) should not be taxed.
 2. Yield-to-Capital Norm: incomes from savings are a genuine accretion to wealth. Interest is income.  Incomes from savings (= capital incomes) should be taxed.
 	Note:
 	- Income taxes (if complete) adopt a yield-to-capital norm. All capital incomes are (ideally) taxed. (In reality, as McCafferty explained, they hardly ever are, because there are systemic flaws, such as "tax evasion 101")
 	- Prepaid consumption taxes (or VAT, or payroll, or social contributions) adopt an ordinary savings norm. No capital incomes are taxed.
 	- Postpaid progressive consumption taxes (or spending taxes, or cash flow based consumption taxes) tax some capital incomes. To the extent that (dis!)saving is used to smooth out consumption, interest is not taxed. To the extent that it is used to enhance lifestyle, or for lumpy consumption (opposite of smoothed out), it is taxed.
 	For a review of different taxes and how they work, consider my prospectus (again attached), pages 60-66
 	Consider this example to understand that a VAT (German MwSt.) is the same as a proportional payroll or proportional social contribution. -->


  <!-- # other last reasons Nozick

  On distributive justice: no, it shouldn't be entitlement "that a person is entitled to those goods acquired in uncoerced exchanges with others" (Robert Nozick, as cited in Bankman, Griffith 1997: 1915)
  I want a welfarist theory of distibritutive justice. It shouldn't be utilitarianism, it should be leximin / Rawls.
  Also: dynamics / outliers / network effects (Benkler, matthias' guy) / inequality / spirit level.
  Also: Hobbesian. -->


  <!-- # McCaffery
  - McCaffery 2009 (819): tax. Most importantly, it develops more formally two norms about the taxation of capital: the yield-to-capital norm, which holds that the return to capital is an increment of value that ought to be taxed, and the ordinary-savings norm, which holds that savings that merely shift labor earnings within a lifetime or between taxpayers ought not to be excessively burdened. These two norms are in fatal tension under an income tax; in contrast, a consistent, progressive postpaid consumption tax accommodates both norms by design.

  these are actually last reasons! -->


<!-- also: man works to live / live to work about the fischergleichnis böll story -->


<!-- more diss notes (sokrates)

these are notes from August 9, from a discussion

starting point: it's difficult to teach economics ("why is greece so much in debt?"/ issue of trade balances) in school on a problem-based approach, because economics is based on (politicized) axioms and ontologies (marginal logic, incentives, etc). If you don't get to problematizing those, you end up with random disagreement and some arbitrary teaching from, say, a marxist and neoclassical economist.
Crucially, the two (and especially the students, or civicon citizens) won't even know why the disagree (metaconsensus).

so you need to go in depth, so that people get the axioms and ontologies. You can either do that spontaneously, starting wherever you are, which might be better from a motivational point of view, or systematically, say according to some textbook. That might be less optimal from a motivational point of view.

notice why the axioms and ontologies are so important: economics (and politics) is both circular reasoning and implies policy (collectively binding stuff).
It is circular, because (need a plot for this): when you decide on institutions (assuming that you accept some human agency and choice in that, and are NOT a fascist or a libertarian or otherwise non-Bonhoeffer), you obviously want them to somehow correspond to human motivation. They cannot completely ignore human motivation.
On the other hand, that very human motivation is, of course -- especially of already grown, existing humans -- shaped by their experience with past institutions: a lifetime of incentives and property rights will probably create people who respond to incentives and believe in property rights.
So you have a circular piece of reasoning in any economic policy making.

Notice that this does not pertain to whichever part of human motivation is not amenable to institutions but hard-coded "nature".

Notice that this is less dramatic for natural sciences, because they do not have a circular reasoning in their reasoning; instead they have objectiviable criteria, so cutting of the chain of justification and referring to tradition or authority (experts say that) is not, in principle, illegitimate, at least to the extent that their scientific process is ok.
This is not the case for deliberative democracy and economics: NO process relying on such a circular piece of reasoning can ever be legitimate.

Pragmatism may be the only way out: you accept that you always have to take some present state of the world as given for policy, but that state can never justify the ends of that policy, you must always look towards a horizon of more, even if you can only judge taht horizon imperfectly.

This shows up quite dramatically in deliberation, where absent a recourse to the foundations of economics (marxist, marginal, etc.) it's very hard to reach metaconsensus. -->
