# The CiviCon Citizen Conference {#civicon}

<!-- 1. Methods-1 (CiviCon) -->
<!--    - explicates the *treatment condition*; in this case, the CiviCon Citizen Conference -->
<!--    - *contextualizes* the CiviCon format within existing literature, formats, conflicts, tradeoffs -->
<!--    - *documents* structure, experts, sample, etc. of CiviCon -->
<!--    - *reports* on the validity, reliability of the treatment in deliberative terms, including citizen and moderator feedback. -->

I here propose to investigate a supposed difference in current, and (more) ideal speech thinking about tax by subjecting a group of diverse citizens to a deliberative forum on the topic, which, in one succinct summary [@Steenbergen2003 25ff], is marked by

1. open *participation*, including setting the agenda and deciding on procedures (@Benhabib-1996-aa, @Chambers1995, @Cohen-1989-aa, @Habermas1992 [370ff])
2. mutual *justification* of assertions and validity claims [@Habermas1992 370],
3. orientation on the *common good* [@Rawls-1971],
<!-- not sure about this, it's kinda downstream from habermas -->
4. *respect* for one another, as well as one's arguments (@Gutmann1996, @Macedo1999), other-directedness, empathy and solidarity,
5. *constructive politics* of a widely acceptable decision over well-defined policy alternatives, ideally --- though not necessarily --- by consensus [@Cohen-1989-aa 23],
6.  *authenticity* in sincere, not strategic communication [@Habermas-1984 149]
<!-- %add here, maybe: manifest equality as demanded by Cohen -->

<!-- TODO insert this alternative list:
%\begin{enumerate}
%	\item reasonably accurate and complete \emph{information},
%	\item substantive \emph{balance} of possibly competing arguments and perspectives presented,
%	\item \emph{diversity} of participants and their positions taken,
%	\item a sincere weighting of arguments by participants, or \emph{conscientiousness}
%	\item equal consideration of all arguments, regardless of which participant offered them \cite[K1799]{Fishkin2009}.
%\end{enumerate} -->

## Reciprocity

Deliberation is no such catalogue of first-order considerations of what would make a good (efficient, fair, sustainable) decision in any given policy field, but instead, a second-order prescription to resolve disagreement *over* those very the moral and causal arguments [@GutmannThompson-2004-aa 125].
Still, and in contrast to pluralism, it places more than just *procedural* claims, but posits *substantive* requirements for how agreement must be reached.
Succinctly, @GutmannThompson-2004-aa demand that "your fellow citizens must give reasons that are comprehensible to you" [-@GutmannThompson-2004-aa K177].
More than merely intelligible, permissible arguments to reach deliberative agreement must raise validity [@Habermas-1984] and moral [@Rawls-1971] claims *universally* acceptable to everyone.

Logically, it must then be theoretically possible for any *given* argument to *fail* that test, and to be impermissible --- including the arguments brought forward by experts.
In fact, deliberation reserves no special place for nominal experts at all, except if and to the extent that these experts have arrived at, and present their agreement under the standards of deliberation.

As noted in the above, any research design that axiomatizes any disagreement between experts (or ex-ante logic) as *misunderstandings* on the part of the non-experts fails the deliberative standard, no matter the supposedly enlightening de-biasing treatments.

The desiderata of taxation and deliberation are seemingly in conflict.
Taxation requires people to consider an exogenously given catalogue of abstractions, and deliberation implies that no such set of arguments can be unconditionally accepted.
This is a general contradiction of procedural and substantively epistemic formulations of deliberative democracy [@Bohman1998 402].

This impasse has real repercussions for the proposed research design:
apparently, it can serve only one master.
Either, participants misunderstandings can be revealed by treating them with introductory economics, *or* they can deliberate any which arguments they themselves find comprehensible.

As with so much that deliberative theory is up against this is a false dichotomy.[^false_dichotomies]

[^false_dichotomies]: For example, political participation versus enlightened understanding versus political equality, as @Fishkin2009 points out.

Argumentative reciprocity implies that expert knowledge be neither presumed, nor negated, but that these arguments --- as all others --- be allowed to demonstrate their universal causal and moral validity.

<!-- %``Mutual justification means not merely offering reasons to other people, or even offering reasons that they happen to accept [\ldots] \citep[98]{GutmannThompson-2004-aa}.
%	It means providing reasons that constitute a justification for imposing binding laws on them.
%	What reasons count as such a justification is inescapably a substantive question.
%	Merely formal standards for mutual justification --- such as a requirement that maxims implied by laws be generalizable --- are not sufficient.%plagiarism? -->

Expert- and non-expert (as all other) arguments must not merely be balanced in terms of airtime or affect, but "the considerations offered in favor of, or against, a proposal, candidate or policy \[must\] be answered in a substantive way by *those who advocate a different position*" [@Fishkin2009 K550, emphasis added].
Deliberation is, in other words, when non-experts answer expert arguments *on their own, expert terms*, and vice versa, too.
Surely, the relation of this ideal to practice is "aspirational", too, as all in deliberation [@Fishkin2009 K2679].
So far, democratic theorists have failed to show "how to incorporate the need for expertise and technical administration in a deliberative democracy" [@Thompson2008 515] and "\[a\] great deal of work on deliberative theory focuses on conflicting values, religious toleration, identities and so on, and relatively little on conflicting facts" [@Moore2011 2].

Yet, for the deliberative experimenter, this aspiration to argumentative reciprocity is the ultimate hypothesis in need of falsification, including reciprocity with expert arguments.
If expert knowledge on taxation is presumed valid, and any dissent chalked up as misunderstandings the aspiration of communicative action could *never* be falsified.
Likewise, if expert knowledge on taxation is not given adequate opportunity to be reciprocally considered on its own terms, communicative action will *always* be violated.
Neither of those formats would provide construct-valid deliberation.
Expert knowledge is then "a special case of the general problem of convincing those who are not 'in the room' to accept the results of a deliberation in which they did not directly participate" [@Moore2011 2].
This problem can only be resolved by a "democratic conception of expert authority" [@Moore2011 2], that is, if deliberative standards are extended to expert arguments, too.
A good deliberative format brings ordinary citizens into this business:
they must be enabled to the farthest extent possible to argue expert as well as non-expert claims on their own terms, including the possibility to reject expert opinion if it is found insufficiently reciprocal in argument.

Because bringing ordinary citizens into this business, and *equally* so, is, as @Rosenberg-2002-aa's so difficult, deliberations must "be regarded as remedial institutions" [-@Rosenberg-2007-aa 12] and more, "they must be sites for political education and development" [-@Rosenberg-2007-aa 13].

<!-- %%Mansbridge 2010
%	%   * points out that deliberative polling mostly does not include radical solutions, perspectives (that could be a problem)
%

%Any such reduction would violate the spirit of deliberation; citizens could not set their own agenda.
%Any such reduction may well fail to elucidate my hypothesized misunderstandings: I imagine “understanding tax” as a bucket, which, if leaky will drain to the lowest level.
%For example, if deliberators would discuss most aspects of taxation, but skip over the limits (!) of price controls, they may well opt for price controls in lieu of, or in addition to taxation.

%Meaningfully deliberating tax requires a lot of knowledge, and that knowledge is unlikely to spring merely from the act of deliberation, but it needs some input.

%\citep[101]{GutmannThompson-2004-aa} ``Reciprocity is to justice in political ethics what replication is to truth in scientific ethics.
%A finding of truth in science requires replicability, which calls for public demonstration.
%A finding of justice in political ethics requires reciprocity, which calls for public deliberation.
%Deliberation is not sufficient to establish justice, but deliberation at some point in history is necessary.'' --> 

<!-- I have a reference to abortion somewhere, that it CANNOT be resolved and there seems to be a case from Caroline Lee where pro-life and pro-choice people got together and talked with one another to prevent violence, and they ended up liking one another, but *not* agreeing at all
this is interesting both because of of the moral issue of abortion, but also as an example of the talk -->


## Remedial Deliberation

If their democratic rule is to be enlightened, deliberators must also engage a set of abstractions concerning its optimality, justice and sustainability as well as problematize the view of human motivation, utility and rationality implied by these (economic) abstractions.
<!-- TODO link to old tax sections in the above -->
Deliberators must also understand the means and ends of an (ideal) mixed economy within which taxation reconciles allocation by plan and by exchange, including respective government and market failures.
@Warren2008 [K1513], reporting on the [ca]{acronym-label="ca" acronym-form="singular+short"}, notes that such learning phases are "crucial to its ability to render a decision, and indeed" and that it *can be done*:
"the decision was a learned and sophisticated one";
"Most members transformed themselves from lay citizens with little knowledge of electoral systems into experts over a period of several months (...)" [-@Warren2008 K1513].
Any deliberation that fails to engage such technical but broadly consensual --- if not entirely coherent --- concerns, must be considered unenlightened.
It would ignore some of the causal relationships and moral alternatives that we must assume exist, if and to the extent that we accept the economic ontology of coexisting states and markets.

The fora, even though featuring learning phases, must not regress to a (traditional) classroom setting in which the economics teacher knows best.
Still, this *is* the inescapable challenge of deliberation in the modern world, as @Moore2011 points out:
"the ideal of citizen equality to deliberate issues that affect them is in tension with the inequalities of knowledge that are inherently governing complex societies", *but* "the question is not *whether* expert authority is part of the deliberative system, but *how* it is integrated and whether *this integration is itself subject to deliberative standards*" [@Moore2011 14, emphasis added].


<!-- TODO link to mixed econony and ontology -->

<!-- why do we need learning phases? how is this necessary? (it is) -->

<!-- cite rosenberg to argue for learning phases: -->
<!-- % \subsection{Political Psychology}
% Communicative action is very demanding of the cognitive and moral faculties of deliberators.
% Political psychologists have problematized these demands that deliberation poses \citep{Rosenberg-2002-aa} --- especially, but not only, deliberation of highly abstract topics.
% Troublingly for deliberative democracy of the Habermasian kind, recent research in political psychology suggests, that --- contrary to the bounded rationality assumption \citep[for example,][]{Simon-1999-aa,Kahneman2011} --- imperfect human reasoning may not only stem from remediable cognitive scarcity, but may be developmentally determined.
% \citet{Rosenberg-2002-aa} has proposed a threefold developmental sequence and typology of \emph{sequential}, \emph{linear} and \emph{systematic} reasoning.
% %TODO add better rosenberg references
% His empirical accounts suggest that if any, only systematic thinkers will be able to meet the cognitive demands for reasoned arguments, and egalitarian free speech of deliberative democracy.
% Moreover, this cognitive competence was found \emph{not} to be domain specific, and while people may regress to lower levels of competence under high loads or appropriate cues, they are unlikely to easily, if ever, achieve higher than developed levels.
% ``Structurally (more and) less developed reasoning adults'' make ``not only the adequacy of citizens' reasoning, but also their \emph{equality}'' a problem for deliberative democracy \citep[12, emphasis added]{Rosenberg-2007-aa}.

% On this red flag, too, much of deliberative practice is silent.
% While deliberative formats routinely strive to attract diverse participants and ensure their equal participation \citep{Fishkin2009}, they rarely problematize, or measure the substantive, argumentative \emph{equality} of participants.
% Among the small research that has looked into argumentative equality of actual (\gls{dp}) proceedings, \cite{Siu} finds that information, rather than education of participants is related to argument quality \emph{at the small group level}, but offers no individual-level analysis.
% There is also yet --- to my knowledge --- no research that tracks how limited and unequal capacities for moral and causal reasoning may filter up to understandings of, and preferences over complex policy issues.
% Here, too, taxation is a good case to test the promise of deliberative fora:
% it demands both advanced moral and causal reasoning, and raises controversies and tradeoffs likely to impact the life-chances of people along similar socio-economic dimensions as those related to cognitive competence.

% Based on his sobering findings, \citet[20]{Rosenberg-2007-aa} also suggests a revised understanding of deliberation:

% \begin{quotation}
% 	\emph{``Deliberative fora must not be regarded simply as empty stages that provide a venue for the realization of citizenship;
% 	nor must the design of these deliberative stages focus simply on the removal of obstructions that may inhibit freedom or give unequal scope for maneuver.
% 	Instead, deliberation must be understood as a site for the construction and transformation of citizenship.
% 	In deliberation, citizens are made as well as realized.
% 	The operative metaphor here is that of a school, but of particular kind.
% 	The educational goal is not the transmission of specific beliefs and values, although these are by no means irrelevant.
% 	Rather the central aim must be to foster the requisite cognitive development for a fuller autonomy, a greater communicative competence and a better ability to engage in a collaborative effort to make good and just public policy.''}
% 	\\*
% 	--- Shawn W.\ \citet[20]{Rosenberg-2007-aa}
% \end{quotation}

% This ``reforming'' variant of \citeauthor{Habermas-1984}' vision --- informed by empirical facts about our time, and our people --- also bears on the analysis and operationalization of deliberation.
% \emph{School}, as \citeauthor{Rosenberg-2007-aa} reminds us, is the ``operative metaphor'', one that balances furthering of equality and citizens' autonomy.

%note that the link between rosenbergs sequence thinking and my tax misunderstandings is still to be developed -->


## Format

Consequently, a good format for deliberating tax includes a strong learning component, where participants are introduced to the structured choices and relevant abstractions suggested by experts, including their disagreements, conditions and uncertainties.
Deliberators are unlikely to cover these extensive grounds by themselves, or pick them up from (very limited) briefing books and will benefit from well-planned lessons.
On the other hand, a good format must also feature extensive small-group discussion, where participants talk amongst themselves, shielded from the authority of expertise.
Deliberators may benefit from a trained, non-expert moderator and/or scribe to assist, structure and document their discussion.
Most importantly, participants must be encouraged to adjudicate the validity claims of economics, to contrast and possibly relate those to their own, and other claims.

As noted earlier, most deliberative formats include --- often moderated --- small-group discussion, but few add to that a substantive learning component.[^dps]

[^dps]: [dps]{acronym-label="dp" acronym-form="plural+short"}, the pronounced methodological gold standard of deliberation [@Mansbridge2010] are too short to feature long lessons, and confine expert knowledge to ad-hoc question and answer sessions with experts and limited briefing books [@Fishkin2009].
    Citizen Juries [@SmithWales-2000-aa], Planning Cells [@Dienel-1999-aa] and related formats also include no learning components, and some experimenters even advise against expert knowledge.

Among those that do are the small-n Danish-developed Consensus Conferences [@Grundahl1995] and especially the large-n, one-off [ca]{acronym-label="ca" acronym-form="singular+short"} in British Columbia, Canada [@Citizen-2004-aa].
Consensus Conferences have been held on very technical issues, including nanotechnology [@LeeKleinman2007] or genetically modified foods, and the Citizen Assembly was tasked to recommend an alternative electoral system for the province.
Much like taxation, technology policy, and especially electoral systems design also demand highly structured choices (for example, a seat allocation rule or regulation) and raises a set of abstractions (party systems or risk distributions).

In a Consensus Conference, 12-15 self-selected but diverse citizens discuss a technical matter of political relevance for three or more days (!) and issue a report on their discussions [@LeeKleinman2007].
In preparation for the conference, participants read quite extensive background material, which they discuss during the first of several daylong sessions.
At later sessions, they (publicly) share their questions with experts and finally draft a report for the sponsoring body and/or the media.
@LeeKleinman2007 report that a positive atmosphere, good organization and skillful facilitation are necessary for a successful Consensus Conference.
They also recommend that participants tell their stories, which moderators then weave into themes, to help citizens relate their experiences to expert knowledge [-@LeeKleinman2007 159].

The [ca]{acronym-label="ca" acronym-form="singular+short"} expanded on this model.
Over the course of a year, 160 randomly selected British Columbians read and learned about electoral systems, held public hearings, deliberated amongst themselves and, after several intermediate votes, recommended a (quite complicated) [stv]{acronym-label="stv" acronym-form="singular+short"}-variant and drafted a report [@Citizen-2004-aa].
The extensive learning phase, spanning six (!) weekends stands out among deliberative experiments.
In addition to a university-level textbook on electoral systems, Citizens received interactive lectures accompanied by small discussion groups.
An expert panel vetted the learning phase for impartiality and accuracy of information.
Participants also developed a set of shared values during the learning phase, both (procedurally) for how they wished to deliberate and (substantively) for a desirable electoral system.


## Implementation

The [ca]{acronym-label="ca" acronym-form="singular+short"} provides an ideal blueprint for a deliberative forum on tax;
however, limited resources and lack of experience do not permit such a large undertaking for this project.

Instead, the project proposed here is a scaled-down hybrid, combining the ambitious learning phases of a Citizen Assembly, with the more intimate, small-n interaction and participant empowerment of Consensus Conferences.[^learning_phase_ca]

[^learning_phase_ca]: The [ca]{acronym-label="ca" acronym-form="singular+short"} also featured a "listening phase" [@Pearse2008 1609] during which members held public hearings throughout the province, drawing some 3,000 attendees and 1,600 written submissions.
    Both because I do not have the resources and --- absent a mandate --- expect limited public interest, I plan no such phase.

A small, self-selected sample of 15-24 diverse, ideally randomly-sampled, citizens will attend around 6 days of learning and deliberation spread over several weeks.
A provisional schedule is included in (p. ).

After introducing the format and framing the issue, deliberators are invited to tell stories about experiences with taxation, following @Mansbridge2010a [67]'s recommendation:
'Stories can establish credibility, create empathy, and trigger a sense of injustice, all of which contribute directly or indirectly to justification'' [-@Mansbridge2010a 67].
Deliberators also share opinions and grievances about tax as well as identify relevant questions and issues, which will be taken up in, and structure the later learning phases.
During these learning sessions, taking up less than half of the time, participants receive information about the structured choices and relevant abstractions of taxation from the author.
These lessons are organized around themes and values identified by deliberators in an initial session, and attempt to relate the subject matter to participant experiences.
Learning sessions alternate with extensive small-group deliberations, during which participants reflect on the lessons, relate or contrast it to their own experiences and claims and adjudicate the validity of the presented moral and causal arguments.
Small-group deliberations are facilitated by a trained moderator, who has no expertise in taxation or economics.
At the end of the process, participants must agree on a tax and write a report outlining their recommendation, which can be released to the public.
If resources permit, participants will also hear a panel of expert witnesses to discuss their questions.

<!-- notice pretest at uni hamburg
%Participants in the university class will be graded, but not based on their contributions to the deliberations, to which the author and instructor will not be a party.
%The class will be advertised through the usual channels at the university. -->


<!--
%a good format for my goal includes
    %Includes a strong learning component, structured roughly along my drafts -- but shorter, and in more accessible style.
%(It must not be a microeconomics text).
    %Relates these abstractions to personal experiences and intersubjective value judgments.
    %Prioritizes intensity (duration) over representativeness (sample size) under given constraints (time, money).
    %May involve me and existing material for the learning component, but someone else must moderate the deliberations.
    %Starts from a small-scale, face-to-face deliberation as a pilot study, both to guarantee concept validity and because I have no idea about deliberation-

    %Instead the same quasi-experimental design could be run with qualitative data, including, open-ended questionnaires and/or semi-structured interviews, or even a record of the deliberations.
%Such data could be content-analysed (or rather: coded) to distill the (mis)understanding before and after the treatment.

%note reciprocity, sharing ones causal assumptions

%\cite{Azmanova2010} (also \cite{Fishkin2009}: 529)
	%49: thoughtfulness and reflexivity (as per Fishkin) require 1) reasonably accurate information 2) substantive balance 3) diversity, 4) conscientiousness, 5) equal consideration

%\cite{Citizen-2004-aa}
	%11: one guy did the learning sessions
	%1) has a selection phase
	%2)  has a LEARNING phase
		%also develop "shared values" about the process
	%3) has a PUBLIC HEARING phase
	%4) has a DELIBERATION phase
	%go to chrch with group, maybe.

%\cite{Fung-2003-ac}
	%very good summary, get back to this

%\cite{Fishkin2009}
	%democracies are supposed to fulfill two values; political equality and deliberation (loc.
%84)
	%``a democracy in which we all had substantive information [and] [\ldots] substantive opinions would seem to take too many meetings.''
	%what's wrong with unenlightened opinions (all loc.
%113ff)
		%\begin{enumerate}
			%\item they may be volatile (cite other sources
			%\item people may be manipulated by foregrounding some information (clean coal vs.\ dirty coal, forgetting about natural gas -- compare this to tax choice)
			%\item misinformation (savings rate)
			%\item favor favorable, true arguments over others
			%\item manipulation may ``prime'' one aspect of policy.
		%\end{enumerate}
	%K260: ``the hard choice, in other words, is between debilitated but actual opinion, on the one hand, and deliberative but counterfactual opinion, on the other.''
	%K369: table with raw/refined opinion, and different kinds of sampling.
	%K438: ``The idea is that if a counterfactual situation is morally relevant, why not do a serious social science experiment -- rather than merely engage in informal inference or armchair empiricism -- to determine what the appropriate counterfactual situation might look like?
%and if that counterfactual is both discoverable and normatively relevent, why not then let the rest of the world know about it?
%Just as John Rawls's original position can be thought of having a kind of recommending force, the counterfactual representation of public opinion identified by the \gls{dp} also recommends to the rest of the population some conclusions that they ought to take seriously.''
	%K390: self-selected samples will be very limited in what they can achieve.
	%K401: citizen juries use quota samples, consensus conferences use self-selected samples, then with some quota sampling
	%K550: notes that positions must not merely be balanced in terms of airtime or affect, but ``whether the considerations offered in favor of, or against, a proposal, candidate or policy are answered in a substantive way by those who advocate a different position.'' %THIS IS KEY!
	%K561: three categories for such considerations
		%``the benefits or burdens of a policy or political choice,
		% the causal arguments about whether those benefits or benefits or burdens will actually result from one choice or another,
		%and the values by which those benefits and burdens might best be evaluated.''
		%K1424: ``the problem is that any microcosmis deliberation taking place in a modern society will be one in which there are significant social and economic inequalities in the conduct of ordinary life in the broader society.
		 	%It seems difficult or impossible to `bracket' these inequalities -- for participants to behave `as if' they do not exist.
		 	%Indeed the problem goes deeper.
%The possibility of doing so is the challenge of the ``autonomy of the political'', namely, whether or not equality can hold sway in politics in a world in which inequality rules in economic and social relations.
		 	%The viability and legitimacy of the liberal-democratic process may turn on the answer.'' \citep[loc.
%2679]{Fishkin2009}

%\cite{GutmannThompson-2004-aa}
	%loc177: `your fellow citizens must give reasons that are comprehensible to you''
	%K188: they introduce first and second-order theories, too!
	%K919, writing about Fish: ``Giving reasons is the chief way of academics to exercise power in democratic politics.
%All the talk about deliberation, like deliberation itself, is merely a cover for power politics.''.

%iris marion young, especially notes that people of lower status may have a hard time getting listened to, or that others may be particularly accustomed to orderly forms of reason-giving arguments that weigh with other participants -- and this may be particulary problematic the more substantive the topic is.

%note that

%groupthink!

<!-- absolutely must re-read moore piece on conducting deliberation; this is key for how it's done and facilitated, there are also helpful comments in there. -->

<!-- title: so crazy, it did just work? -->

<!-- this will definetely remain very much a proof of concept; it's too small and unporfessionall to say much -->

<!-- TODO: get offe field report email -->

<!-- TODO: get email to random experts -->

- 25 Anmeldungen (Stand 10.07.), davon 20 Studierende (!)
- Beschickt sind / noch im Gange sind:
  - lokale Presse
  - lokale Institutionen (Kirche, Stadtbibliothek, VHS, Vereine)
  - korporatistische Institutionen (Gewerkschaften, Kammern)
  - Parteien (lokal)
  - Diverse Mailinglisten (überwiegend Studierende, Akademiker)
  - Diverse Soziale Netzwerke (überwiegend studierende, Akademiker)


### Weiterer Prozess

- 14.07.2014 Presse und ggfs. kostenpflichtige Anzeigen
- 21.07.2014 Ende der Voranmeldungen, Auswahl
- 28.07.2014 Verbindliche Zusagen
- 11.08.2014 Anreise


### Offene Fragen

- Weitere Quellen/Kanäle?
- Vortreffen?
- Wie kann man Teilnahme sicherstellen?

- Martin sagt: 5 Leute als Springer bereit halten oder überbuchen
- Broschüre in Arbeitsamt

- broschüre vorher verschicken (vor q-sort ist ok), damit die vorher wissen was bus und bahnhof ist und außerdem hat ja noch keine deliberation statt gefunden

- moderatoren müssen darauf achten, ob ich neutral bin.

- gruppen fest machen, oder rotieren?
- kleingruppen einzeln untersuchen




## Methode Q-Sort

- Q-Sort wurde in mehreren Versionen 8 mal durchgeführt, Änderungen eingearbeitet
- Q Methode wurde im Doctoral Colloquium vorgestellt, Feedback von Christopher Cohrs (UB) eingeholt
- Siehe Auszug DC Präsentation (anbei)


### Weiterer Prozess

- 3-5 Weitere Probeläufe
- Vorläufige Analyse muss wahrscheinlich entfallen (kleines N)


### Offene Fragen

- Metaconsensus weiter spezifizieren; was ist damit gemeint?
- 1--3 Q-Sorts?
- Präferenzen (Steuern) in den Q-Sort?


## Status Konferenz-Planung

-


### Offene Fragen

- Praktiker für das Panel? (Steuerberater, Finanzbeamte, Bund der Steuerzahler)



## Status Moderation

- Planungstreffen mit Moderator_innen am 4.8. in August


## Status Pressekonferenz, Ergebnisse

Pressekonferenz muss video aufgezeichnet werden.

Feldtagebuch zu schreiben.




## Status Infobroschüre/Lernphasen

- Siehe Anhang.


### Experten

- Dennis Dittrich (Jacobs)
- Karlhans Sauernheimer (em., Uni Mainz)
- Wolfram Elsner (Uni Bremen)

- Philipp Genschel (Jacobs, Ausland?)
- Stefan Traub (angefragt)


(This was prepared for meetings with Matthijs Bogaards in the summer of 2013.)


# Designing Fora for Deliberating Tax Choice – Alternative Operationalizations for a Quasi-Experiment

Maximilian Held, Bremen 01.06.2013


## Preliminaries

- This is in fairly colloquial language and style; will change it once we agree on one format and make this part of the proposal.
- I have concentrated on the practical choices (when’s the coffee break) in hosting such a forum (not so much deliberative theory).
- Especially in Plan A (see below), I have prioritized the substantive demands of deliberation over the research design -- if that’s even a meaningful alternative.
	I thought it first important to operationalize a doable, but still concept-valid deliberation.
- Feel free to comment anywhere. Should work without sign-in.


## Strategic Analysis


### What's special about deliberating tax choice?

- Tax offers/demands very structured choices: there are essentially only 4x3 broad tax types (see tax table in drafts).
  Different from, for example, a deliberation on “racial tensions”, deliberating tax choice is more close-ended.
- Tax expertise is easily politicized, because:
	- Tax cannot be reduced to an empirical question, both because inframarginal data is not available, and because macroeconomics is incompletely understood.
	- Tax cannot be reduced to a consequentialist inquiry, because people (may) care about other normative claims, too (e.g. fairness).
- Tax cannot be easily (if at all) dumbed down to subsets of tax choice (e.g. VAT vs PIT), or subsets of abstractions (e.g. only “bastard keynesianism”) for two reasons:
	1. Any such reduction would violate the spirit of deliberation; citizens could not set their own agenda.
	2. Any such reduction may well fail to elucidate my hypothesized misunderstandings: ßI imagine “understanding tax” as a bucket, which, if leaky will drain to the lowest level. For example, if deliberators would discuss most aspects of taxation, but skip over the limits (!) of price controls, they may well opt for price controls in lieu of, or in addition to taxation.
- Meaningfully deliberating tax requires a lot of knowledge, and that knowledge is unlikely to spring merely from the act of deliberation, but it needs some input.


### SWOT Matrix

|                   |   *Helpful*   | *Harmful*  |
|-------------------|---------------|------------|
| *Internal Origin* | Strengths     | Weaknesses |
| *External Origin* | Opportunities | Threats    |


#### Strength

1. I hopefully have a fairly consistent, comprehensive and uncontroversial account of what deliberators need to know (the drafts).
	It’s reasonably well-structured.
2. I have a list of quite open-ended questions that should guide the deliberation, without prejudice to one or the other tax choice.
	(I don’t actually advocate the PCT anymore -- but it’s question needs to be raised).
	I have developed an account that lays bare the remaining disagreements and tradeoffs between experts and choices.
3. I have some experience in explaining this stuff to lay audiences (Science Slam) and in organizing small-scale fora (Akademie Res Publica).


#### Weaknesses

1. I have a stake in this, I have found some of these taxes to be vastly more attractive than others, and tend to attribute any dissenting opinion to some “misunderstanding”.
2. When talking about this, I easily regress into a (wannabe) microeconomics-teacher, which may not be an appropriate style for a deliberation.
3. I have never witnessed, participated in, let alone run a deliberative forum.
	There may be many known (moderation, scheduling, briefing material) and unknown (?) unknowns.
	In particular, I know little about pedagogy and small group psychology.


#### Opportunities

1. (Self-selected) people might actually enjoy deliberating tax.
	Grasping some of the abstractions they have heard about might empower them as citizens.
2. People can relate their personal experience to the abstractions presented.


#### Threats

1. SES-graded, unequal participation may remain/result, especially because tax tends towards academic abstractions.
2. Political apathy may remain/result, especially because fundamental tax reform cannot even be done at the national level and may face other hurdles.
	Participants will in no way have some actual decision-making power over the subject of their deliberation.
3. The deliberation might regress into a microeconomics class, where deliberators look for “right” or “wrong”, rather than empower their own voices and intersubjective understandings.


### Strategic Fit

A fitting deliberative format for my project...

1. Includes a strong learning component, structured roughly along my drafts -- but shorter, and in more accessible style.
	(It must not be a microeconomics text).
2. Relates these abstractions to personal experiences and intersubjective value judgments.
3. Prioritizes intensity (duration) over representativeness (sample size) under given constraints (time, money).
4. May involve me and existing material for the learning component, but someone else must moderate the deliberations.
5. Starts from a small-scale, face-to-face deliberation as a pilot study, both to guarantee concept validity and because I have no idea about deliberation-


## Research Design

This will produce (small-n) data, that may not lend itself to a conventional quantitative DP-research design (essentially a within-subjects Likert-type data).
A small sample may not be statistically powerful enough to produce significant effects.
Instead the same quasi-experimental design could be run with qualitative data, including, open-ended questionnaires and/or semi-structured interviews, or even a record of the deliberations.
Such data could be content-analysed (or rather: coded) to distill the (mis)understanding before and after the treatment.


## Choices


### Button 2005

```
\cite[loc. 594]{Button2005}
```

This project should be in the bold cells.

|                                    |  *Self-selected participants* |     *Randomly-selected participants*    | *Stakeholder-selected participants* |
|------------------------------------|-------------------------------|-----------------------------------------|-------------------------------------|
| *Initiated by a civic association* | School-based deliberation     | -                                       | National Issues Forum               |
|                                    | Chicago PD deliberation (...) |                                         | Study Circles (...)                 |
|------------------------------------|-------------------------------|-----------------------------------------|-------------------------------------|
| *Initiated by an NGO*              | **National Issues Forum**     | **Deliberative Poll**                   | National Issues Forum               |
|                                    | **AmericaSpeaks**             | **Citizen Juries** (aka Planning Cells) | Participatory Budgeting             |
|                                    | **online dialogues**          | (...)                                   | (...)                               |
|------------------------------------|-------------------------------|-----------------------------------------|-------------------------------------|
| *Initiated by government*          | Town Hall meetings            | Deliberative Poll                       | Deliberative city planning          |
|                                    | local councils                | Citizen Juries                          | participatory budgeting             |
|                                    | (...)                         | (...)                                   | (...)                               |
|------------------------------------|-------------------------------|-----------------------------------------|-------------------------------------|


### Own Typologies

This project should be in the bold cells.

|                     |        *Short duration*       |                   *Long duration*                   |
|---------------------|-------------------------------|-----------------------------------------------------|
| *Large sample size* | Deliberative Poll             | Citizen Assembly (BC: Electoral reform)             |
| *Small sample size* | Citizen Jury / Planning Cells | Consensus Conference (Australia: GMOs, NZ: Biotech) |


|                                |       *Limited and/or positive knowledge*        |       *Knowledge-intensive and/or contested*      |
|--------------------------------|--------------------------------------------------|---------------------------------------------------|
| *Unstructured ex-ante choices* | National Issues Forum (race in Philadelphia, PA) | Deliberative Poll (Texas: Energy)                 |
|                                |                                                  | Consensus Conferences (Denmar, Canada, Aus: GMOs) |
| *Structured ex-ante choices*   | Deliberative poll (Jacobs community service)     | **Citizen Assembly** (BC electoral reform)        |
|                                |                                                  | Planning Cells                                    |
|                                |                                                  | Consensus Conferences                             |
|                                |                                                  |                                                   |

(By stuctured ex-ante choices, I mean an issue which allows only finite, discrete and well-defined policies, as taxation does.).


## The Plans

*in descending order of attractiveness*


### Plan A: Citizen Council / Consensus Conference on Tax Choice (working title)

similar to:

- Citizen Assembly (large n): British Columbia Citizens’ Assembly on Electoral Reform. (2004). Making Every Vote Count - The Case for Electoral Reform in British Columbia. Techreport.
Citizen Jury (medium n): Crosby, N., & Nethercut, D. (2005).
- Citizen Juries - Creating a Trustworthy Voice of the People. In J. Gastil & P. Levine (Eds.), The Deliberative Democracy Handbook -- Strategies for Effective Civic Engagement in the Twenty-First Century. New York, NY: Wiley.
- - Consensus Conference (small n): Lee Kleinman, D., Powell, M., Grice, J., Adrian, J., & Lobes, C. (2007). A Toolkit for Democratizing Science and Technology Policy: The Practical Mechanics of Organizing a Consensus Conference. Bulletin of Science, Technology & Society, 27(2), 154–169. doi:10.1177/0270467606298331


- 8-16 participants (depending on funding) (Crosby et al suggest a maximum of 24 for meaningful plenary sessions). \cite[loc. 1888]{CrosbyNethercut-2005-aa}
- 5-7 days (depending on funding)
- face-to-face, all-day including common lodging and meals
- Includes learning phases, expert panels and small group / plenary deliberation, modelled roughly on the Citizen Assembly (electoral reform in Britsh Columbia)
- Deliberators are briefed with an extensive issue book, material is reviewed during the deliberation.
- Issue book and learning phases are “vetted” by a diverse panel of economists (e.g. Hickel, Traub, Sauernheimer, Frank)
- Learning phases are held by Max Held, organized along questions from draft chapters on tax and mixed economy, reframed for maximum accessibility.
	Learning phases are interrupted by moderated, small-group sessions, in which deliberators reflect on what they have learned and relate it to personal experience, judgements and understandings.
	Crosby et al. stress face-to-face, extended interviews of expert witnesses, rather than written issue books or presentations (\cite[loc. 1899]{CrosbyNethercut-2005-aa}
	Carson & Hartz-Karp recommend panels of stakeholders, instead -- I'd rather go with scientists, because stakeholders (political parties etc.) are way too deep in this game already, and may fail to ask the deepest, most relevant questions about tax.
- Deliberation phases are held (in plenary and small groups) by 2-3 trained moderators.
	Moderators guide the discussion and encourage an agenda of questions, but are not experts in the field.
	Max Held does not participate in the deliberation phases.
	(Supposed expertise must not silence debate or dissent).
	People with experience in teaching, intercultural communication or community organising might make good moderators (e.g. Anja Jungermann).
- The sample is *not* representative, but seeks to maximize diverse backgrounds, experiences and preferences.
	It’s a *saturation* / stratified ranom sample. Details
	- A random sample is drawn and invited to “apply”.
		If no random sample can be drawn (expensive), a random geographic walk of households and within-household randomization might do.
		People are asked to provide some SES-data.
	- From the (self-selected!) applicants, a saturation sample of 8-16 or so people is constructed, who are invited to participate.
- Set-up:
	- People from around Bremen (to reduce travel cost) are lodged together.
	- Meals are prepared together both to forge understanding, and to reduce cost.
		Citizens can suggest recipes, staff will provide ingredients.
	- Sessions are held in office rooms available at Jacobs University or Uni Bremen.
	- No or only a small (50-100 EUR) honorarium is granted, but all costs (including local travel) are covered.
		On-site child-care is offered.
		Crosby et al suggest a “decent day’s wages” as per diem, but I may not be able to fund that \cite[loc. 1899]{CrosbyNethercut-2005-aa}.

A preliminary (very rough) draft schedule:

|              |                    Tuesday                     |                Wednesday                |                      Thursday                      |           Friday           |                  Saturday                  |            Sunday            |            Monday           |
|--------------|------------------------------------------------|-----------------------------------------|----------------------------------------------------|----------------------------|--------------------------------------------|------------------------------|-----------------------------|
| 09:00-09:30  | Arrival                                        | Learning: Ends of the Mixed economy     | Learning: Tradeoffs, Smoke/mirrors real dissavings | Learning: Optimal Tax      | Learning: Incidence of Tax/Elasticity      | Free Time / Church Service   | Learning: Tax Choice        |
| 11:00-11:30  | Introduction                                   | Small Group: Ends of Mixed Economy      | Small Group: Tradeoffs, Smoke/mirrirs, dissavings  | Small-Group: ptimal Tax    | Small-Group: Incidence                     | Plenary: Preparing Questions | Small Group                 |
| Lunch Break  |                                                |                                         |                                                    |                            |                                            |                              |                             |
| 14:00-15:00  | Small Group: Experience and Questions with Tax | Learning: Means of the Mixed Economy    | Plenary: Summary                                   | Learning: Just Taxation    | Learning: Schedule, timing/Neutrality      | Experts Panel: Q&A           | Plenary: Write up of Report |
| 16:00-17:30  | Plenary: Report on above                       | Small Group: Means of the mixed economy | Learning: Overview of existing taxes               | Small Group: Just taxation | Small Group: Schedule, Timing & Neutrality | Plenary: Reflection          | see above.                  |
|              | Learning: Distilling guiding questions         |                                         |                                                    |                            |                                            |                              |                             |
| Dinner Break |                                                |                                         |                                                    |                            |                                            |                              | Farewell Dinner             |
| 20:00ff      | Movie: 12 Angry Men                            | tba.                                    | Games Night                                        | tba.                       | tba.                                       | tba.                         | Departure                            |


#### Advantages

- I can learn and study deliberation, starting from the smallest scale, exposing my research interest to rich procedural data, and allowing other qualitative data (semi-structured interviews).
- The format stays true to the substantive demands of deliberative democracy -- as much as possible under given constraints.
- The format allows citizens to learn about relevant abstractions in tax, and relate them to their own experience to form a preference.
- Validity may be relatively high.


#### Disadvantages

- The format does not scale easily, if at all.
- The sample will be heavily skewed, because of interest, time (5-7 days!) and other factors. Non-response will probably be high.
- The sample will be too small to yield statistically significant results, impact may be limited and reliability may be low.

It will be important to reserve enough time for the deliberative phases, and to encourage that citizens come up with their own concerns, possibly in conflict with the (microeconomic) orthodoxy presented in the learning phases.

Moreover, citizens should be informed up-front what the scope of the deliberation is (tax choice), including its limitations, and they should be encouraged to argue and note wherever they find this framing limiting or inadequate.


### Plan B: A “Deliberative” Class on Tax

```
(similar to: Sliwka, A. (2005). Das Deliberationsforum - Eine neue Form des politischen Lernens in der Schule. Berlin.)
```

- 2-week (summer school @ Deutsche SchülerAkademie) or 1-semester (UB or Jacobs) undergraduate seminar on tax choice.
- Schedule might be roughly as above.
- Students themselves would moderate.


#### Advantages

- Cheaper and easier to organize.
- Varying levels of education, SES probably less of an issue (that’s also a disadvantage).
- I have some teaching experience.


#### Disadvantages

- Sample will be completely self-selected, comparatively homogeneous group (high SES, young). Results may not be surprising; it’s “too easy”.
- Format will easily tend to an introduction to microeconomics, with clear notions of “true” and “false”, which may impair deliberation.
- It may be hard to break or circumvent the conventions (grading!) and expectations (hierarchy!) of academic teaching to enable true deliberation.


### Plan C: A Deliberative Massive Online Open Course (D-MOOC) on Tax

- Much like the above class and schedule, but hosted online.
- Deliberation may be conducted in small-group video-chats.


#### Advantages:

- Can reach a large n.
- Web-based services (Google, Iversity, …) are well-developed and very cheap.
- May scale easily, and at low cost.
- Is more flexible, can be iterated.


#### Disadvantages

- High production value web-content is expensive and difficult to create (needs illustrations, producers, etc.)
- Sample will be extremely self-selected, and may display further self-selected attrition. Will skew young and high SES and (probrably?) left-of-center (Pirates).
- Foregoes the face-to-face dynamics and concentration of a physical deliberative forum.


Other web-based approaches (none of which are truly deliberative):

- Fishkin does it (wants to do it), too!: http://www.managementexchange.com/hack/deliberative-corporation
- e-thePeople.org somewhere between abgeordnetenwatch.de and wahlomat.de
- Liquid Democracy Piraten Partei project and platform. Processes, practices and usage still unclear / in flux.
- http://www.meetup.com/ platform to schedule, identify physical neighborhood meetings.
- MoveOn.org rather a web forum for progressives, rather partisan.


## Next Steps

1. Discuss analysis and suggestions with primary advisors, Matthijs and Olaf.
2. Get feedback on suggested forum from people experienced in deliberation.
3. Budget and schedule event.
4. Apply for budget.


## Next Next Steps

1. Look into pedagogy and didactics of economics.
2. Identify and coordinate with moderators.
3. Identify and coordinate with experts.
4. Draft issue book and plan learning phases.
5. Vet issue book and learning phases with expert panel.
6. Invite participants.

---

# Field report
anwogessel@yahoo.de (anonym) has some skepticism (see email), generally makes me wonder whether there are people who are just too angry and distrustful to participate, or whether they indeed have a point, as in:
- is this indoctrination?
- does this only attract like-minded people?
- shouldn't this be left to pluralism? (ha!)

---

DGB Telefonat

Mit Anette Düring, Regionsvorsitzende, hatte Email gelesen, war extrem aufgebracht, ärgerlich, sie hat kein Interesse daran.
oh man, manchmal verstehe ich diese Welt einfach nicht. Ich habe beim DGB Bremen (endlich) jemanden telefonisch erreicht, und die Frau (Vorsitzende Bremen) war extrem aufgebracht, sie hätten an sowas kein Interesse, würden mir auch nicht sagen warum, und auf emails wie meine bräuchte sie auch nicht zu antworten.

---

notes on recruiting:

you have to start somewhere, that’s pretty hard. You need trust, and some structure.
That leads back to corporatism (as social capital, not as interest representation), and as harbingers of a sense of citizenship – and to social capital proper (people who know people).

It’s not even clear whether a proper random sample (say, by drawing from the books) would be that much better – maybe it would be, maybe not. Maybe it would lack the kind of public spiritness that this process selects for.

Also, this kind of recruitment is a lot more open – but systematically biased in many ways.

Good news: it also serves as its own PR; more people get to know about this thing, they *had* a chance to participate (which they would never have had if only random luck had chosen them).

Besides, it’s not clear that we need random sampling, maybe we need theoretical sa

---

hate mail auf Facebook

Nicola Schöning Das ist doch totaler Quatsch, würde bedeuten ich habe umsonst drei Jahre tagein tagaus das "tolle" deutsche Steuerrecht gepaukt....ich hab zu der Zeit Urlaub, aber nach dem Stress ist mir meine Freizeit heilig, anstatt mir so einen Quatsch anzuhören...

---

afraid of unemployed people

why are they so afraid?
do they resent academia?

---

videoconference with facilitators

think through the didactics, do something tangible, where people can move, do stuff. maybe a ballet for the economic cycle, also something for tax base and schedule
do a fishbowl after the learning phase, to harvest questions (“ich hab’ das so verstanden”)
problematize (this is via Anne) models; they always only tell part of the story
begin the first round by telling stories
don’t explain more outside of groups: we’re doing this because we want to advance to the stuff that people can disagree on; not factual questions, those are the most interesting ones
consider doing dinner outside
get mic and speakers
figure out a video or something else that will tease on people, make them think about this
cc moderators
do the press conference outside?
do a fishbowl for a press conference
get fruit for coffee breaks
get a fireplace
remember to work out


---

People asked for second lernphase when the whole thing was done after 2nd q sort (5-6 people)

Grußwort CiviCon



Das beste Argument für Demokratie ist ein 5-tägiges Gespräch mit unseren Bürgerinnen und bürgern.

Ich will Ihnen ein Geheimnis verraten. [...] Wir lesen und schreiben Gedichte nicht nur so zum Spaß. Wir lesen und schreiben Gedichte, weil wir zu Spezies Mensch zählen, und die Spezies Mensch ist von Leidenschaft erfüllt; und Medizin, Jura, Wirtschaft und Technik sind zwar durchaus edle Ziele und auch notwendig; aber Poesie, Schönheit, Romantik, Liebe sind die Freuden unseres Lebens. Ich möchte an dieser Stelle Whitman zitieren, »Ich und mein Leben ... die immer wiederkehrenden Fragen, der endlose Zug der Ungläubigen, die Städte voller Narren. Wozu bin ich da? Wozu nützt dieses Leben? Die Antwort. Damit Du hier bist. Damit das Leben nicht zu Ende geht. Deine Individualität. Damit das Spiel der Mächte weiterbesteht und Du deinen Vers dazu beitragen kannst.« Damit das Spiel der Mächte weiterbesteht und Du deinen Vers dazu beitragen kannst. Was wird wohl Euer Vers sein?”

Hinweis auf das nächste Mal: Anmelden auf http://www.civicon.de



Pressetelefonate:

Weser Kurier
Landwehr Rückruf 0421 36713610 / Block
NDR Oldenburg
maybe
Taz Bremen
interested, but understaffed

This IS teilnehmende Beobachtung


Pressetelefonate:

Weser Kurier
Landwehr Rückruf 0421 36713610 / Block
NDR Oldenburg
maybe
Taz Bremen
interested, but understaffed
Radio Bremen 4
maike evers
Sat 1 Regionalfernsehen
NDR4 Info
040 41560 3925
NDR Fernsehen Hallo Niedersachsen
halloniedersachsen@ndr.de


CiviCon speech notes

Apple commercial quote.

Das beste Argument für Demokratie ist ein 5-tägiges Gespräch mit unseren Bürgerinnen und bürgern.

Ich will Ihnen ein Geheimnis verraten. [...] Wir lesen und schreiben Gedichte nicht nur so zum Spaß. Wir lesen und schreiben Gedichte, weil wir zu Spezies Mensch zählen, und die Spezies Mensch ist von Leidenschaft erfüllt; und Medizin, Jura, Wirtschaft und Technik sind zwar durchaus edle Ziele und auch notwendig; aber Poesie, Schönheit, Romantik, Liebe sind die Freuden unseres Lebens. Ich möchte an dieser Stelle Whitman zitieren, »Ich und mein Leben ... die immer wiederkehrenden Fragen, der endlose Zug der Ungläubigen, die Städte voller Narren. Wozu bin ich da? Wozu nützt dieses Leben? Die Antwort. Damit Du hier bist. Damit das Leben nicht zu Ende geht. Deine Individualität. Damit das Spiel der Mächte weiterbesteht und Du deinen Vers dazu beitragen kannst.« Damit das Spiel der Mächte weiterbesteht und Du deinen Vers dazu beitragen kannst. Was wird wohl Euer Vers sein?”

Hinweis auf das nächste Mal: Anmelden auf http://www.civicon.de



kürzlich verstorbene Robin Williams


"Das beste Argument gegen die Demokratie ist ein fünfminütiges Gespräch mit dem durchschnittlichen Wähler.”

Wir sagen: das beste Argument für Demokratie ist ein fünftägiges Gespräch mit Bürgerinnen und Bürgern wie Sie und ich.


Der Zweck von menschlicher Sprache ist...


civicon quote (for the incidence day): the curious task of economics is to ..

also: man works to live / live to work about the fischergleichnis böll story

Prof. Dr. Johannes Hackmann
Seyedeckreihe 11
D-22043 Hamburg
Tel.: 040/6523 775
Email: hackmann[at]unibw-hamburg.de


Gespräch Vogel Kleinunternehmern mit Karr Langezeit arbeitslos will bewusst nicht arbeiten, reden über wertschätzen

zitat: der mensch lebt um zu arbeiten

Kowalski radio bremen bremen1

0151 12711128

Freitag Abend 19:00

sonst Donnerstag


BIGSSS / Uni

The german state university combines some of the worst of two worlds: the faddishness, senseless human churn and unfairness of markets, and the inefficiency, stupidity and inflexibility of state plans, all in an effort to regulate a crucial activity which can neither be planned, nor incentivised: human discovery.

With this, probably unindented, goes away any chance at genuine creativity. Decades from now, no one will remember these edited volumes.

Or maybe, in a more benign fashion, this is not an accident, but it is the plan; to colonise the always anarchic realm of academia, and to make sure that between all the drittmittelantrag, ha-reform etc. no actual criticism of the status quo will ever be formulated.

A good example of this are the research areas, trumpeted an an increasingly byzanthine network of webpages and interlinked institutions. For often than not, if you ask the participating researchers honestly, these labels are non-labels (and also impenetrable newspeak).

They serve no purpose other than to boggle up resources. In the best of cases, these researches will ignore their supposed research topic and continue as they otherwise would. In the worst case, they will actually squeeze their research interest into these topics, which – you don’t need to be a Foucault-reader to see it – always implies a political agenda.

This too, is policy-based evidence making.

So what is to be done?

get the state out of it, as much as possible.
And don’t fool yourself into believing that quasi-market institutions work here.

They won’t.

Sure enough, scientists bear responsibility for the privilege they gain. But you can’t legislate or control that. You can hope that many academics will use some of the time to explain to the public what they’re doing.

And, as hard as that sounds, but we might just have to live with the fact that Science has a lot of unknown unknowns.

Engaging on that discovery, nonetheless, that’s a promise of modernity worth fighting for.

videoconference with facilitators

think through the didactics, do something tangible, where people can move, do stuff. maybe a ballet for the economic cycle, also something for tax base and schedule
do a fishbowl after the learning phase, to harvest questions (“ich hab’ das so verstanden”)
problematize (this is via Anne) models; they always only tell part of the story
begin the first round by telling stories
don’t explain more outside of groups: we’re doing this because we want to advance to the stuff that people can disagree on; not factual questions, those are the most interesting ones
consider doing dinner outside
get mic and speakers
figure out a video or something else that will tease on people, make them think about this
cc moderators
do the press conference outside?
do a fishbowl for a press conference
get fruit for coffee breaks
get a fireplace
remember to work out



afraid of unemployed people

why are they so afraid?
do they resent academia?



hate mail auf Facebook

Nicola Schöning Das ist doch totaler Quatsch, würde bedeuten ich habe umsonst drei Jahre tagein tagaus das "tolle" deutsche Steuerrecht gepaukt....ich hab zu der Zeit Urlaub, aber nach dem Stress ist mir meine Freizeit heilig, anstatt mir so einen Quatsch anzuhören...


you have to start somewhere, that’s pretty hard. You need trust, and some structure.
That leads back to corporatism (as social capital, not as interest representation), and as harbingers of a sense of citizenship – and to social capital proper (people who know people).

It’s not even clear whether a proper random sample (say, by drawing from the books) would be that much better – maybe it would be, maybe not. Maybe it would lack the kind of public spiritness that this process selects for.

Also, this kind of recruitment is a lot more open – but systematically biased in many ways.

Good news: it also serves as its own PR; more people get to know about this thing, they *had* a chance to participate (which they would never have had if only random luck had chosen them).

Besides, it’s not clear that we need random sampling, maybe we need theoretical saturation, that might make more sense for Q method.


you have to start somewhere, that’s pretty hard. You need trust, and some structure.
That leads back to corporatism (as social capital, not as interest representation), and as harbingers of a sense of citizenship – and to social capital proper (people who know people).

It’s not even clear whether a proper random sample (say, by drawing from the books) would be that much better – maybe it would be, maybe not. Maybe it would lack the kind of public spiritness that this process selects for.

Also, this kind of recruitment is a lot more open – but systematically biased in many ways.

Good news: it also serves as its own PR; more people get to know about this thing, they *had* a chance to participate (which they would never have had if only random luck had chosen them).

Besides, it’s not clear that we need random sampling, maybe we need theoretical saturation, that might make more sense for Q method.


Ideal: Citizen Scientists

this could be down for a longer period of time, maybe several weeks per year, and these people would return to their communities and be knowledge about some things in great detail.

It’s not so much about teaching these people what’s going on, but about making them ask their own questions – they become, rather than learn from scientists.

Oddly, these lay scientists may be the bests scientists all around; because they are pragmatic, and they are unencumbered by strategic considerations that all to often plague the modern economy.


DGB Telefonat

Mit Anette Düring, Regionsvorsitzende, hatte Email gelesen, war extrem aufgebracht, ärgerlich, sie hat kein Interesse daran.
oh man, manchmal verstehe ich diese Welt einfach nicht. Ich habe beim DGB Bremen (endlich) jemanden telefonisch erreicht, und die Frau (Vorsitzende Bremen) war extrem aufgebracht, sie hätten an sowas kein Interesse, würden mir auch nicht sagen warum, und auf emails wie meine bräuchte sie auch nicht zu antworten.


Karlheinz Gerhold von der Finanzverwaltung Bremen würde gern mitmachen – als Experte?

Manfred Palm notes that more incremental formats (just a half day, then ask for more) might work better, and would like to see more concrete information on the brochure. Maybe needs longer brochure.

anwogessel@yahoo.de (anonym) has some skepticism (see email), generally makes me wonder whether there are people who are just too angry and distrustful to participate, or whether they indeed have a point, as in:
- is this indoctrination?
- does this only attract like-minded people?
- shouldn't this be left to pluralism? (ha!)


Give n’ Take

I have added three example issues to maxheld83/samuelson
Please do not be confused by any changes in civicon/samuelson; there will be a lot.
For future uses/transparency, it would be great if we could keep the meta-communication (issues on github) etc. in english.
Uploaded the overview of all taxes to both STiNE and Google Drive
Uploaded `Niemeyer2007` to STiNE (it’s been on google Drive already); this is the closest thing to a written formulation of the conception of deliberative democracy that undergirds this class, namely, that deliberative democracy “has occurred” if people display meta-consensus (they agree about the nature of choices in beliefs, values, preferences) and intersubjective rationality (people who have the same beliefs and values want the same preferences, and vice versa). Consider this merely a nice add-on, or maybe something you can go back to later in your studies; it’s in no way crucial for the writing task at hand here.
You asked for a presentation for the stuff I talked about in the first session; I do not have a presentation on that per se. I will upload whatever I sketched on the board (see below) and point you to the video and Niemeyer-2007 (see above). In any event, this was merely to set the scene, and will not be important for your writing.
Will schedule office hours in September. We’ll doodle that in early september.
Uploaded all the pictures I took in class to Google Drive and (as a zip) to STiNE.
You can find the formalities for the Hausarbeit-replacement-assignment as a milestone and description on github: https://github.com/maxheld83/samuelson/issues/milestones
You can find the substantive notes for the Hausarbeit-replacement-assignment as a README.md right in the main of github: https://github.com/maxheld83/samuelson . This replaces the traditional essay prompt or Aufgabenstellung.
You really, really, really should add issues before you start work, so I can comment on them and give you some (hopefully helpful) guidance.
You asked for some more documentation on the technology of github etc. Here it comes, in decreasing order of importance:
Github (this is the provider of git we’re using): https://guides.github.com
gitbook.io (this is the tool that translates folders full of markdown files into a webpage and other book formats): http://help.gitbook.io
Git (this is the open source version control system that runs underneath): http://git-scm.com
Atom (this is an open source editor for all kinds of files, including markdown, with handy git integration. Completely optional, but awesome: now also for windows: https://atom.io
This is a website with some tech links I wrote for another class I am teaching: https://github.com/BildungBegabung/emile/wiki/Technik
This is a workshop I am holding in the fall, covering github, gitbook etc, (might be too late for you guys): http://www.maxheld.de/i-heart-txt/


## Random notes on Sampling

### (via audio note on 2014-07-25)

There seem to be several standards that might work for civicon sampling:

1) Public relations and impact: you need a self-selected sample, and just a lot of ads. Self-selection raises awareness, because here, a self-selected sample, everyone *could* have applied
2) Random sample undertaken by polling firm may be ideal for representativeness, but it might not raise awareness as much.

Whether society notices recruiting or not matters a great deal, not just to push deliberative democracy, but also simply to strengthen concept validity of the format, or make it externally valid.
There needs to be something at stake; and that doesn't work in this case because there is no external mandate or actual decisions to be had, not a constitutional mandate anyway.
The only thing you might have that matters is that people listen to the results, and find it important.
That might need much more money and professional PR, maybe something an external foundation could pay for.

But it also matters for the research, because this raises the stakes and establishes concept validity.


### (via audio note on 2014-07-14)

Finally, ideally you won't need the PR strategy, because with a constitutional mandate, a civicon should "spin itself " – but that's not happening anytime soon.
Civicon should probably be an independent format with some gravitas and an established brand before it enters into any formal relationship with the state, which may otherwise really interfere with its operation.
Or maybe not?
Maybe I am wrong about that.

I need a visualization that shows the demand for a good civicon
Actually, you need a n argument why long, why complex civicon.
Then you need the same thing for different civicon,s what gives them enough people, such as money, venue, PR.
Which of these is important for the IMPACT factor and which for REPRESENTATIVESS of the sample (2x2 table anyone?)


### science ethics in the experiment (via audio note on 2014-07-14)

Also notice the conundrum that for all practical intends and purposes it would be easier if I could make people sign people a paper that forces them to participate, and then to pay pack some money if they drop out at the last minute.
But that would be completely unethical probably generally because of scientific informed consnet science ethics / experimental ethics: people must always be able to drop out without financial repercussions.
This is especially so in this case, where there are audio and video recordings.
So, no signing.

Generally, it seems hard to underestimate the psychological stress this might piut people under, including confronting their own economic situation.
This will only become more challenging the more diverse the sample becomes.


### optimal human groups -> https://github.com/civicon/civicon.github.io/issues/92


### on reimbursements (via audio note on 2014-07-14)

If you want a representative sample, as in a GSEOP-kind of sample, you might want to have *huge* incentives, especially if you want to attract poor, marginal people, busy people, with kids etc.
The problem then is of course that people might participate *not* as a matter of a citizen right, or even privilege, but simply because they face outrageous incentives.
(This might again mean to treat people as means, not as ends – compare strategic behavior as per Habermas).
That might not be the best idea.
So maybe, after all, you live with it not being representative – just like in elections: there is a huge non-particiupation.
The standard, of course, must be that it must be plausibly possible for everyone to participate.
I have to really be careful here not to construe the format in a way (such as 2 weeks, sleep in communal haousing, enjoy bbq together etc) that the format attracts a certain kind of people, but not others, maybe because it's too intimate for them or just too plain long.
It must not be infeasible for others.
That is a very delecate balance.
Obviously the standards for elections is very low: it does not ask a lof citizens, but a civicon well might.


## Notes during


## On the topic

we need discrete choices for a CiviCon, otherwise we're all over the place, but it needs to be a choice that is relevantly abstract
