# Epilogue

> Hope is definitely *not* the same as optimism. 
> It is not the conviction that something will turn out well, but the certainty that something makes sense, regardless of how it turns out.
>
> --- Václav @HavelDisturbingPeaceConversation1985

<!-- Dr.~Pangloss is really giving optimism a bad name. If anyone is an optimist, it's Candide: ``Let us cultivate our garden.''. -->
<!-- get Cervantes here: the sickest/craziest person is whoever accepts the world as it is, not as it ought to be. -->

<!-- things have gotten worse in the meantime -->

<!-- important point for conclusion: sadly, it's not even that there's a choice between libertarian arrangements and social democratic ones; at least those are *both* carefully thought out, and attractive, if competing visions of human flourishing.
the danger, however is that, perhaps, either side of pragmatic compromise lie not more purer (if disagreeable, to some) arrangements, but a violence and chaos, resurrecting, if anything, the twin mob politics of right fascism and left authoritarianism. (this is quote from @Crouch2004) 
%mob politics of communism and fascism
%both arose out of a particular mismatch b/w the antagonisms of capitalism.
-->
<!-- Because conservative and libertarian analyses mostly proceed by *via negativa*, recommending what *not* to do, these limitations naturally apply more to critical and other approaches calling --- *via positiva* --- for *more*, or different collective intervention [see @taleb_antifragile:_2012]. -->

<!-- TODO scale
maybe scale actually matters, and how every hard deliberation is should be read as an indication to not do this too often, and to concentrate on when we really need to do this -->

<!-- this might all be too little, too late -->

<!-- we're now facing a different battle, for the middle 1/3, and for *some* level of liberal democracy -->

<!-- there is two ways of looking at this: you can say, haha, see, this is what happens because there was not enough deliberation, better mixed econ an so for -- basically retrenching your position.
or you can say, uh-ok, maybe we're really stretching a little thin the bounds of political and economic integration, and the general limits of the political system, so maybe we ought to revert a little.
or maybe a third way is correct: to absolutely not revert, but to concentrate on where we really need this stuff.
to economize on moral disagreement -->
<!-- perhaps history really is smarter Hemerijck -->
<!-- or not?
### Hemerijck
> "I like to believe that history is smarter than I am." (Hemerijck, December 10, 2010)
really?!? I think path dependency is part of the answer why history errs in this case. Before individual (let alone electronic) checking and savings accounts, only an income tax was feasible to achieve some degree of progression. Individual Haig-Simons accounts were simply not available for a large share of the population. In addition, the income tax was, at that point, a powerful tool to get at the supramarginal returns of a capital-owning class. Today, the income tax, or some defunct version of it lingers on for reasons of path dependency. A PCT, indeed, cannot easily co-exist with an income tax. -->

<!-- the libertarian response:
notice here: this gets dicy.
maybe, and this would be worthwhile for the epilogue, the fact that we *can't* get taxation right should be taken as indication that it shouldn't.
mmaybe this really is a pointless illusion, we can't get tax right, at least not at this scale, so we should build political institutions that do *not* in fact rely on this so much.
these *do* exist; smaller scale, shame, etc.
not sure I buy this argument, but it's worth pointing out.
this is the "history really is smarter" part of the argument -->
<!-- this is also, essentially, the second-bester argument, morphed onto democracy, for which it was not intended -->

<!-- following through the libertarian critique, of course, also places this whole 8-year dissertation in a somewhat pale light.
maybe just do things that people find immedietaly helpful, not some self-justifying, reified fighting against windmills. -->

<!-- I guess the naive starting point was that, no you can never argue that x or y can't work in a democracy, because we can't fix the public choice problem associated.
this is somin
%ok, so somin is officially an asshole.
%He wants more Hayek.
%Because th commons can't be governed, let's have more market.
I guess my thinking evolved
in a weird, roundabout way, the demands and intricacies of deliberation, much like public choice, show, essentially, that things are way more complicated, that in hayeks works we don't really know shit about designing institutions
sso maybe, in a roundabout way, they are right -->

<!-- %Thought on Kaplan: he is right to note that Shapiro and other proponents for democracy who say that there are no extra-democratic proponents of democracy to compare it against are correct (this is the substantive vs procedural issue).
%That is tautological, indeed, as Kaplan points out.
%But Kaplan, too, is tautological, when he accepts that principal-agent problems and other dysfunctions can serve to insulate political institutions and thereby make it better, that is a weak-ass response.
%He is emptying the bathtub with the baby in it.
%Kaplan is also himself tautological: panglossian: if you imply that democratic government is corrupted, and therefore, we should resort to market, you are also tautological: by definition, whichever state we observe in the real world, is the best we can get.
%My key point is: democratic governments and markets must be held to completely different standards.
%Democratic government must remain to be the one institution that allows deliberate societal change. -->
<!-- be very careful about this, bit in this conflation (might/right) also is some fascism -->

<!-- %\begin{quote}
%	\emph{``We've got a bad thing made by men, and by God, that's something we can change.''}\\
%	--- Anonymous tenant in \emph{The Grapes of Wrath} \citep[38]{Steinbeck1939}
%\end{quote} -->

<!-- but the libertarian standpoint, loosely speaking, is also empty.
it sounds very elegant, because it scales, because it alleviates us of the colossal headache that is living as men in the plural (arendt)
but it is also empty: because it does not problematize were preferences come from, and it as implausible that they can be planned, as that they come ex-nihilo out of nowhere.
And it is also empty, because libertarians always skirt the question of just *how* even the minimal state institutions *they* like (property rights) come about, and how they can be maintained.
sure, they say, markets actually *evolved* and so did property rights.
but, setting aside the question of whether group selection really works, either in biology or in culture, by the same token you could say, yeah, it sure did.
and so, today, with some of the deepest, greatest markets we have ever had, evolved the welfare state on top of these property rights, because that's just how it works.
the welfare state, after all, *did* evolve.
it's also a bit lazy, because it abdicates responsibility.
and it's good to heed Hayek's skepticism, to be mindful of what we can and cannot do.
but that is not the same as letting it all burn down
that's also not pragmatism -->

<!-- and again, don't confuse this pragmatism with muddling through, or "realism".
they are very different. -->

<!-- %Note in the trust and deliberation discussion Ostrom's conditions to solve CPR problems (communication, small-scale, trust, localized physical setting) -->

## The Great Unravelling: Why we Must Now Embrace Complexity to Avoid a Return to Fascism

With Donald Trump elected to the most powerful office on the planet, Brexit passed, rightwing populists banging on the gates of parliaments and government in France, Germany and elsewhere, we find ourselves in the midst of the greatest assault on liberal democracy since World War II.
Instead of the heralded "End of History" [@Fukuyama1992], we must now consider a broad civilisational regression, and even the return of large-scale violence as [real and frightening possibilities](https://medium.com/@theonlytoby/history-tells-us-what-will-happen-next-with-brexit-trump-a3fefd154714#.dz7g9ccbw).
<!-- also cite collapse jared diamond -->

Calmer minds may find this alarmist; I hope they are right.
But when the downside risks are so enormous, the precautionary principle almost *dictates* alarmism. 
When the stakes are this high, we'd better be safe than sorry.

*Marginal* polling errors notwithstanding, the return of demogoguery and populism isn't exactly a sudden shock, but it calls us all to urgent action.

But first, we need a precise diagnosis of what is going on.

<!-- It's a perfect storm -->


There are already many thoroughly argued explanations out there, including of a global [white identity backlash](http://www.vox.com/world/2016/11/9/13572174/president-elect-donald-trump-2016-victory-racism-xenophobia) [@ivarsflaten-2008, @cederman-wimmer-etal-2010], [widening income inequality](http://bruegel.org/2016/11/income-inequality-boosted-trump-vote/) and postindustrial decay, [cultural](http://www.cracked.com/blog/6-reasons-trumps-rise-that-no-one-talks-about/) [alienation](http://www.tagesspiegel.de/politik/die-globale-klasse-eine-andere-welt-ist-moeglich-aber-als-drohung/14737914.html), education and age.
Perhaps crucially, Trump and other right-wing populist voters may be driven by *loss aversion* concerning their material or (however illegitimate) cultural status, compared to some real or imagined past, as James Surowiecki has recently [pointed out](http://www.newyorker.com/magazine/2016/06/06/losers-for-trump) in the New Yorker [compare @levy-2003, @KahnemanTversky1979].
As always, the preliminary empirical evidence (at least from US exit polls) seems [more complicated](http://fivethirtyeight.com/features/the-mythology-of-trumps-working-class-support/), and many of these *correlations* are also *multi*collinear.

To these, I add a new (if not especially original) hypothesis: Voters turn to right-wing populists, because they seek to avoid the moral and ethnical cognitive load that the abstractions, complexity and interdependencies of the modern world place on them.

And no, this is not just another way of calling Trump-supporters "dumb".
We may all be the 99% ignorant.

Consider, for a first illustration, anthropogenic climate change.
*If* you believe climate change is *a fact*, and if you value -- as is increasingly demanded, and rightfully so -- all *human beings* equally, but also fly across the atlantic to attend a conference of questionable value, as I recently did, then you face a pesky **moral-cognitive dissonance** [compare @festinger-1957].
More than a mere dissonance, this behavior  challenges my comfortable *identity* as a biking, vegetarian, and generally blameless treehugger: turns out, I *did* value the cosmopolitan ego-boost of an international conference more than the people of Bangladesh, my future childrens future and the rest of the planet.
Straightforwardly, I can either own up to this inconsistency (which sucks), or I can change my behavior (which also sucks).
There are, alas, two other ways to resolve the dissonance:

1. I can *discredit the fact* of global warming ("the Jury's still out!"), question the authority of climate scientists ("the climate lobby is corrupted!"), or even reject the entire abstraction of a global climate system out of hand ("but this winter, there was a lot of snow!").
2. I can *discount the value of other human beings*, by straightforward jingoism ("America first!"), subtle privilege ("Flying is part of our transatlantic culture!") or othering racism ("these people only live in huts anyway!")

By forming either, or any combination of these *preferences over these beliefs* [@Caplan2007], I've solved my problem.
Notice that this is quite a taxing problem, it's not just liberal handwringing: to *really* consider the lives of people I have never met, or lives in a distant future, and to relate that to an exciting trip is a mighty ask for a cognitive and moral miser like myself.

To be fair, as someone who has spent all of his adult life arguing things, I can come up with somewhat cleverer-sounding delusions. 
I could argue that I only buy marginal seats at cheap prices, and that therefore, the plane would have flown anyway, and only the marginal CO2e cost of adding my body and bags to the wide-body jet were incurred.
Or I can point out that transatlantic flights *have no carbon-free* substitute (for now), and that if only all other parts of the economy were carbon neutral, then flying would not be a big problem.
In a way, Elon Musk is my Donald Trump: A self-made entrepreneur whose every outlandish utopia I *want* to believe in, because it helps me resolve these pesky inconsistencies.

I have developed this hypothesis in my exploratory dissertation work on public understandings of taxation, as well as personal conversations with AfD-voters and Trump-supporters.
Over the past 10 years, I have studied tax policy and made it my (hopefully) 1% non-ignorant domain.
As it turns out, taxation is marred in abstractions and complex interdependencies, which force you to re-evaluate your conceptions of justice and your own (financial) biography at every juncture.

For example, if you *want* a progressive schedule (rich people paying more as a percentage), *and* you do not want to "punish" people for marrying, then you *will* have to accept that the tax burden of a couple depends on the *distribution* of income between the spouses (stay-home moms with high-earning husbands will do well).
This is not an opinion, it is a logical fact: of the above three oft-desired outcomes, you can only have two [@Moffitt2003: 124, @Dalsgaard2005: 29].
As a voter and as a politician, it is a whole lot easier to disregard this unavoidable abstraction, and to simply demand, or promise a tax system which would support all "working-class families equally", even though that is a fairly meaningless statement in this context.

Most abstractions of tax do not even take the form of a trilemma, and are still cognitively and morally vexing.
For example, most OECD tax regimes do not tax imputed rents from owner-occupied housing (and the US slaps on the infamous home mortgage interest deduction).
To treat renters and owners *equally*, as horizontal tax equity would dictate, we would have to (partly) *tax* house owners on the rents they *would* have to pay for their *own* houses, because this is a capital income, and the otherwise equal renter will have to pay the same tax on her capital income, from, say, a mutual fund.
I would wager that, in the abstract, *most* people would agree that renters and owners should be treated equally.
But faced with the consequence of imputed-rent taxation, many of the (self-selected, small N) citizens I worked with balked at the idea.
They came up with with (very benign) forms of the above-mentioned forms of dissonance resolution: they either rejected the abstraction ("but it's *my* house!"), or they othered-away the equal rights of renters ("they could have bought a house, it's a lot of work!").

I chose these illustrations, because they are the easiest to explain, and the least controversial.
There are other, far more complicated and more consequential abstractions of taxation, including the adequate *base* of taxation, the *incidence* of (corporate) taxes and welfare effects.

What does any of this have to do with President Trump and his supporters?
It has *everything* to do with rampant inequality, low growth, high debt, post-industrial decay, poor jobs and a government structurally unresponsive to resulting voter demands: the whole post-democratic malaise [@Crouch2004].
This is not some inconsequential, wonky distinction.
This fine print makes or breaks the social contract.

Over the past decades, this foundation of the social contract has fractured.
In fact, if you were to purposely design a tax system to protect rich people and heirs while squeezing future generations, poor and middle earners, you could hardly design a more effective regime then the current income tax and value-added tax system [compare @McCaffery2005].
The *tax system really is rigged*, though not in the ways that Donald Trump *or* Bernie Sanders might think: 
it simply presents the legislatures with prohibitively and needlessly unattractive tradeoffs, such as between equity and efficiency.
Predictably, faced with the choice of a rock or a hard place, democratic institutions become unresponsive, and voters feel increasingly disenfranchised.

This might look like a grand conspiracy, but I don't think it is one.
Instead, I fear, it is simply a slowly unfolding trainwreck of fiscal history.
Some people may -- in the medium term -- benefit from a fractured social contract, though any potential sabotage may yet backfire (violence), and I am skeptical whether these beneficiaries ever successfully colluded.
The bigger blame lies with us: the 99% ignorant.

The data from my exploratory (small-N) dissertation study show that ordinary citizens hold staggeringly inconsistent beliefs and values on taxation, which can, at least partly, be explained by their cognitive ease and comfort and as an outlet for resentment against the economic system.
(I am aware that this is not a deductive proof; it is an abductive hunch, but also see @McCaffery2006b, @SausgruberTyran2011).
Absent a deeper understanding, or at least appreciation of complexity, some of the most promising suggestions for reform will never be discussed in such an impoverished political process: a Negative Income Tax [@Friedman1962], a Progressive Consumption Tax [@Seidman1997], a Land Value Tax [@George1879ab], or even a proper Inheritance and/or Property Tax are *all* unfamiliar, complex and demand a recognition of our mutual interdependence.
In 2008, a leading party operative for the Social Democratic Party of Germany (SPD) told me that frankly, a Progressive Consumption Tax was a nice idea, but that it would be too vulnerable to populist attacks to promote.

This is the vicious cycle we find ourselves in: 
a dysfunctional policy makes democratic institutions unresponsive, which frustrates and impoverishes voters, who turn to increasingly populist candidates, who degrade the political discourse, and make it impossible to pass better policy.
This is a democracy, eating itself alive.

Complex policy, of course, is not a recent phenomenon, and voters decades ago were probably not any better equipped to deal with the complexity of their day.
However, background conditions have shifted dramatically over the last decades, exacerbating the mismatch.
On the one hand, the factual complexity has grown, mutual interdependencies have deepened and the moral horizon has widened. 
This process of social integration is unequivocally good, perhaps such reaping of positive-sum cooperation is even the telos of human cultural evolution.
On the one hand, voters have also learned to demand more of government, and traditional political elites (smoke-filled backrooms) and institutions (party affiliation) have eroded.
This process of emancipation and individualisation is also, by and large, a good thing.

These two processes together *do not* in itself "overload government", as conservative critics once feared.
They do, however, demand a lot from voters.
They also open up a tremendeous opportunity on the supply side of politics to engage in *"discursive dumping"*, to dumb down and discredit complexity and interdependence, to offer voters (false) relief from their cognitive and moral loads.
After an initial successful fix, and the following hangover, as voter demands continued to be frustrated, politicians slowly increased the dosage -- from "welfare queen" to "Joe the Plumber" to "death tax", and, ultimately, "Make America Great Again".
This was neither a fast, nor continuous process, but rather, a slow and self-reinforcing  chipping away at communicative rationality, one sound bite at a time, one delusional simplification after another.

This is not yet a rigorously conceptualised hypothesis, let alone a tested one.
As sociological theory goes, it is also pretty banal.

<!-- # This is more than just moral cognition -->

<!-- But it might explain some of the frankly bizarre topics and politics, pedelled by many of these latest, most dangerous right wing populists.
Vaccination and climate "skepticism" (Trump, AfD), an insistence on traditional gender norms (AfD), opposition to "political correctness" (Trump, AfD), rejection of trade (Trump, AfD), assorted conspiracy theories

By any conventional dimensions [e.g. @WelzelInglehart-2003-aa], it is not obvious what, say, an 

But as a latent, and intervening variable, for the above-mentioned theories based on racism and economic deprivation, it might help explain some of t

Realists might respond that democracies have always muddled through.
That is probably and that is certainly correct -- though

What is more, the participating citizens specifically rejected, or were indifferent towards some of the most promising suggestions for reform, such as a Negative Income Tax, a Progressive Consumption Tax, a Land Value Tax or even an Inheritance or Property Tax, perhaps because some of these are unfamiliar, complicated and demand an 


To resolve it, I can own up to that inconsistency, revisit my comfortable identity as a biking, vegetarian, treehugging change my behavior and skip the next time- and CO2e-wasting, but ego-enhancing conference (which sucks).
Al, *or* you resolve it by sufficiently *othering*, say, the people of low-lying Bangladesh, -->

<!-- %Blog post
	%Fortschritt ist, wenn wir etwas (1) gemeinsam Beschlossenes, Vernünftiges und Gutes erreichen, (2) dass uns freier und gleicher macht, (3) auch gegen Widerstände.
%Wir müssen uns also zusammenraufen und der Sphinx sagen, welche Antwort sie für uns alle einloggen soll, damit Fortschritt passieren kann.
%Seit 225 Jahren machen We the People das mit Abstimmungen und Freiheitsrechten.
%In unseren pluralistischen Demokratien kämpfen Interessengruppen um die politische Macht im Staat.
%Bürgerinnen verfolgen diesen Wettkampf in der Zeitung, schließen sich, folgend ihren gegebenen Interessen Gruppen zusammen, wählen die ihnen am nähesten stehende Partei — und das ist dann das gute Ende der Geschichte.
%Oder?

	%Auch auf dem deutschen und europäischen Marktplatz der Ideen sind Dumping-Anbieter unterwegs.
%Unser Politik-Ramsch kreischt nicht schrill, er lullt uns ein in seiner ganzen, miefigen Mittelmäßigkeit:
%konzeptionell, rhetorisch, visionär.
%Wir tauschen keine Argumente aus, denn Basta, es gibt keine Alternative.
%Wir nennen keine Gründe, denn wir nehmen ja “Augenmaß“, “machen unsere Hausaufgaben” und halten unsere “Hände ruhig“.
%Was bedeuten diese betäubend-sinnentlehrten Phrasen?

	%Amerika und uns plagt die gleiche Krankheit, in unserem gemäßigten politischen System schreitet sie nur schleichender voran.
%Es ist eine schlimme Krankheit, bei der sich der demokratische Prozess loslöst von den tatsächlichen Abstraktionen, die unsere Welt regieren und den machbaren Alternativen, die sich unserem Gemeinwesen bieten.
%Entscheidungen werden bestenfalls im Hinterzimmer verkuhhandelt, meistenfalls gewinnt der Status Quo und schlimmstenfalls diktieren wenige Interessierte.
%Wir raufen uns nicht mehr zusammen, wir raufen nur noch zusammen.

	%Früher war nicht alles besser, aber manches einfacher.
%Wenn in den 50er Jahren ein Kumpel für mehr Mitbestimmung die SPD und ein Beamtin für bessere Pensionen die CDU wählten, dann lagen sie damit beide grob richtig, folgten ihren gegebenen Interessen.
%Wenn 2013 eine Häuslebauerin gegen Eurobonds die CDU und eine Bandarbeiterin für paritätische Sozialabgaben die SPD wählt, dann ist das nicht mehr so klar (vielleicht deshalb und deshalb).
%(Glücklicherweise) funktioniert unsere Demokratie nicht mehr als Zuschauersport, in dem wir einfach jeder alle vier Jahre das für sich bessere Team wählt.
%Von den billigen Plätzen ist es einfach verdammt schwer geworden zu sehen, wo das Tor steht.
%Die weiter hinten sitzen können nur hoffen, dass die Trainer es sehen, die Wahrheit sagen, und das Spiel nicht längst gekauft ist.

	%Ich will nicht Politikerinnen verunglimpfen oder Wählerinnen verhöhnen.
%Sie tun, wir alle tun das im gegebenen Rahmen Mögliche.
%Nicht alle Politikerinnen sind schlecht oder alle Wählerinnen dumm, sondern die Institutionen der pluralistischen Demokratie überkommen.
%Die Komplexität und Ungerechtigkeit unserer Welt passt nicht in eine SPON-Fotostrecke, nicht in 1:30 Tagesschau.
%Unser Gemeinwesen braucht keine harte aber faire Arena, sondern die Sendung mit der Maus. -->

## Second Best

#### Second Best.

Today, maybe one of the clearest Panglossian pronouncements comes under the imposing heading of a *Theory of Second Best*, originally formulated by [@Lancaster1956].
As so many great economic ideas, this one has strayed far from its original form, and interbred with ideology to father many illegitimate --- and sometimes deformed --- offspring.

In its initial, rigorous formulation, the Theory of Second Best showed formally that if --- as seems likely --- some conditions for the pareto optimality of markets cannot be meet, it might enhance efficiency to allow additional, possibly offsetting deviations from perfect competition elsewhere in the economy.
Rather than to fight all market failures everywhere in isolation ("piecemeal welfare economics", [-@Lancaster1956 11], @Lancaster1956 suggested that from a general equilibrium view, there may be less demanding *necessary* conditions that could pareto improve the economy, in addition to the often implausible, *sufficient* conditions of perfect competition [-@Lancaster1956 17].
[@TheEconomist2007] explains it beautifully thus:
if your optimal cookie recipe requires chocolate chips and coconut flakes, but you cannot find the chocolate chips, your (second) best bet may be to bake gingersnap, rather than chocolate chip cookies without chocolate chips.
This is the kind of devilish complexity that I allow myself to ignore here, but that policy makers have to consider:
if, for example, research and development are so prohibitively expensive that we absolutely cannot profitably have more than one manufacturer of wide-body aircraft, our (second) best policy may indeed be to stray further from neoclassical doctrine, and to keep subsidizing *The Boeing Company* and *Airbus SES*, so that we can have at least have ourselves a decent, somewhat competitive, duopoly.
There is nothing Panglossian about such hard choices because, it is, in fact, *materially* impossible to develop dozens of competing wide-body designs.
Because for the social sciences --- as for moral philosophy --- *ought implies can*, the second-best of the subsidized Boeing/Airbus duopoly also needs no social scientific explanation.
This *really* is collateral damage to a worthy cause.

After [-@Lancaster1956], however, the Theory of Second Best as slowly morphed into a general skepticism of state intervention, it is now name-dropping "proof" of its *ipso-facto* futility and serves as welcome absolution for the demise of the mixed economy.
@Wolf1987 [@Wolf1979], for example, argued that because governments fail, just as markets do, the second-best response to such market failures may be to just let them be.
You can take this argument to merely logical extremes, and throw out government and democracy altogether.
[@Leeson2009], for instance, wonders whether in some (developing economies) settings, anarchy may not be preferably to predatory statehood, whether, in other words, no state would not be second-better than an inevitably failing government.
[@Caplan2007], in an otherwise thoughtful book, seems to suggest that because voters are so invariably rationally irrational, markets may be second-better than democracy altogether.

This has very little to do with the rigorous argument presented by @Lancaster1956:
he did, at least in [-@Lancaster1956], never consider a constrained government, let alone an incapacitated democracy to be grounds for "second-besting", but, instead even seemed to hope for a government and people powerful and wise enough to heed his call.

This is Pangloss at his finest:
if you assume, as modern-day second-besters do, that the very *means* to deliberately get to a better world --- government and democracy --- are inevitably flawed, you can show, with almost hermetic logic, that whatever world we find ourselves in, must be the best of all *possible* worlds.

In that word --- possible --- lies the catch.
Modern-day second-besters assume that, akin to markets and evolution, government and democracy are *aimless* processes that merely aggregate pre-social, more- or less rational self-interest.
If government and democracy are aimless, it follows --- as it does, in fact, follow for markets and evolution --- that any positive results of government and democracy are beyond reproach, and beyond improvement.
Government failures, as monopoly pricing or an appendicitis, are just *facts*.

Enlightenment, the mother of modern science, did not consider democracy, a merely *positive* affair, but a normative prescription.
[@Kant1785] asked us not to "follow your incentives", but to "act only on that maxim through which you can at the same time will that it should become a universal law" [-@Kant1785 Chapter 11](*ibid.*.
The US Constitutional Convention in 1787, did not just decide to try out this new [fptp]{acronym-label="fptp" acronym-form="singular+short"} way to aggregate preferences, but "We the People" were to do so "in Order to form a more perfect Union".
In a free society, social scientists need not believe in these, or any other ideas, but if they reject them all, they deserve not the air of scientific sophistication in which they cloak their utter cynicism.
As mere accountants of the status quo, their work is anathema to Enlightenment, and they ought to be disowned of the emancipatory heritage that the social sciences were endowed with.

But ignoring, for now, the enlightened humanism that comes part and parcel with the social sciences, the logic of modern-day second-besters is also simply fallacious.
Even if government and democracy turn out to inevitably disappoint, such flaws are *not*, to the social scientist, quasi-material constraints.
Because government and democracy *are* the subject matter for the social scientist, she must not presume, but has to *explain* them.
If we do, as the second-besters, exclude from the first-order alternatives to be explained by second-order theory, those alternatives that the political process *may* corrupt, we have thereby conflated first and second-order theory.
Whatever second-order theory might have to tell us about a corrupted political process, we would never learn, if we did not test for the absence of first-best solutions.
This Frankenstein variant of the Theory of Second Best confuses, as [@Brubaker-2002-aa] succinctly criticized the literature about ethnic conflict, the "empirical data" with our "analytical toolkit":
government failure is "what we want to explain, not what we want to explain things *with*" [-@Brubaker-2002-aa 165, emphasis in original].
