# Well-Structured Hypotheticals {#hypotheticals}

<!-- \subsection{Impotent Redistribution}

\begin{quote}
	\emph{``Advocates of redistributive taxes must wake up and realize that their end is in jeopardy on account of their poor choice of means:
	they are fighting, and losing, the wrong war.''}
	\\*
	--- Edward J.\ \citet[848]{McCaffery2005}
	%add correct citation
\end{quote} -->

<!-- %Ingolfür Blühdorn (2007: 313) writes:
%“Politicization is the realization that established social norms, social practices, and social relations are contingent rather than sacrosanct, that things could also be different and that citizens, individual and collectively, have political agency by means of which alternatives can be explored and implemented.
%This recognition that things could also be different has always been the igniting spark of the emancipatory-progressive movements, and politicization has always been their key strategy.”
%In this thesis, I want to politicize the abstractions and politics of tax.
%This is a normative prescription, but it is also of analytical value.
%If there is indeed another, superior fiscal configuration out there, its absence needs explaining.
%Such an explanation can inform the welfare retrenchment debate, and, possibly, the broader condition of the (pluralist) political economy. -->


<!-- %As any positive methods curriculum teaches: it is just as important to explain why the observed outcome has occurred as it is important to explain why an unobserved outcome has not occurred.
%Only then, if at all, can positive social science capture the causal dynamics of our present day (for a methodological appraisal of the hypothetical, see \citealt{Fearon1991}). -->

<!-- %When \emph{feasible} trumps \emph{desirable} too often and too readily, policy analysts become preference falsifiers \citep{Kuran-1995-aa}, caught up in their own \emph{Spirals of Silence} \citep{Noelle-Neumann1993}. -->

<!-- %why don't we have it?
	%Because it may not be better?
		%requires general equilibrium modeling, utility functions
		%depends on a number of axioms
	%how would it be specified, implemented
		%requires ge model, utility functions
		%modeling grunt work
	%there is an international cooperation problem!
		%requires general equilibrium model, utility functions, game theory
	%domestic, political dysfunctions prevent it!
	%maybe: path dependency, game theory, veto playing, principal agent
	%because people do not want it!
		%survey research, vignette research, experimental economics -->

<!-- %[ ] Tetlock/Belkin about hypothetical
%[ ] Morgan Winship on hypothetical -->


<!-- %\begin{quote}
%	\emph{``It is demonstrable'' said he,``that things cannot be otherwise than they are; for as all things have been created for some end, they must necessarily be created for the best end.
%%Observe, for instance, the nose is formed for spectacles; therefore we wear spectacles.
%The legs are visibly designed for stockings; accordingly we wear stockings.
%Stones were made to be hewn and to construct castles; therefore my lord has a magnificent castle; for the greatest baron in the province ought to be the best lodged.
%Swine were intended to be eaten; therefore we eat pork all year round.
%And they who assert that everything is right, do not express themselves correctly; they should say that everything is best.
%	''}\\*
%	--- Dr.~Pangloss in Voltaire's novella \emph{Candide} (\citeyear{Voltaire1759}: K125).
%\end{quote} -->

<!-- %Note that what Ganghof + Scharpf 2004:
%37 is incorrect in their treatment of capital incomes.
%They are actually taxed, when they are consumed, given that the tax is cash-flow based (dissavings count!).
%Consider the Haig-Simons.
	%This is a widespread misunderstanding of the PCT, particularly with regards to its evil twins.
	%Contact Ganghof + Scharpf about this mistake!

% Fundamental agreement on the likely advantages of a PCT regime has been reached in the (albeit heterodox) economics literature (conceptually Brümmerhoff 1990:
%357ff, empirically Tomer et al.
%2008, normatively McCaffery 2002).

%What Is The Perfect Tax?
%Friedman is actually a fan of the PCT, and has argued to use it to pay for the war effort in the past.
%This is via Robert Frank 2011 (Darwin). -->

Taxation offers highly structured choices along the three dimensions of base, schedule and timing, the first two of which are cross-tabulated in table.
<!-- TODO refer to tax overview table here -->
There can be no meaningful democratic rule on taxation that does not ultimately opt for a definitive mix of distinct combinations along those dimensions.
The choice among these (already high-level) alternatives cannot be abstracted away, or relegated to experts:
it hinges on irreducible moral and causal judgments [for example, @McCaffery2005].

<!-- %what about the distinction about INDIRECT taxes.
%Indirect taxes are taxes levied on entities other than those expected to bear the eventual burden. -->

<!-- Which taxes exist in the real world, and which taxes are conceivable?
It will not be possible to list them all here in all their legal and administrative detail.
Instead, rough archetypes of real existing taxes ([vat]{acronym-label="vat" acronym-form="singular+short"}, [payroll]{acronym-label="payroll" acronym-form="singular+short"}, (Dual) [pit]{acronym-label="pit" acronym-form="singular+short"}, [cit]{acronym-label="cit" acronym-form="singular+short"}, [lbt]{acronym-label="lbt" acronym-form="singular+short"}) will serve to compare them to the three hypothetical (or rare) taxes suggested ([pct]{acronym-label="pct" acronym-form="singular+short"}, [wt]{acronym-label="wt" acronym-form="singular+short"}, [nit]{acronym-label="nit" acronym-form="singular+short"}). -->

<!-- these are first order hypotheticals -->

<!-- we need discrete choices for a CiviCon, otherwise we're all over the place, but it needs to be a choice that is relevantly abstract -->

<!-- this is what the learning phases are about -->

<!-- taxes vs fees vs pigou (tijnbergen!) -->

<!-- find higher equilibria -->

<!-- if there were no other taxes, no fundamental alternatives, no deep disagreement -- then why should we bother for deliberation?
in that case, we might just stick with the status quo, or maybe move on to fix the small stuff, or the really big stuff (capitalism)
in this case, we can really move on from tax -->

<!-- below is old structure, this needs to be astracted away -->

<!-- %Graetz 1979:
%1635 makes my key point:
%the one reason for CIT is that "undistributed corporate income does not escape taxation"
	%abolish business taxation (1636)
	%a corporation has no one "ability to pay" -->

## Taxes on Income

### Taxes on Capital Income

#### Corporate Income Tax (CIT)

\phantomsection
[\[sec:CIT\]]{#sec:CIT label="sec:CIT"}
The [cit]{acronym-label="cit" acronym-form="singular+short"} taxes the earnings
[^1]
of an incorporated firm.
It is usually proportional.
Unincorporated firms do not pay [cit]{acronym-label="cit" acronym-form="singular+short"}, instead their owners owe [pit]{acronym-label="pit" acronym-form="singular+short"} on their business earnings.
[^2]

[cits]{acronym-label="cit" acronym-form="plural+short"} are proportional, with rates around 20% in the EU.
Countries have recently created issued sectoral (trade, finance) or regional (Hong Kong, London) exemptions from the [cit]{acronym-label="cit" acronym-form="singular+short"} to attract investment [@Genschel2009; @Ganghof2007; @Genschel2005].

##### Local Business Tax (LBT)

\phantomsection
[\[sec:LBT\]]{#sec:LBT label="sec:LBT"}
Taxes on local businesses exist only in some OECD countries, including Germany.
In Germany, local authorities can tax local business a progressive tax on their earnings.
Local authorities set the rate of the tax (within federally mandated margins).
Firms are taxable based on the location of their establishments.
Earnings of firms with multiple establishments are weighed by the sum of wages and salaries paid.

### Taxes on Capital and Labor Income

#### Personal Income Tax (PIT)

\phantomsection
[\[sec:PIT\]]{#sec:PIT label="sec:PIT"}
Under the [pit]{acronym-label="pit" acronym-form="singular+short"}, all sources of personal income (labor, capital) are added and taxed under a single schedule.
[pit]{acronym-label="pit" acronym-form="singular+short"} schedules are typically progressive.
Marginal (not average!) tax rates in Germany range from 14% to 42% (Bundesministerium für Finanzen 2009).

<!-- %The personal income tax is usually levied according to a progressive schedule both on labor and capital income.
%Its incidence is borne by the taxed individual, but it disincentivizes work and (risky) investment.
%It taxes capital twice:
%once when it is initially earned and again when it generates an interest.
%Income taxes only on labor (payroll tax, social contributions) can contribute to structural unemployment by raising effective price floors, especially when they are not sufficiently progressive.

%Personal income taxes on capital (\ldots
%gains tax) necessitate a corollary taxation of corporate income.
%Without it, taxpayers could easily evade payment by incorporating capital it in a firm, withdrawing earnings only slowly.
%Corporate income tax rates spill over to personal (capital gains) tax rates (Ganghof & Genschel 2008, Ganghof 2006).
%Like the personal income tax, they depress economic activity.
%Moreover, corporate income taxes are indeterminate with regard to incidence and flat in their progression.
%The tax incidence in a firm on either labor or capital is determined by a host of firm- and market-specific factors, including the relative factor price elasticities.
%Corporate income taxes apply one rate over all shares.
%The lifesavings of a worker, invested in a company through her life insurance, are taxed at exactly the same rate as the share of a stock-market tycoon.
%As the base of the corporate income tax is relatively mobile (compared to labor, consumption), it can easily evade taxation or compete down rates. -->

##### Dual Income Tax (Dual PIT).

\phantomsection
[\[sec:Dual-PIT\]]{#sec:Dual-PIT label="sec:Dual-PIT"}
The [2-pit]{acronym-label="2-pit" acronym-form="singular+short"} is a variation on the [pit]{acronym-label="pit" acronym-form="singular+short"}, where schedules differ between capital and labor sources of income.
[2-pits]{acronym-label="2-pit" acronym-form="plural+short"} burden capital relatively less than labor incomes.
The [2-pits]{acronym-label="2-pit" acronym-form="plural+short"} was introduced to avoid the negative growth effects of high capital taxation (particularly through its , p. ) and to counteract capital flight.

In Sweden, a pioneer of the [2-pit]{acronym-label="2-pit" acronym-form="singular+short"}, the top marginal (not average!) rate for labor incomes is 55%.
Capital incomes are taxed proportionally at 30% (marginal rate equals average rate).

### Taxes on Labor Income

#### Payroll Taxes (Payroll)

\phantomsection
[\[sec:Payroll\]]{#sec:Payroll label="sec:Payroll"}
In Germany, and many other countries, social contributions for old age, health, unemployment and long term care insurance are implemented as payroll taxes.
Payroll taxes are paid on labor income.
Whether they are implemented as withholding taxes (the employer withholds and transfers the tax) or paid out of the employees funds is of no significance here:
it does not matter for (page ).

##### Social Insurance Contributions

\phantomsection
[\[sec:SIC\]]{#sec:SIC label="sec:SIC"}
are capped [payroll]{acronym-label="payroll" acronym-form="singular+short"}, actually.
Despite this terminological confusion and their administration in semi-independent public agencies, it is important to note that social contributions are government revenue, irrespective of their quasi-fiscal status.
Social contributions are proper pages
To the extent that government adopts universal provision of health care, unemployment insurance and long term care as allocative goals, compulsory contributions to these services are .
To the extent that government finances old-age pensions out of current incomes, such PAYGO contributions are intertemporally and intergenerationally redistributive taxes.
[^3]
To the extent that private markets for health care, unemployment and long term care insurance are plagued by lemons markets [@Akerlof-1970-aa], respective contributions serve to (page ) and are proper revenue-generating taxes.
Additionally, universal health care provides provision against epidemics (think vaccinations) and unemployment insurance serves as an automatic stabilizer to smooth out economic growth.

Social insurance contributions are presented here for the sake of completion and clarification.
They are, when typically implemented as payroll taxes, a variation of a [2-pit]{acronym-label="2-pit" acronym-form="singular+short"}.

Rates for social insurance contributions are usually proportional.
In the EU, they vary from 20% in Denmark to 32% in Germany and 50% in France (Statistisches Bundesamt Deutschland 2007).
In Germany, contributions are capped above a certain income threshold, above which additional income is not taxed.


## Taxes on Consumption

### Prepaid Consumption Taxes

#### Value Added Tax (VAT)

\phantomsection
[\[sec:VAT\]]{#sec:VAT label="sec:VAT"}
The [vat]{acronym-label="vat" acronym-form="singular+short"} is best understood as an elegant advancement of a retail sales tax.
A retail sales tax charges sellers a fixed percentage of the sales price on goods for which the (corporate or private) buyer is the end user.
Because under a sales tax, the tax on any single taxable transaction is very high, incentives to evade the tax and to smuggle goods are great.
What is more, the state looses *all* tax revenue on a given good when evasion occurs.

The VAT was developed to address this problem.
Instead of charging sellers only at the end of a production chain (before the good is consumed), sellers are charged a percentage of their sales prices on *all* goods, including investment and intermediary goods.
Sellers invoice the tax to buyers.
Buyers are then eligible for refunds on their VAT receipts:
they can deduct all of *their* sales.
Instead of kicking in only at the last transaction before consumption, the VAT charges every transaction according to the value added at the respective stage of production.
It is handed down the economic cycle to whoever ultimately consumes a good.

The tax burden on any *single* transaction is much smaller:
value added instead of entire sales price are taxed.
Incentives to evade the tax on any single transaction are thereby greatly reduced.
[^4]

VATs are very common in the EU, standard rates differ from 15% (Luxembourg, Cyprus) to 25% (Denmark), with the majority of countries above 20%.
Reduced rates are frequently implemented for foodstuffs and other basic needs.

<!-- %The value-add tax (VAT) is a straightforward indirect tax.
%It has a relatively immobile base (consumption of everyone), supposedly robust revenues, and is relatively incentive-neutral.
	%The VAT is, however, regressive (poorer people spend more of their income generating capacity on consumption).
%Like payroll taxes, the VAT raises effective price floors of labor when socially acceptable minima are present, and can thereby contribute to structural unemployment.It emerges from this simplified overview that taxes with progressive schedules also tend to have relative mobile bases#.
%If mobile tax bases erode relatively more because of tax competition, so will progressive schedules. -->

##### Graduated VAT

### Postpaid Consumption Taxes

#### Progressive Consumption Tax (PCT)

\phantomsection
[\[sec:PCT\]]{#sec:PCT label="sec:PCT"}
The [pct]{acronym-label="pct" acronym-form="singular+short"} is applied to the total consumption of natural persons.
Crucially, it is *postpaid* and *cash-flow based*.

Postpaid.

:   It is crucial to understand that the PCT is *not* a VAT or sales tax of any kind with progressive rates (say, a higher rate for luxury goods).
    The PCT is not *prepaid* on the price of individual *consumer goods*, but *postpaid* on the sum of individual *consumer accounts*.
    It matters not what you consume, but how much and of what value.
    The PCT suggested here is called postpaid because the progressive rate is known and deducted only once all consumption in a given period is completed.

Cash-Flow-Based.

:   It would be impractical to collect and add up all consumption receipts.
    People usually consume very many, different things of relatively small value.
    Instead, the PCT relies on the @Haig1921-@Simons1938 definition of income in ([-@Haig1921], [-@Simons1938] respectively).
    $$\label{eq:HaigSimons}
            \text{Income}=\text{Consumption}+\Delta\text{Wealth}$$

    A trivial transformation yields a practical definition of consumption:

    $$\label{eq:HaigSimonsPCT}
            \text{Consumption}=\text{Income}-(\text{Savings}-\text{Dissavings})$$

    Consumption is simply defined as that part of income which is not saved.
    You can, after all, only either save or spend.
    People create much fewer savings receipts than consumption receipts:
    while you may have hundreds of grocery receipts, you will have only one savings account and maybe a few other financial instruments.
    In addition, transactions to save money are more thoroughly formalized:
    the bank, by necessity, keeps good track of your accounts.

Consumption out of wealth is included as a dissaving.
Consumption out of loans is also treated as a dissaving.
Payments on interest and principal are treated as accretions to wealth (saving).
They are fully deductible.

To measure the wealth of individuals, the taxman would have to list the assets and liabilities of each person.
Such *balance sheet* accounting would be very costly administratively and require undesirable evaluation of (page ).

The PCT achieves its objective through a simple *cash flow* accounting of individuals.
Instead of evaluating all assets and liabilities, the taxman merely records all cash transactions.
A dissaving is recorded when, for instance, a mutual fund is sold and its cash value wired to the checking account.
Savings are recorded when payments are made from that checking account to a qualified investment (say, a life insurance).
Incomes from labor or capital are recorded as the salary or interest are deposited on the checking account.
Consumption is recorded as cash is withdrawn or wired to a seller.

The cash flow variant of the PCT rests on the assumption that all assets are transformed into cash before they are consumed.
[^5]

Cash flow accounting is much simpler than balance sheet accounting.
In a modern economy, most cash flows are already recorded by individuals and their financial service institutions.
The taxman just needs to look into these records.
Moreover, cash flows are by definition liquid:
they constitute the equilibrium prices.
The taxman does not need to evaluate anything.

##### Illustration

I enlist @Aesop's fabled Ant and Grasshopper (c.a.
564 b.c.) to explain an example.
[^6]
summarizes incomes, savings and consumption for three archetypical taxpayers.

##### Grasshopper

earns 30,000 each year, of which he spends everything.
He had no savings at the beginning of the year, and none at the end, when winter, or rather, the taxman comes.
With no savings, all of his income is taxable at a progressive rate, of say, 10%.
Grasshopper owes 3,000 to the state.

##### Thrifty Ant,

who also earns 30,000 per year, saves 10,000.
Her taxable consumption is 20,000 at, for example, 5%, owing 1,000 to the taxman.
Ant will at some point in the future consume what she has saved, but possibly spread more evenly (thereby avoiding sharply progressive rates) and while earning an interest on her savings.
This interest is *not* income taxed, as mandated by the (page ).

##### Big Spender Lion.

Let's introduce a third beast, the Lion, who powerful as he is, earns a great income of 600,000.
He also consumes a lot (he is a predator, after all), say 300,000.
Come winter the (brave) taxman will collect a 33% due on consumption, that is 100,000.
Note, that although Lion consumes *relatively less* (50%) than Grashopper (100%), he has to pay *relatively more* taxes (33% as compared to 10%), because, in absolute terms, he is encouraged to spend less and save more, given his superior income-generating abilities.
Also note that the tax liability does not depend on the source of income.
It does not matter whether the Lion earns much because he is such a diligent hunter (labor income), or (as it happens to be), whether it is because he sits comfortably on the top of the food chain and actually sleeps most of the day (capital income).

<!-- pun: it really is a fabled tax -->

Table: Progressive Consumption Taxation of Thrifty Ant, Big Spender Grasshopper and Big Earner/Spender Lion.

|  | Ant | Grasshopper | Lion |
|-------------|--------|-------------|---------|
| Income | 30.000 | 30.000 | 600.000 |
| Saving | 10.000 | 0 | 300.000 |
| Consumption | 20.000 | 30.000 | 300.000 |
| Tax Rate | 5% | 10% | 33% |
| Tax | 1.000 | 3.000 | 100.000 |

<!-- expenditure tax is the evil twins
\paragraph{Expenditure Tax (ET)}
	\phantomsection
	\label{sec:ET}
%must write this, it's simple
%I also think this is the evil twin!
%it is NOT cash-flow based!

%random ideas, edits, additions for thesis
%[ ] to bash FairTax.org (evil twins):
%http://www.taxpolicycenter.org/publications/urlprint.cfm?ID=901139
	%[ ] good source (popular) for the positional consumption race and its efficiency losses:
%http://prospect.org/cs/articles?article=postconsumer-prosperity#
	%[ ] really bash the Bradford X-Tax for good:
%It has limited progression (0-35% on the labor component, 25% on the non-labor VAT).
%This isn't exactly very good progression.
%Also, it falls only on labor.
%It's not a progressive consumption tax.
%It's a VAT with some poor relief. -->


## Taxes on Wealth

### Taxes on Unimproved Nature

#### Land Value Tax (LVT)

<!-- %get quote

% via wikipedia on LVT, here's a reason for why govntm evaluation is always bad: Austrian School economist Murray Rothbard later raised similar concerns, stating that no government can fairly assess value, which can only be determined by a free market.[20]
	%Rothbard, Murray.
%"The Single Tax: Economic and Moral Implications and A Reply to Georgist Criticisms".
%The Mises Institute.
%Retrieved 2009-02-13. -->

<!-- notice in all of this that the flight to illiquidy and the problems that arise for the state are not, in fact, unique to the lvt.
the pit also has that -->


<!-- %note that the LVT may also act as an automatic stabilizer, at least of real estate, because, given the right function, it might curb real estate bubbles.
%problem:
%how do we KNOW the unimproved value of land?!? -->

<!-- \subparagraph{Other Natural Resources}
%\ldots
%but NOT CO2E, it does not replace that, it only deals with the inequality AND a little bit the commons problem of resources
%when applied to other material resources, too, the LVT becomes a, or might replace severance taxes.

%also compare this to auctioning off.
%The same could be done for land, except that would require land reform, so maybe the LVT is the smarter choice.

%notice that this unlikely to hit farmers (as they might expect) and other marginal uses of land.

%also notice the foundational beauty of this (smith mentions it):
%it's about taxing that part of your property that is valuable because of the stuff that other people around it (and public infrastructure) are doing.
%It's so beautiful. -->

<!-- TODO is this actually a tax on a factor, rather than on wealth? -->

<!-- %note about the LVT:
%it HAS limited income;
%it cannot be taxed beyond rental value people would simply stop using land at all (because the supply curve is completely inelastic).
	%so you might need other taxes, too.
	%it's not clear how much value add comes from this one factor

%include the LVT in the circular flow diagram, together with other rents

%note that the LVT requires some difficult evaluations;
%it may cause some of the same illiqudity and other market reactions that we already now.
	%notably, market evaluations for untraded land (for example, in the insurance business and/or for mortgages) will not help much, because these are in turn, market interactions that may be distorted, or equivalently, cause their own DWLs.
	%modern algorithms and data mining might help a little, in so far that land is comparable, which seems possible (it doesn't have sharp gradients).
	%alternatively, auctioning off land periodically might be the better solution to this problem -- it would have the same distributive effects (NO land rent), but may be politically difficult.
		%unclear if you can get the same steering effects on land concentration

%normative attractiveness:
%no one actually created land, it is but a by-product of capturing, or at one point, having captured, parts of land.

%there is a problem of transitional justice;
%people who have now invested in land, as opposed to other assets, may be at a disadvantage (or will they?)
	%if you have land, you're taxed on the unimproved value, if the rental value is lower, you don't use the land, so land use get's smaller, some land is abandoned (but it'll stop generating revenue at that point)
	%solow also says this:
%‘Theoretical’’ is an essential qualifier here, because consensus evaporates once the papers turn to real-world implementation issues.
%One such issue is emphasized by discussant Robert Solow (p.
%278):
%high tax rates on land values would mean departing dramatically from existing tax policy, with correspondingly dramatic capital losses:
%‘‘Expropriating land values today would have no semblance of fairness.
%Suppose I have just paid through the nose for a prime beach lot.
%I have no unearned increment from the land.
%If you now tax away the rent, you are in effect taxing away the savings that enabled me to buy it.
%The original appropriator of the land is long gone.’’ /this is via \cite{Tomlinson2001}


%— Adam Smith , The Wealth of Nations, Book V, Chapter 2, Article I:
%Taxes upon the Rent of Houses:
	%Ground-rents are a still more proper subject of taxation than the rent of houses.
%A tax upon ground-rents would not raise the rents of houses.
%It would fall altogether upon the owner of the ground-rent, who acts always as a monopolist, and exacts the greatest rent which can be got for the use of his ground.
%More or less can be got for it according as the competitors happen to be richer or poorer, or can afford to gratify their fancy for a particular spot of ground at a greater or smaller expense.
%In every country the greatest number of rich competitors is in the capital, and it is there accordingly that the highest ground-rents are always to be found.
%As the wealth of those competitors would in no respect be increased by a tax upon ground-rents, they would not probably be disposed to pay more for the use of the ground.
%Whether the tax was to be advanced by the inhabitant, or by the owner of the ground, would be of little importance.
%The more the inhabitant was obliged to pay for the tax, the less he would incline to pay for the ground;
%so that the final payment of the tax would fall altogether upon the owner of the ground-rent.

%note neutrality of the tax

%Paul Samuelson:
%Paul Samuelson strongly supported a land value tax.
%"Our ideal society finds it essential to put a rent on land as a way of maximizing the total consumption available to the society.
%\ldotsPure land rent is in the nature of a 'surplus' which can be taxed heavily without distorting production incentives or efficiency.
%A land value tax can be called 'the useful tax on measured land surplus'." (wikipedia)

%Friedman from Wikipedia:
%Milton Friedman stated:
%"There's a sense in which all taxes are antagonistic to free enterprise -- and yet we need taxes.
%\ldotsSo the question is, which are the least bad taxes?
%In my opinion the least bad tax is the property tax on the unimproved value of land, the Henry George argument of many, many years ago."

%Krugman from Wikipedia:
%Paul Krugman agrees that a land value tax is efficient, however he disputes whether it should be considered a single tax, as he believes it would not be enough alone, excluding taxes on natural resource rents and other Georgistesque taxes, to fund a welfare state.
%"Believe it or not, urban economics models actually do suggest that Georgist taxation would be the right approach at least to finance city growth.
%But I would just say:
%I don’t think you can raise nearly enough money to run a modern welfare state by taxing land [only].” http://www.psmag.com/politics/this-land-is-your-land-3392/

%The Nobelist Joseph Stiglitz writes "Not only was Henry George correct that a tax on land is non-distortionary, but in an equilibrium society \ldots
%tax on land raises just enough revenue to finance the (optimally chosen) level of government expenditure.

%\cite{Tomlinson2001}
	%Book reviews / Regional Science and Urban Economics 31 ( 2001 ) 601 – 641 635
 %properties that sell are developed properties.
%Reschovsky’s concluding comment (p.
%234) underscores the issue’s significance:
%‘‘In my view, the most important unresolved issue concerning the adoption of a land value tax by a city or state government is the ability of that city or state to provide high-quality land value assessments that will be widely accepted by taxpayers, and will reflect as closely as possible the ‘highest and best use’ of each parcel of land.
%Experts clearly disagree about the feasibility of assessing land values.
%One way to resolve this issue would be for at least one state to attempt to implement a serious state-wide assessment of land values.
%This in turn would allow for full evaluation of the land value tax in a state or local government setting.’ -->


##### Pigouvian Element.

##### Other Natural Resources

### Taxes on Property

#### Property Tax

\phantomsection
[\[sec:PT\]]{#sec:PT label="sec:PT"}

#### Stamp Duty

\phantomsection
[\[sec:SD\]]{#sec:SD label="sec:SD"}

### Taxes on Net Worth

#### Wealth Tax (WT)

\phantomsection
[\[sec:WT\]]{#sec:WT label="sec:WT"}
The Wealth Tax is a tax on the net wealth ($assets$ $-$ $liabilities$) of natural persons.
It requires a balance sheet account for all tax liable individuals, including some method of valuation for .
Wealth Taxes are typically progressive in schedule.
They are levied only in a few OECD countries, including France (up to 1.8% p.a.) and Switzerland (up to 1.5% p.a.).


<!-- %Include the estate and gift taxes as a subclass of taxes on net worth, because these are just triggered at a particular point in time (death).
%They are, crucial and by definition, not income taxes because they are not LINKED TO ANY EXCHANGE, for if they were, they would be incomes.
%Also note this in the definition of incomes:
%they are exchange incomes, not gifts.
	%or are they?
%maybe I need to include gift and estate taxes somewhere \ldots

%mention subsets Property Tax \gls{pt} and Stamp Duty \gls{wt} here.
%Also refer to \gls{lvt} -->

## Non-Taxes

#### Financial Transaction Tax (FTT)

\phantomsection
[\[sec:FTT\]]{#sec:FTT label="sec:FTT"}

#### ecotax

\phantomsection
[\[sec:Ecotax\]]{#sec:Ecotax label="sec:Ecotax"}

#### Negative Income Tax (NIT)

\phantomsection
[\[sec:NIT\]]{#sec:NIT label="sec:NIT"}
The Negative Income Tax (NIT) is a subsidy for low wage earners, not a tax.
It does not raise, but spends revenue.
It is included here because of its broad redistributive impact and its technical implementation as a "tax".

The NIT was suggested by Milton [@Friedman1962] as an elegant replacement for minimum wage legislation and (page ) social security transfers.
Under the NIT, workers would receive progressive transfer payments for hourly market wages below the socially acceptable minimum.
However, in contrast to current income supplements, real market wage increases are not entirely eaten up by transfer cuts:
at any given level of income, earning more on the market will leave you with more net in the bank.
For example, under a minimum acceptable hourly income of €7.50 (current minimum wage proposal in Germany), moving from a €2.00 market price to a €4.00 market price job could increase your post-tax income from €7.50 (transfer €5.50) to €8.50 (transfer €4.50), always maintaining your incentives to earn more on the market.
This may also help to counteract rent-seeking exploitation by low-paying firms.

<!-- %tax allows only very limited choice: income, consumption or assets; a couple of schedules, plus some pigouvian taxation.
% the CIT, notably, is just a special way to raise the PIT.
%Otherwise, only natural persons.
%Tax demands these choices.
%Also, these choices \emph{are} as I explain in the below, political, so they must be made legitimately, and we may not be able to simply outsource them to elites.

%there remain problems: you can't just go about this as if it wwere not controversial; it is controversially maongst experts, but more importantly, controversial whether experts have in fact authority and the right context.
%It can't just be an experiment, or a treatment intervention where ordinary citizens must necessarily become more like experts, and if they are not, then the teaching has failed.
%It must be possible for people to disagree with the abstractions they ar epresented with, see the criticism of it.

%tax is very technocratic, simply because the instition is like that.
%this will have to be qualitative

%\gls{oecd}-world (\autoref{chap:3-crises}

%Tax offers/demands very structured choices: there are essentially only 4x3 broad tax types (see tax table in drafts).
%Different from, for example, a deliberation on “racial tensions”, deliberating tax choice is more close-ended.
%Tax expertise is easily politicized, because:
%Tax cannot be reduced to an empirical question, both because inframarginal data is not available, and because macroeconomics is incompletely understood.
%Tax cannot be reduced to a consequentialist inquiry, because people (may) care about other normative claims, too (for example, fairness).

%Tax cannot be easily (if at all) dumbed down to subsets of tax choice (for example, VAT vs PIT), or subsets of abstractions (for example, only “bastard keynesianism”) for two reasons:
    %Any such reduction would violate the spirit of deliberation; citizens could not set their own agenda.
    %Any such reduction may well fail to elucidate my hypothesized misunderstandings: I imagine “understanding tax” as a bucket, which, if leaky will drain to the lowest level.
%For example, if deliberators would discuss most aspects of taxation, but skip over the limits (!) of price controls, they may well opt for price controls in lieu of, or in addition to taxation -->


<!-- A Numerical Example to Show the Equivalence of VAT and Payroll

2 Periods
EUR 100 Income
20% tax
10% interest
Payroll / Social Contributions
EUR 100 Gross * 0.8 Payroll Tax = EUR 80 Net
Period
Consumption
Saving
p1
EUR 40
EUR 40
p2
EUR 44 (from Saving * 1.1)
0
Aggregate Consumption / Utility = EUR 84


VAT
EUR 100 Gross = EUR 100 Net
Period
Consumption
Saving
p1
EUR 50 * 0.8 = EUR 40
EUR 50
p2
(EUR 50 from Saving * 1.1) * 0.8 = EUR 44
0 -->

<!-- if you need stuff on positional races, go here, otherwise KILL IT
%garrard 2012
	% briefly reference Rousseau "obsessive being-for-others" with whom "one is forced to compare onself at each instant".
	% 382: ``The possession of positional goods has also been associated with measurable levels of increased well-being, while their absence has been linked with increased stress, status anxiety and other adverse psychological and physical effects such as depression, heart disease and reduced life expectancy''.
	%382``There is some evidence of a connection between blood concentrations of the neurotransmitter serotonin—the so-called ‘happiness hormone’—and dominance. Unusually high levels of serotonin have been found in officers of college fraternities, athletic team captains and officers and crew members on an extended sailing voyage (Frank 1985: 23–8). Richard Wilkinson has linked being in a subordinate position with heightened levels of stress and depressed levels of serotonin (Wilkinson 1996). Increased levels of the central stress hormone cortisol, which can be measured in blood and saliva, have been found in individuals whose self-esteem and social status are threatened, and stress has been positively linked to The status of happiness 383 poor health and increased obesity. Low or declining social status has also been associated in some studies with poor cardiovascular health (Wilkinson and Pickett 2009: 38, 191; Marmot 2004).
	%383: Rousseau may be right, but it might be nature already: While there is some evidence that he was more or less right about this, it seems as though our preoccupation with status and relative position is rooted in our natures which, according to evolutionary psychology, are ‘adaptive responses shaped by man’s biological nature and situation on earth’ (Hirschleifer 1978: 321).
	%. ‘[T]he farther an individual fell in his local pecking order,’ according to economist Robert Frank, ‘the more serious were the threats to his survival,’ which typically provoked feelings of stress and anxiety affecting levels of testosterone and serotonin, as we have already seen (Frank 1999: 136). In such a setting, ‘low social status is an evolutionary dead end,’ to put it bluntly (Wilkinson and Pickett 2009: 204). For
	%``What mattered for survival in this environment was one’s position relative to local rivals with whom individuals and groups were in direct, immediate competition for food and sex, ‘whereas comparisons with others who are distant in time and space are typically irrelevant’, from an evolutionary perspective (Frank 2007: 57). One of the central findings of Robert Frank is that most people today are relatively indifferent to the wealth and status of people far removed from them, whereas they ‘care deeply about where they stand in their various local hierarchies’ (Frank 1985: 107). Hence,''
	%``For example, the voluntary simplicity movement seeks to overthrow ‘the god of positional consumption’ (Schor 1999: 61) in the name of reduced consumption, anti- materialism and sustainable development. A policy of deliberate ‘downshifting’ typically involves working less, earning less and consuming less so that there is more time to better enable people to pursue other goods. Such a lifestyle would be materially poorer than now but richer in non-material, non-positional goods and therefore happier. To the extent that it is possible to reduce the speed of the consumption treadmill so that less time and fewer resources are expended on the joyless pursuit of positional goods and status, we may be able to devote ourselves to more intrinsically satisfying activities and forms of consumption that actually improve our quality of life, such as higher air quality, more urban parkland, cleaner drinker water, reducing violent crime (Frank 1999: 11).''
		%comment on this kind of anti-growth stuff; it might be anti-growth, but anti-spending might be even better. -->

<!-- ## Seidman

2 USA tax is the only that doesn't discourage either savings or is regressive!
8: education should be deductible
old age equity issue? - think this through!
coment on the need for an asset tax based on net workf effects, think about collateral.
The history
Kaldo 1955: an Expenditure Tax
Irving Fisher did it before
even Hobbes, Mills mention it, just didn't think it was technically feasible
cite the history (14)
Fisher 1942: 14: wait a minute, all you need is to deduct! -->

<!-- ## a desire that others not understanding
We sometimes hear it is only a "matter of timing" when we pay the income tax. This , McLure 1988 as cited in Seidman 125 writes, is either because  "Such a statement reveals a basic failure to understand - or a desire that others not understand - the nature of income taxation and tax avoidance: (...) If income tax can be postponed (...), interest (or other capital income) can be earned on a tax deferred basis in the meantime". in other words: compound interest, is ignored. -->


<!-- ## Bank 2004

2: talks about the ideal combination that McCaffery's plan is: progressive appeals to liberals, exemption for avings and investment appeals to conservatives
3: skepticism that this ever will materialize. rather: the consumption tax supporters want a flat VAT, the progressive guys want an income tax
2: was considered post WW1 (graduated spendings tax), Mill's proposal again in1942 by Treasury Secretary Henry Morgenthau (graduated surtax on spending), and lastly in 1995 by Sen Sam Nunn, Pete Domenici, Bob Kerrey Unlimited Savings Allowance (USA Tax).
4: numbers for the PCT can be found here (US example, progression up to 50%).
4: Haig-Simons definition of income: I=C+A
debt repayment would be deducted from income (it's a form of investment), debt spending however would be consumption
5: estate and gift tax, according to McCaffery can be safely abolished. Dead people don't spend. Their heirs pay when they spend.
7: two ideas were present from the very beginning: place the burden on the wasteful spender, never the investor. Also, make it more equitable, yet efficient.
10: the progressives were against it because it didn't tax firms, nor property as such
10: the regressives were against it, well, because it was progressive, they wanted flat ax, already back in 1921.
10: Representative Stevenson asked: "[put] into effect the proposition according to what a man spends and graduate it according as he spends it, and the United States Government will have to have an auditor behind every man in the country who has any money to spend. How would you ever carry it out?"
15: "Under the progressive consumption tax, Hazelett explained, "we define income as what it really is. there is no economic income but the living standard of the taxpayer".
this point is key: things OUT to be about consumption!
18, 19: the USA tax had to problems: it didn't include borrowing as income and it didn't terminate the estate and gift taxes (which are transfers, not new consumption)
19: Both in 1942 and in 1995 the PCT failed because of its complexities: the more complexity you introduce, the more devils, the more rejection. With that rise chances for evasion: flat and sales tax proponents are disenchanted
Think about the problems of old savings: we have to know about these, do a full cash flow status of people.
as cited on  22 As McCaffery writes, "I will not add fuel to think tank fires. Complexity can wait. The devil may indeed dwell in the details, but we first need to find an angel or two in the abstractions that govern tax."
idea: the PCT is between a rock and a hard place in terms of how people like it in the political spectrum! But that doesn't need to be so. there is nothing inherently good about the income tax.
actually, the PCT provides a possibility to fight evasion: you can force people to prove where they have invested and treat it as consumption, otherwise. The problem, of course,  need to think this through -->


<!-- JIPEEEH I got it. Cafferty 2005: 918 says. Corporate income tax has two problems: it depends on incidence (economists disagree), and even if it does tax capital, it does so randomly, not progressively. All capital owners are taxed, not just the progressive ones. -->

<!-- die linke actually writes that they think the fta tax would burden factors
26: Mit einer Finanztransaktionsteuer wollen wir die Spekulationen auf den Finanzmärk- ten eindämmen und die Verursacherinnen und Verursacher der Krise an deren Kosten beteiligen. -->

<!-- ## Graetz 1979?

- Graetz on progressive consumption tax 1979
	- eliminates the problem of double taxing of saving
	- India and Sri Lanka have tried it, and failed. But it should be easier than income tax to administer
	- problem: "the notion of a sharp division between pleasure-seeking and profit-seeking is alien to human psychology and essentially unrealistic" (chirelstein as cited in graetz 1979 1586). And yet, we deal with the same problem in income taxation. And remember how much good this tax could still do, how it could redefine the very boundary of what is pleasure and what profit (thinkg conspicuous consumption). Also, we have this thing called depreciation which takes care of it. -->

  #### It's Win-Win-Win-Win: No DWL Or No DWL & Less Waste Or Diminishing Marginal Utility.

  \phantomsection
  [\[sec:WinWin\]]{#sec:WinWin label="sec:WinWin"}
  The DWL case for the PCT is not clear, but either way, it's good.

  Just in *which* way the PCT is good depends on the in excessive and positional consumption.
  
  <!-- %let's be honest about this, the DWL case of a PCT is not so clear-cut.
  %It might still disincentivize people, because at the end of the day, they get to enjoy less, although, only to the extent that there is actually no race.
  %Also, note, that the PCT still does not tax compound interest.
  %from \cite{ZimmFina2009}
  	%   * Read p.
  % 138-159
  	%   * feature the Economic cycle page 139 in my thesis, argue why it makes more sense to tax consumption
  	%   * 156:
  %"Überschreitet die [Einkommens]Besteuerung jedoch ein gewisses Ausmaß, so ist zu erwarten, dass sich negative Auswirkungen auf Investitions- und Arbeitsbereitschaft ergeben und damit das Wachstum beeinträchtig wird.
  %Dagegen könnte eingewandt werden, dass ein höherer Anteil der Einkommenssteuer bei gleichem Gesamtsteueraufkommen die Gesamtbelastung nicht verändert, sonder nur wahrnehmbarer macht, weil die Einkommenssteuer für die Besteuerten merklicher ist als die Verbrauchssteuer.
  %Für die Wirkung auf Investition und Arbeitsbereitschaft ist aber wahrscheinlich nicht die tatsächliche Belastung eines privaten Haushalts oder Unternehmens entscheidend, sondern nur der Teil der Belastung, der wahrgenommen wird und in die ökonomischen Entscheidungen eingeht."
  	%      * Bingo.
  %This is the argument for the PCT vs PIT in terms of incentives.

  %\cite{MusgPubl1976}
  	%   * the PCT "is still a new and exciting idea" (315)
  	%   * "In some respects, the approach would be simpler than under the income tax.
  %The dilemma of how to deal with unrealized capital gains would disappear.
  %If assets were sold, the proceeds would enter into the tax base unless offset by purchases of other assets or an increase in balances.
  %Also, there would be no need to determine corporate profits.
  %Dividends would appear as receipts and unrealized capital gains obtained through retention of profits or otherwise would be irrelevant until realization occurred and the proceeds were channeled into consumption.
  %The difficult problem of depreciation accounting, similarly, would disappear." (316)
  	   %   * bingo, bingo, bingo
  	%   * "(\ldots) distributional objectives might be achieved with less disincentive effects" (317)
  	%   * Contras, needed (316)
  	%      * complete recording of cash balances (OK)
  	%      * inclusion of imputed consumption (homegrown foods, housing) (OK)
  	%      * Borrowing must be acccounted for (indeed, OK)
  	%         * "Where the lender was an individual, also subject to tax, he would see to it that this was done so as to reduce his own base;
  %but where lending was by institutions not subject to the expenditure tax, lenders would have to be required to file information returns on loans made" (316)
  	%         * (OK, this can be done by simply legislating that loans without such reporting are gifts.
  	%      * consumer durables (OK)
  	%      * "The expense-account problem, difficult enough under the income tax, would assume large proportions" (fringe benefits, acknowlegded)
  	%      * education "would pose a similar problem, as they again involve both consumption and investment aspects" (OK)
  	%   * "on balance, the administrative diffculties for an expenditure tax may well equal or outweigh those of an income tax.
  %For higher-income individuals at least, more or less complete balance-sheet accounting would be needed.
  %Yet, this is precisely the income range over which effective administration would matter most.
  %At low levels of income, there is relatively little difference between an income and an expenditure tax approach.
  %The distinctuon becomes of major importance only as we move up the income scale and the savings rate rises" (317)
  	%      * yes, yes, yes, but I don't agree that you need balance-sheet accounting.
  %Cash-flow suffices.
  %%or do you?
  %Actually you need balance-sheet accounting either way for personal progression. -->

  Without further empirical research, they cannot be known.
  The PCT will have *very* high marginal rates, possibly well above 100 %.
  Because universal, stark price hikes in the markets for excessive consumption have never occurred, we have no systematic observations regarding the responsiveness of excessive buyers to such price changes.

  So what are the alternative outcomes?

  ##### What If: People Still Consume Excessively.

  If people *do not* respond to the post-tax price hike in excessive consumption, the PCT will tax an .
  The DWL will be , as per desiderata [\[des:tax-inelastic\]](#des:tax-inelastic){reference-type="ref" reference="des:tax-inelastic"} and [\[des:minimal-DWL\]](#des:minimal-DWL){reference-type="ref" reference="des:minimal-DWL"}.
  Most of what consumers no longer enjoy in excessive consumption will be recouped as government revenue, as illustrated in .

  Producers will be perfectly elastic in their supply.
  At least in the long run,
  [^14]
  all producers can shift their production to less expensive consumer goods, or, as described later, to investment goods.
  The burden of the PCT will fall exclusively the who ultimately consume goods, as mandated in desideratum [\[des:personal-taxation\]](#des:personal-taxation){reference-type="ref" reference="des:personal-taxation"}.

  ##### What If: People Consume Less (Expensive) Things.

  If people *do* respond to the post-tax price hike in excessive consumption, the PCT gains a Pigouvian component, but one that works.
  When people consume excessively, they pay for the negative externality of defection in the (page ).
  Recall that when the Joneses buy a BMW (defect) instead of a VW (cooperation), the utility enjoyed by the VW-owning Does decreases:
  they cannot stand having the cheaper car.
  Under the PCT, the Joneses pay (dearly) for showing off their BMW.
  If their demand for BMWs is price elastic, they may buy the same VW as the Does.

  Also recall that the level of cooperation in a multiplayer Prisoner's Dilemma is a (page ).
  Contributing to cooperative behavior creates a benefit to other players from which they cannot be *excluded*.
  Establishing cooperation is, however, *rival*:
  if no one, or too few people cooperate, the benefits of cooperation will not materialize.
  Buy buying a VW, the Does contribute to a common-good-like lower level of automobile consumption, from which everyone else can invariably (relatively) benefit.
  The Joneses can exploit the thriftiness of the Does by buying a BMW (greater relative utility), or they can partake in the Does thriftiness by buying a cheaper VW (same relative utility, but lower absolute utility), without being looked-down upon by a BMW-owning neighbor.
  Either way, the Does cannot prevent the Joneses from benefiting (non-exclusion).
  The Joneses buying of a VW is, however rival.
  If they end up being the only family on the street that buys the cheaper VW, their triftinness will be inconsequential for everyone else.

  Common Goods are best financed out of Pigouvian taxes.
  The PCT is that Pigouvian tax of excessive, positional consumption.
  It falls on exactly that behavior (excessive consumption) at exactly that price (marginal rate!) which it is meant to discourage.
  If rates are sufficiently high and progressive, the PCT can effectively curb .
  At minimum, it can lower the level of material waste at which positional consumption occurs.

  ##### What If: People Don't Mind Buying Less (Expensive) Things.

  A Pigouvian tax, by definition, has a DWL.
  The DWL of a Pigouvian tax is the very consumer and producer surplus that should never have been realized, because of the social costs hidden to them.

  The definition of a DWL assumes that the utility of consumers is accurately measured in their willingness to pay.
  Utility and nominal demand curve are the same.
  (page )
  suggest that people derive utility not from absolute, but relative consumption or status.
  People want to have more, or at least not less things and status than other people.

  If excessive consumption occurs for positional gain, there *can* be no DWL when that consumption is curtailed for everyone.
  No one will be relatively worse off, only less relatively different.
  If anything, a more compressed stratification in the material signs of affluence and status will make most of us happier.

  ##### What If: People Really Care About Luxury.

  People enjoy having many, and many expensive things not *only* because they want more than their neighbor.
  Driving that BMW on the autobahn may be aesthetically pleasing and functionally faster in absolute terms.
  [^15]

  Let's assume for a minute that there really is an absolute, *sheer driving pleasure*
  [^16]
  in driving an expensive car.
  Even if there is absolute utility, it is likely to be of marginally decreasing return.
  Upgrading from a VW to a BMW will probably bestow more utility on someone than upgrading from a BMW to a Bentley.
  By taxing big spenders more, the PCT accounts for in excessive consumption.
  Even in a world of *sheer driving pleasure*, when more people get to upgrade from VW to BMW and fewer from BMW to Bentley, aggregate autophile utility will be maximized.

  #### Sky-High Progression.

  The PCT can be arbitrarily progressive.
  For very excessive consumers, rates can be as high as several hundred percent:
  literally, the sky is the limit.
  Because the PCT falls on consumption, and not on incomes, incentives or entrepreneurship will not be dramatically curtailed.

  The ultimate reason for *homo economicus* to work hard and invest wisely is superior consumption.
  At first sight, depressed consumption (at higher prices) may appear to reduce incentives.
  Consider the trade-offs for *homo economicus* under the PCT:
  She can either work an extra hour, or not.
  Because she is already very diligent, and likes to *work hard / party (consume) hard*, any additionally enabled unit of consumption will be taxed at a fairly high rate.
  At *any* rate of consumption taxation, she will still be better off if she works the extra hour.

  At the other end of the progressive schedule, rates can be very low or at zero for people who consume very little.
  Aside from equity, this also serves to labor as per desideratum [\[des:low-price-floor\]](#des:low-price-floor){reference-type="ref" reference="des:low-price-floor"}.
  If the working poor or structurally unemployed pay a zero tax rate on their necessarily minimal consumption, their living standards increase and their reservation wage vis-a-vis the socially acceptable minimum living standard drops.

  #### The PCT Smoothes Consumption.

  Under progressive tax rates on consumption, people are punished for spikes in their consumption.
  To have the lowest possible PCT rate for a given level of lifetime consumption, you have to spread out the shopping sprees as evenly as possible.
  
  <!-- %frank seems to note somewhere (source unknown, this is from economist web):
  	% that the PCT can be counter-cyclical ``If a progressive consumption tax were phased in gradually, its main effect would be to shift spending from consumption to investment, causing productivity and incomes to rise faster.
  %Should a recession occur, a temporary cut in consumption taxes would provide a much more powerful stimulus than the traditional temporary cut in income taxes.''

  %note that stabilization is always a second best, it'd be nicer if we could fight the cause of busts and booms, but, considering for a moment that we may be unable to do that, such dampers may be a good idea.
  %Also, note that if no boom/bust cycle sets in the PCT does not hurt you much. -->

  In a bust or boom, the PCT serves as an automatic stabilizer.
  Without legislative intervention, people are always incentivized to smooth out their consumption.

  The PCT can also serve as a powerful discretionary stabilizer.
  In a bust, legislatures can opt to lower the entire PCT schedule
  [^17]
  .
  For the duration of the bust, people have a greater incentive to consume, knowing that higher rates will return once the economy reverts to its long-term growth path.

  The PCT as discretionary stabilizer will be general in impact.
  *Whatever* you choose to buy will be cheaper to buy.
  Government can inject discretionary stimulus without opening up to clientelist pressures.

  The PCT also minimizes windfall effects.
  Because you have to consume first to take advantage of the lower rate, you cannot channel the government stimulus into further savings.
  In fact, you have to divert from your average consumption path, and consume *more* during the bust.
  Just as a *cash-for-clunkers* scheme, the PCT incentivizes people to *dissave*, except for all kinds of consumption and without the waste of clunkers.

  #### Deciding How Much to Consume, and Who Consumes.

  The PCT allows government to set an arbitrary savings rate.
  Because it is progressive, the PCT can incentivize saving without (see page ).
  The PCT allows for greater saving than the VAT because it (greatly) incentivizes exactly those people to save more, who can:
  the excessive consumers.

  ##### How the PCT Makes You Save More.

  The PCT offers two mechanisms to increase the savings rate.

  First, the PCT is simply an elegant revenue stream for government from which it can finance public good projects (public works) or buy investments (sovereign wealth fund).
  Both a new (non-congested) motorway and public ownership of some corporation constitute saving.

  Second, the PCT is an instrument to alter the save-vs.-consume trade-off for natural persons.
  It encourages saving in three distinct ways (the following is from [@Seidman1997 28ff].

  The incentive effect

  :   of higher post-tax interest rates is more complicated than might appear at first sight.
      Intuitively, tax exempted saving and capital incomes will increase the post-tax interest rates and cause people to save more.
      A *substitution effect* may ensue:
      for every unit of resource saved now, you will receive a greater post-tax payoff in the future.
      You save more.

      On the other hand, a higher post-tax interest rate is an accrual to wealth:
      you just got richer.
      According to the *income effect* of higher interest rates, you may save *less*.
      For fewer units of resources saved now, you will receive a same payoff in the future.
      The PCT is less ambiguous in its effects than a change in the market interest rate.
      It has only a substitution effect.
      Because people are (income) taxed before the PCT, too, introducing the PCT does not make them any richer.
      Taxation does not disappear, it merely shifts the base.
      Think this through again

  The horizontal redistribution (heterogeneity) effect

  :   occurs between *equally* affluent persons who differ in how much they consume.
      Consider two millionaires, one of whom spends all his income (affluent consumer), one of whom saves all her income (affluent saver).
      Under income taxation, both pay a (same!) tax on their millionaire income.
      Under the PCT, the affluent saver pays no tax at all, and the (price inelastic) affluent consumer pays twice the income tax for revenues to stay constant.
      The affluent saver gets to save *all* of her income.
      Under income taxation, she can save only the post-tax income.
      In sum, at same public revenues, more money is saved under the PCT than under income taxation.
      @Seidman1997 estimates US savings rates to increase by roughly 11% due to the heterogeneity effect of a PCT transition.

  The postponement effect

  :   occurs as a one-off effect as the tax burden shifts within cohorts from saving at working ages to dissaving during retirement.
      An income tax burdens savings immediately, and early in life once they are earned.
      A PCT burdens savings late in life, when they are consumed.
      At same levels of retirement consumption, people will be able to accumulate more capital earlier.

      To the extent that the postponement effect occurs *within* cohorts, it is a zero-sum intertemporal redistribution between private saving and public revenue.
      It does not, as @Seidman1997 seems to imply, generate genuine new saving in the long term.
      It just postpones government revenue.

      To the extent that the postponement effect occurs *between* cohorts, it can genuinely improve the savings rate *and* public revenue by taxing old savings twice (or even three times).
      The intergenerational equity considerations of this effect are later discussed in .

  #### It's not All Pleasure-Delaying.

  So far, the PCT appears to encourage thriftiness over all else.
  As Ant --- and even the most die-hard supply-side economist --- will attest, *that* alone would make for a fairly sad state of affairs, with all saving, and ever-delayed consumption.
  As Ant learns, the heart wants some music, too.

  ##### The Party's Over.

  As argued in , there are good reasons to believe that we are growing much slower than we could at greater savings, and that, already, we have taken out loans on the future.
  No matter what the heart wants, we may have to turn down the music quite a bit.

  ##### Deciding How Much To Consume.

  Correctly understood, the PCT is actually agnostic towards how much we, as a society, consume or save.

  What is missing in the description so far --- as it is in much of the politics of tax --- is what happens with the revenue.
  Taxation does not reduce resources, but (with a small DWL), merely redirects them.
  It is then up to the democratic state, or the individuals to which it redistributes, to decide how much should be saved or invested and how much should be devoted to consumption.

  ##### Deciding Who Consumes.

  Let us (optimistically) assume that the current savings rate is optimal, that aggregate consumption must remain on current levels, and that the public expenditure quota is optimal.
  Even in this (unlikely) scenario, the government can use the PCT as a pure redistributive tax to redirect resources from big spenders to small spenders, with no effect on the savings rate or public budgets.
  All government would have to do is to either zero-rate the small spenders (a de-facto redistribution *to* them), or hand out additional transfers to them.
  To go back to the car example, the PCT would redirect resources from buyers of BMWs to buyers of budget Dacia Logans.

  Alternatively, government itself can also spend the revenue on public goods or risk pools.
  For instance, government could organize a big parade or a fireworks display on the national holiday.
  The savings rate would be unaffected.
  The same amount of resources would be spent, just by a different body and for a different purpose.

  ##### S-Classes to Subways.

  Let us now consider what happens when the PCT is used to increase the savings rate, as described in the above.
  When implemented with an appropriately , the PCT *does not* lead to a drop in aggregate demand (page ).
  It merely redirects economic resources from the production of consumer goods to the production of capital goods.
  Under axiomatically assumed , factor markets always clear.
  That means that surplus incomes (savings) will always find profitable investment.

  This capital deepening of the economy can take many forms.
  In the public budget, it can mean building a new school, upgrading our infrastructure, funding basic research or abating and adapting to climate change.
  On the marketplace, it can mean building a new factory for solar panels, developing a new biotech patent or building more equity to guard against the next financial crisis.

  Whatever the use, in a perfect market, capital deepening is an unambiguously good thing.
  It means to enrich our world, with powerful
  factories, liberating technologies and empowering education.
  When people and institutions are given enough time to adapt to the new incentives, no welfare will be lost and no factors will sit idle.
  Mercedes Benz just needs some time to convert its production line from S-Class sedans to economic minivans, or even public transportation.

  #### The Foundational Beauty of the PCT.

  \phantomsection
  [\[sec:foundational-beauty\]]{#sec:foundational-beauty label="sec:foundational-beauty"}
  Gleaming behind its ability to make us all enrich our world, there is a greater normative appeal to the PCT:
  its beautiful alignment with a foundational theory of private property.

  By taxing consumption, the PCT leaves incentives to work *and* save unaffected.
  The PCT *is* as per desideratum [\[des:structural-agnosticism\]](#des:structural-agnosticism){reference-type="ref" reference="des:structural-agnosticism"}.
  Like the VAT, it taxes neither of them, but only the component of *all* income that is consumed.
  In contrast to the VAT, it does so without sacrificing progression.

  "Under the progressive consumption tax", as industrialist C.
  William Hazelett put it to the US Senate in 1939, "we define income at what it really is.
  There is no economic income but the living standard of the taxpayer" (Hazelett as cited in [@Bank2004 15].

  Consumption is the very transaction at which we take a part of the riches of our economy, exclude other people from its partaking and use it up.
  The PCT taxes you for *what you take out of the cake*, not for *what you contributed to the cake* [@Seidman1997 58].

  This foundational ideal of taxation goes back a long time.

  Thomas @Hobbes-1651-aa, in his "Leviathan", wrote:

  > *"\[T\]he equality of imposition, consisteth rather in the equality of that which is consumed than of the riches of the persons that consume the same.
  > For what reason is there that he which laboureth much, and sparing the fruits of his labour, consumeth little, should be more charged than he that living idlely, getteth little, and spendeth all he gets, seeing the one hath no more protection from the commonwealth than the other?
  > But when the impositions are laid upon those things which men consume, every man payeth equally for what he useth, nor is the commonwealth defrauded by the luxurious waste of private men."*\
  > --- Thomas @Hobbes-1651-aa [386]

  Adam @Smith-1776-lq, in his "Wealth of a Nation", wrote:

  > *"Every tax ought to be levied at the time, or in the manner, in which it is most likely to be convenient for the contributor to pay it.
  > \[...\]
  > Taxes upon such consumable goods as are articles of luxury, are all finally paid by the consumer, and generally in a manner that is very convenient for him.
  > He pays them little by little, as he has occasion to buy the goods.
  > As he is at liberty too, either to buy, or not to buy, as he pleases, it must be his own fault if he ever suffers any considerable inconveniency from such taxes."*\
  > --- Adam @Smith-1776-lq [778]

  Both Thomas @Hobbes-1651-aa, the founding father of the modern state, and Adam @Smith-1776-lq, the founding father of the modern economy, hinted at, if not endorsed a (progressive) taxation of consumption.
  [^18]

  ##### The Difference Principle of Consumption Taxation.

  They probably did not know it then, but what already @Hobbes-1651-aa and @Smith-1776-lq saw in the progressive taxation of consumption was the ingenious conciliation of equity and efficiency in the modern world which we now call the @Rawls-1971ian and which here is listed in desideratum [\[des:difference-principle\]](#des:difference-principle){reference-type="ref" reference="des:difference-principle"}.
  The PCT leaves untouched *that* economic inequality in incomes, in incentives, and in entrepreneurship which, in a perfect market, pareto-grows the cake for everyone, including the least well-off, as the difference principle mandates.
  The PCT taxes, discourages, disallows *that* economic inequality, in excessive consumption and positional gain, which slices up the cake in exclusive, inequitable pieces, devours it, leaving only the shameful crumbs for the rest.

  ##### Private Property Isn't Theft. But Neither Is It God-Given.

  \phantomsection
  [\[sec:AntiEntitlement\]]{#sec:AntiEntitlement label="sec:AntiEntitlement"}
  A foundational understanding of private property and taxation is not without its discontents.
  If you believe, as Robert @Nozick1974 does, "that a person is entitled to those goods acquired in uncoerced exchanges with others" [-@Nozick1974 149], there is no good reason (if at all) to tax this *entitled* private property again when it is consumed.
  A comprehensive (de)appreciation of such hyperliberal *entitlement theory* is beyond the scope of this thesis, but a preliminary critique I must offer.

  Naturalizing whatever the allocative results the free market produces as inalienable private property is as ahistorical as it is uncritical.
  Just a cursory look in the history reveals that private property has not been around for a very long time.
  For a constructed entitlement, written and signed on a piece of paper to be powerful enough to guarantee inalienable access to whichever economic resource it concerned, one thing was needed above all:
  security.
  If you have to use a stick everytime you want to exercise your property rights, they are not much worth to begin with.
  In an insecure world, sticks and physical power mean everything, pieces of paper mean nothing.
  This @Hobbes-1651-aaian nightmare of violent anarchy, incidentally, was resolved by the state.
  How did the state and its prototypical racketeers do it?
  They extracted protection money from the people they protected from (or, equivalently, *threatened with*) violence and theft [@Tilly-1985-aa].
  As these racketeers enjoyed technological innovation (gunfire) and economies of scale in their protection of violence, they became larger until they morphed into the modern state.
  From that day on, their protection money was called a tax.

  That hyperliberalism insists on essentially entitled, private property, but now begrudges the polity and the modern state its revenue is, to say the least, ungrateful.

  Private property is not the antithesis to a potent polity.
  They are part and parcel.
  You cannot have the growth that empowers a polity without private property (for now).
  You cannot have private property without a polity either violent enough, or equitable enough to maintain these very entitlements.

  Taxation should treat private property accordingly.
  Not as theft, but as taxable.

  #### The Perfect Tax.

  > *"A progressive postpaid consumption tax emerges as the fairest and least arbitrary of all comprehensive tax systems, precisely because it chooses to make its decisions about the appropriate level of progressivity at the right time.
  > In doing so, it burdens some but not all uses of capital and its yield, and for normatively attractive reasons."*\
  > Edward J. @McCaffery2005 [812]

  Let me introduce you:
  the perfect tax.

  The duty that is both elegant, and fair.
  The regime that lets our economies grow, and have everyone partake in its fruits.
  The excise that reconciles efficiency with equity.
  The only tax that does not either discourage savings, or is regressive [@Seidman1997 2].
  The set of rules that raises the revenue for a potent polity, and, at the same time, curbs wasteful decadence.

  The Nuclear Option --- Wealth Tax {#sec:ScoreWT}
  ---------------------------------

  A wealth tax, or more accurately, an expropriation tax shares many of the advantages of the PCT.

  A wealth tax is superior to a PCT in its ability to disperse the ownership of means of production.
  When inequality is (page ), taxing *consumption* at whichever progressive rate may not suffice to dampen capital accumulation in the hands of very few.

  Three other, more hypothetical considerations speak for a wealth tax.

  First, if there were a macroeconomic crisis of Marxian
  underconsumption, a wealth tax would provide a powerful lever to redistribute resources (to other people or the state) and consume them.
  This is an unlikely scenario:
  Marx's gloomy predictions on the crisis of capitalism have not become reality, and, if anything, OECD economies save too little.
  This is also about a liquidity crunch, and in that respect, it might help, if through a highly discretionary lever, which is not so great.
  In fact, there is both a Marxist (capital accumulation) AND a Keynesian (liquidity crunch) argument for it.

  Second, if there were an inefficient misallocation of resources in an overproduction of private goods (cars) and an underproduction of public goods (levees against rising sea levels), concerted expropriation under a wealth tax could provide for public works revenue much faster than a PCT can.

  Third, if there were a sustained excess indebtedness in public budgets, well-organized and progressive expropriation may be the least inefficient and arbitrary of all evils.
  Sovereign defaults are prone to cause panics and ripple effects in the world economy, as recently evidenced by the Greek debt *crisis* (not default) in 2009.
  Inflating your way out of sovereign debt also has severe adverse effects.
  Rational actors will freeze up their capital in non-monetary assets (such as real estate, or even gold) and be excessively conservative about the future.

  Most importantly, both sovereign defaults and inflation burden natural persons arbitrarily:
  like a corporate tax, defaults and inflation have no well-determined, let alone progressive incidence.
  A wealth tax, for all its shortcomings, has both.

  #### Better Than Income Taxation.

  In contrast to sharply progressive taxation of capital incomes, a wealth tax still maintains (if not strengthens) as per desideratum [\[des:Incentives\]](#des:Incentives){reference-type="ref" reference="des:Incentives"}.
  Even if the taxman will expropriate a certain percentage of your net worth at the end of the year, you will still try to make as much profit with what you have.
  A wealth tax is neutral with regards to the risk aversion of investors.

  #### Property is Power.

  There is an equity argument for a wealth tax, too.
  It requires that we relax condition itm:MaximizeProfits and allow *homo economicus* to make irrational investment decisions.

  If owners of capital exercise *discretion* in their decisions, rather than fully rational (if sophisticated and privately informed) cost-benefit analyses, great wealth bestows great power.
  Such investors, in the classic definition of power, can make other people do something they would not otherwise (pareto-optimally) have done [@Geoff2002 8ff].
  A wealth tax gets at that accumulation of power.

  #### Redistributive Instrument of Last Resort.

  A wealth tax has immense normative and practical drawbacks.
  It is antithetical to capitalist entrepreneurship.
  It disallows market production decisions on those means of productions with are confiscated.

  Most fundamentally, a wealth tax is plagued by the dilemma of having to evaluate in violation of desideratum [\[des:liquid-assets\]](#des:liquid-assets){reference-type="ref" reference="des:liquid-assets"}.
  As a tax on capital, it has to either evaluate illiquid assets as a central planner, or let owners escape taxation and freeze up liquidity.
  Since expropriation is already a state intervention in the economy, it probably makes a certain amount of sense to rely on accrual-based taxation through a central planner.

  #### A Nuclear Option.

  The flaws of a wealth tax are by no means trivial.
  Taxation on realization will allow evasion and wreak havoc on liquidity.
  Taxation on accrual, as expropriation in general, will put the political process under inordinate pressure by private interest.
  The (partial) central planner may be contaminated by widespread clientelism, or incompetent to begin with.
  
  <!-- %broader point:
%avoid zero-sum distribution if at all possible.
%Zero-Sum issues can create rentier politics, this is bad.
	%there is a a case that the WT will always invite rentier dingsda, the PIT will cause DWLs.
%BTW, the economic system influences the political system through rentier politics, the political system the economic one through dwls.
%Make a diagram out of this. -->


  The Backup --- NIT {#sec:ScoreNIT}
  ------------------

  A negative income tax (NIT) can serve to for low-productivity labor by subsidizing the purchasing-power parity minimum living standard of these small earners, as per desideratum [\[des:low-price-floor\]](#des:low-price-floor){reference-type="ref" reference="des:low-price-floor"}.
  It does so more elegantly and with a smaller (desideratum [\[des:minimal-DWL\]](#des:minimal-DWL){reference-type="ref" reference="des:minimal-DWL"}) than minimum wages or combined wages.
  At any level of productivity or gross income, workers will still have (desideratum [\[des:Incentives\]](#des:Incentives){reference-type="ref" reference="des:Incentives"}) to earn more.
  Workers experience less moral hazard not to work, or to work less than they otherwise would.
  Free-riding firms will have a harder time cannibalizing non-subsidized employment.

  #### A Methadone Program for Structural Unemployment.

  A NIT may be a very effective treatment of structural unemployment in the short term.
  In the long term, only greater education and productivity alleviate the root cause of structural unemployment.
  Transferring resources, however elegantly and at whichever level only treats the symptoms, not the disease.
  As a discretionary stabilizer, a NIT can be a structural painkiller, disguising necessary pressures to adapt and reform.

  The Scores {#sec:Scores}
  ==========

  scores different taxes on the desiderata suggested herein.
  Some desiderata are summarized in one entry, when they are very similar or mere specifications.

  #### A Methodological Disclaimer.

  This table is *not* a methodologically sound index of desirability,
  [^19]
  let alone a comprehensive cost-benefit analysis (CBA) of tax choice.
  [^20]

  p4cmccccccccc

  \
  &*vat* &*sic* &*pit* &*Dual PIT* &*cit* &*Business Tax* &*pct* &*Wealth Tax* &*nit*\

  \toprule
  &*vat* &*sic* &*pit* &*Dual PIT* &*cit* &*Business Tax* &*pct* &*Wealth Tax* &*nit*\

  \

  p4cmccccccccc

  \
  &*vat* &*sic* &*pit* &*Dual PIT* &*cit* &*Business Tax* &*pct* &*Wealth Tax* &*nit*\

  \toprule
  &*vat* &*sic* &*pit* &*Dual PIT* &*cit* &*Business Tax* &*pct* &*Wealth Tax* &*nit*\

  \bottomrule
  One Tax, and You'Re Done: As Close to a Beer Coaster Tax as it Gets {#sec:OneTax}
  ===================================================================

  The PCT emerges as the by far superior tax of all of the redistributive taxes scored in the above, both real and hypothetical.
  It can replace all other redistributive taxes, including the (ugly) backstops to income taxation, the corporate, estate and gift taxes.
  Administering the PCT together with any of the existing taxes in the above will at best create unnecessary complications, and at worst, unintended double taxation.

  Organizing redistribution through only *one* tax has tremendous advantages.
  It will reduce costs in the administration and cut red tape for economic activity.
  It will also greatly enhance the transparency of taxation.
  Once the PCT is thoroughly explained, well-designed and implemented, it can enlighten the politics of tax.
  Only if we all understand and know *how* we are taxed and on what, can we begin to have a deliberative debate on *how much* we ought to redistribute.

  #### One Tax Only, Plus Two.

  The PCT may need a supplemental wealth tax and NIT.
  Both of these taxes are very imperfect taxes.
  Metaphorically, they are like powerful antibiotics:
  very effective as a last resort, but at the cost of severe side effects.
  They should be prescribed with care, and only if absolutely needed.

  ##### Bringing in the Nuclear Option: Tax Wealth Only If Absolutely Needed.

  The PCT alone may be insufficient to broaden the distribution of capital, given the self-reinforcing and excessive dynamics of inequality today.
  Taxing only the consumed component may be inadequate to get at some riches [@Shaviro2004 106].
  For some people, no matter how progressively their newest sports car is taxed, they will spend only out of their interest, if not out of petty cash.

  If, and only to the extent that the overall distribution of *private property* is deemed unacceptable only for the reasons mentioned in the above, a wealth tax may be advisable.
  It should target exclusively that inequality of the very, very rich which cannot be adequately taxed on their consumption only.

  ##### Bringing in the Backup: NIT Only If Absolutely Needed.

  The PCT goes some way to lower the price floor of low-productivity labor.
  Very small spenders would be zero-rated in their consumption.
  In effect, these people would receive for free all public goods and risk pools they ever benefit from.
  The productivity of some people may be so low, that even no taxation at all does not make ends meet.

  If, and only to the extent that people cannot live off their equilibrium labor incomes with zero-rated consumption, government should subsidize such labor through a NIT.

  Implementing The Perfect Tax {#sec:Implementation}
  ============================

  A comprehensive suggestion for the implementation of the PCT is beyond the scope of this thesis and my competence.
  Much legal, administrative and design specification will be required to make the PCT real.

  I provide here some preliminary thoughts on implementing the PCT and its problems.

  Durables
  --------

  #### Depreciation, not Expensing.

  A simple addition to a PCT is that durable consumer goods should not be expensed, but depreciated over time.
  A desirable tax as per desideratum [\[des:minimal-DWL\]](#des:minimal-DWL){reference-type="ref" reference="des:minimal-DWL"} will leave , including those between more durable (and expensive) and less durable (less expensive) goods.
  A simple cash flow treatment (expensing) of durable goods would punish people for buying high-quality, presumably expensive durables.
  If you buy a set of new, high quality household appliances in one year, your consumption spikes, irrespective of how long you will use the devices.
  Under a progressive schedule, you would be better of buying cheaper appliances more often (smoother consumption), rather than more expensive appliances less often.
  To avoid such distortion, a PCT should depreciate durables over time.
  The "consumption" of a durable good would incur to your as they are depreciated every year.
  Depreciation schedules for durable goods are tested and readily available in most tax legislations.

  #### *Really* Durable Goods: Real Estate.

  Depreciation of durable goods becomes more thorny for goods that never substantially depreciate, or even *appreciate* in value, as for example owner-occupied real estate.
  There are three possibilities to tax owner-occupied housing, all of which have severe drawbacks.

  First, house owners could be taxed on the imputed rents of the real estate.
  House owners would be treated to tenants, as mandated by desideratum [\[des:minimal-DWL\]](#des:minimal-DWL){reference-type="ref" reference="des:minimal-DWL"}.
  Any appreciation or depreciation of the house would go untaxed just like any other financial investment.
  This would require that the state, in the absence of an equilibrium rent, approximates market rental rates.

  Second, house owners could be taxed on a depreciation schedule set by the government (taxation on accrual).
  This would substantially alter incentives to invest in owner-occupied housing.
  In a house that appreciates in *market* value, occupying owners would be at a relative disadvantage to non-occupying owners and their tenants.
  Much like taxation on accrual, depreciation requires the government to act as a central planner, albeit in a much smaller sector of the economy.
  Under a PCT, only owner-occupied housing, or owner-used durables may require government valuation, not *all* illiquid assets as under income or wealth taxation.

  Third, house owners could be taxed on the resale price of the house (taxation on realization).
  When a house looses market value, occupying-owners will be taxed on the difference in price.
  Owner-occupied housing that gains in market value would escape taxation.
  Much like taxation on realization, taxation on resale price will substantially alter the incentives in the economy, in violation of [\[des:minimal-DWL\]](#des:minimal-DWL){reference-type="ref" reference="des:minimal-DWL"}.
  Markets of depreciating owner-occupied housing may freeze up entirely, in fear of the impending tax burden.
  Markets of appreciating owner-occupied housing may overheat, with demand inflated by the tax-free consumption of such housing.
  Occupying owners would be treated starkly differently than non-occupying owners and their tenants.
  Occupying owners would be subjected to a bifurcated risk distribution.
  If their house gains in value, they go free entirely:
  they gain an income and receive tax-free consumption.
  If their house looses value, they get punished twice:
  they loose wealth and get taxed on the loss.

  On cursory inspection, the least arbitrary and disruptive method to tax owner-occupied housing or owner-used durables in general appear to be imputed rents.

  Introducing the PCT
  -------------------

  The transition to an exclusive, progressive taxation of consumption will require careful planning and specification.

  #### Go Slow.

  \phantomsection
  [\[sec:GoSlow\]]{#sec:GoSlow label="sec:GoSlow"}
  Most importantly, a transition to the PCT must be credible, but very slow.
  Moving to the PCT is probably more a process of (one to three) decades, than of years.
  The principal reason to transition very slowly is that the economy needs time to exit from the production of (positional) consumer goods to the production of investment goods and/or cheaper consumer goods.
  If incentives change faster than firms can cheaply exit and enter, welfare is lost [@Seidman1997 20].
  When Mercedes is forced to abandon the S-Class production line before it is depreciated or before it can be cheaply converted, we are just burning capital.

  It will probably be wise to phase in the PCT over several years.
  The PCT should be introduced on a binding timeline grandfathered-in at year one of the transition, to reliably incentivize firms to change their production.

  Additional problems not discussed here may stem from short- and medium term monetary dynamics.
  A careful investigation of monetary correlates of taxation and the introduction of a PCT in particular must (page ).

  #### Intergenerational Incidence.

  \phantomsection
  [\[sec:IntergenerationalIncidence\]]{#sec:IntergenerationalIncidence label="sec:IntergenerationalIncidence"}
  A tax reform as paradigmatic as from income to consumption will affect people differently depending on when in their lifetime income and consumption streams the reform sets in [@Graetz2009 1649].
  People with savings, absent other specification, will be taxed three times on these savings:
  once when they were initially earned, a second time when they earned an interest (), and a third time when they spend it under the newly introduced PCT.
  People with no savings, absent other specification, will be taxed only once.

  Savings and income follow a probabilistic lifecycle:
  people save out of their income in their middle years to spend when they are old and have no income.
  [^21]
  When the PCT is introduced, people who are old at the time of introduction will contribute more to the polity over their lifetime than people who are young at the time of introduction.

  To a certain extent, intergenerational redistribution of this scope may well be the unavoidable side product of a changing society.
  Equity considerations may come to an end just here:
  you are not entitled to recompensation for *when* in the history of a society you are born.
  Still, the magnitude of triple taxation of old people may be so immense that a PCT should address the intergenerational incidence caused at the time of introduction.

  Investment vs. Consumption
  --------------------------

  #### Deductions.

  The PCT requires a white list for cash uses that qualify as saving.
  For many financial products, the distinction will be straightforward:
  whenever means of production are acquired (equity) or financed (debt), whether as mutual funds, bonds, stocks or life insurance, the respective payments will be deducted from income and dissavings (, page ).

  ##### Education.

  For some cash uses, the distinction may be more complicated.
  Education is a good example.
  On the one hand, *some* component of some education constitutes saving into one's own human capital, one's own means of production.
  On the other hand, education can (and should!) also serve other purposes of self-realization, fulfillment and leisure.
  A summer school in the fine arts is something that we may want many people to enjoy, but it is not in any strict sense an investment.
  Ideally, it should be taxed as consumption.

  These and other lines will be hard to draw in practice.
  Given the broadly beneficial and various spillover effects of education (maybe the fine arts *do* inspire you, after all), it will probably be wiser to err on the side of too much deductable education, rather than too little [@Seidman1997 8].

  #### Self-Employment.

  The line between consumption and investment gets even more blurry, when people own their own means of production other than their human capital.

  First, the distinction between self-employed people and employees should be resurrected.
  When people *do not* bear the full financial risk of their economic activity, their expenses other than education *should not* be deductible.
  Both the commute to work (Pendlerpauschale, commuter tax allowance) and the costs of securing a job (Werbungskosten, income-related expenses), in a perfect market, should be reimbursed in equilibrium incomes, not through tax breaks.

  Second, when people *are* their own risk-takers, all their expenses *should* be deductible.
  Unincorporated, self-employed people must have a tax burden fully equivalent to that of incorporated firms.
  Under a PCT regime, both should not pay any redistributive or general revenue taxes.

  The private consumption unrelated to the business activity of self-employed people should be tax liable.
  In real life, this line will be very blurry:
  which percentage of a large sedan or business attire is required for the job, and which percentage for private use?

  Specifying these rules and regulations for the tax liability of self-employed people (and unincorporated firms) will be very tedious.
  Still, a necessarily unelegant, but rough approximation of what is private and what is business expense should be possible.

  #### Fringe Benefits.

  An equivalent problem occurs when incorporated firms hand out non-cash benefits to employees (or owners).
  These non-cash benefits, while never formally detected as a cash flow under , may constitute additional non-cash income.
  Without further specification of the PCT, such fringe benefits would escape taxation entirely:
  private consumption of the (luxurious, gas-guzzling) company car would go untaxed.

  To avoid untaxed fringe benefits, the taxman has to audit the books of corporations to detect and quantify non-cash Benefits
  [^22]
  .
  Employees who receive non-cash benefits would be tax liable on the cash equivalent of these benefits as incomes.
  All other things equal, if they do not offset their company car use by additional saving, they will be taxed on its consumption.

  Gifts and Bequests
  ------------------

  Gifting and bequesting will not be taxed.
  It is an accrual to (or loss of) wealth (income), but does not constitute consumption.
  Instead, gifted resources will be taxed when *recipients* consume them out of their respective (page ).

  When non-cash resources are gifted, donor and donee have to agree on an evaluation of the gift.
  Donors and donees will have opposing incentives to evaluate the gift.

  Donors will have an incentive to overstate the value of their gift:
  the more inflated the value, the smaller their income, the smaller their taxable consumption.
  If real income drops less than the gift-inflated reported income, people can dissave and spend the difference tax free.

  Donees will have an incentive to understate the value of their gift:
  the more deflated the value, the smaller their income, the smaller their taxable consumption.
  If real income increases more than the gift-inflated reported income, people can dissave and spend the difference tax free.

  Ideally, donor and donee will agree on and report an evaluation close to the equilibrium price of the gift as a result of their opposing incentives.
  [^23]

  Imputed Income
  --------------

  People can consume their own income without either the income or the consumption ever showing up in a cash flow.
  This occurs when people iron their own clothes, or when they sit idle and enjoy their free time.
  Both self-supply and leisure would go untaxed under a pure PCT.
  People would be incentivized to iron their own clothes, rather than have someone else do it for a cash flow detected price.
  Likewise, people would be incentivized to enjoy their leisure, rather than enjoy some additional good or service they could have earned in the same time.

  This is undesirable for two reasons.
  First, it pre-tax market prices in an arbitrary way, in violation of desideratum [\[des:minimal-DWL\]](#des:minimal-DWL){reference-type="ref" reference="des:minimal-DWL"}.
  Ironing your clothes yourself or giving them to a dry cleaning should not be taxed differently.
  Second, it favors autarky over welfare-improving trade.
  When cash-based division of labor is disincentivized, many absolute and comparative advantages may be foregone.
  The dry cleaner may be much more efficient, or at least relatively more efficient in ironing your clothes.

  This problem can be solved by including an imputed income in the cash flow for everyone.
  If you earn no income at all and spend nothing at all, the assumption would be that you consume your own work entirely.
  If you are living the autarky lifestyle, you cannot offset your imputed income with any savings.
  All of your imputed income is, by definition, consumed, and taxable.
  If you are living the separation-of-labor lifestyle, you receive an actual income on top of your imputed income.
  You can spend your actual income and save out of your imputed income.
  At (presumably) equal living standards, only one of the two incomes is consumed, and taxed.
  The PCT with an imputed income is neutral towards the relative configurations of leisure, self-supplying consumption and cash-compensated separation of labor.

  An imputed income also serves as an elegant backstop to barter transactions undertaken to evade the PCT.

  #### Strengthening Comparative Advantage.

  The theory of comparative advantage dictates that one should specialize in whichever production one is *relatively* more efficient [@Ricardo1817].
  Even if a doctor can iron her shirts faster than the worker at the dry cleaning, she should outsource ironing because she is relatively even more productive at providing medical care, compared to the worker with no medical training.
  Efficient incentives should reflect the comparative advantage of the doctor in providing medical care.
  Under the PCT, even with a flat imputed income, this is not the case.

  All other things equal, a highly productive doctor has an *equal* tax incentive to send her laundry to the dry cleaning as, say, a social science PhD student with questionable productivity.
  When they do their own ironing, both are taxed on the *same*, flat imputed income that they are consuming in supplying themselves.
  In reality, the two have very different opportunity costs in ironing:
  doing another brain surgery, or spending another afternoon on the internet.
  Ideally, the doctor should be incentivized to outsource much *more* at *same* levels of consumption than the PhD student.

  A variable, imputed income based on past earnings accomplishes just that.
  If you have shown to be very productive, you will be incentivized to devote your time to that highly productive and well-paid activity.
  If the doctor irons her own shirt, she consumes out of a much higher imputed income on which she will be taxed.
  If she instead gives the shirts to the dry cleaning and does another brain surgery in the meantime, given *same* levels of consumption, she will be taxed only on the presumably lower price paid in cash at the dry cleaning.

  It is important to note that including even a variable, imputed income based on past earnings *does not* force more productive people to work more.
  At *same* levels of consumption, it merely incentivizes them to work whichever time they choose to work at whatever they are best at.

  An imputed income based on past earnings also does not force highly productive people to adopt any *specific* combination of work and leisure.
  It merely incentivizes them to adopt the *same* combination as other people.
  Absent a dynamic, imputed income, very productive people could maintain the same standards of living (consumption) with much less work than less productive people.

  Still, to incentivize productive work, an imputed income based on past earnings must not entirely reflect higher productivities.
  If higher productivity does not allow you to *either* work less *or* consume more, you may never strive too hard in the first place.

  Cross-Border Transactions {#sec:IntlPCT}
  -------------------------

  As with any tax, additional complications arise when cross-border transactions are concerned.

  The problems arising from *different* tax rates or tax regimes between countries are not addressed here.
  The real existing international political economy of taxation is what is *malleable*, or what demands *explanation* given the doable and desirable hypothetical established here.

  #### The End Game.

  First assume that all developed countries have transitioned to the PCT.
  All income, value-added, corporate and withholding taxes are abolished.
  People would be taxed based on residence [@Graetz2009 1645].
  [^24]

  Consumption abroad would be liable to taxation at home.
  Investment abroad, when properly documented, would qualify for tax deductions.
  If in doubt, the taxman can simply assume that cash flows to another country constitute consumption until otherwise proven.
  Conversely, aliens consuming in another country would be taxed in their home country of residence.

  #### The Real World.

  In the real world, international transition to and harmonization of the PCT is likely to occur slowly, if ever.
  In the meantime, introducing the PCT will create some problems and complexities.

  Citizens investing or consuming abroad can be taxed on their global consumption at home.
  Receipts for VATs, income or withholding taxes paid abroad can be deducted from their PCT liability.

  Taxing consumption abroad may violate WTO regulations on the free movement of goods, services and capital.

  People can evade the PCT if they cash in foreign capital and labor incomes abroad and consume it there.
  Considerable international tax cooperation will be necessary to avoid such evasion.
  Non-PCT countries may have few incentives to cooperate.

  Foreign residents earning labor or capital incomes at home, absent any PCT account for them, would still have to be income taxed.
  Similarly, to maintain stable revenues, government would have to retain withholding taxes on foreign-owned corporations.
  [^25]
  This will create considerable administrative duplications and contradictions.

  Family
  ------

  Notwithstanding in accordance with desideratum [\[des:personal-taxation\]](#des:personal-taxation){reference-type="ref" reference="des:personal-taxation"}, people who share living quarters and pool resources should be taxed as one household, as argued in .
  Under a progressive schedule and with no, or only a small penalty to mechanical solidarity in marriage or other forms of intimate cohabitation, the tax liability of such units will depend on the distribution of consumption (not income) in a household.
  A big spender marrying a small spender will enjoy a much greater benefit than two small spenders.

  Aside from spouses, children are often dependents relying on mechanical solidarity.
  Under the pure PCT, they are treated equivalently.
  Their income and saving is added up to a household-wide , consumption is then divided by the number of persons in that household and taxed at the respective rate of *average* consumption in the family.
  While this will already give parents a tax break, it is not clear that the relief would be sufficient or appropriately distributed.

  #### Why Averaging May Not Suffice: Children Are Investments.

  Averaging taxable consumption alone will treat a child exactly like a spouse.
  Considering the low fertility rates in many developed countries and the severe dissaving of an aging (not shrinking!) population, this equal treatment may be insufficient.
  Rearing a child is fulfilling, but it is also a costly investment into the future of your society.

  Averaging taxable consumption alone will give limited financial incentive to procreate.
  I cannot address here whether such pro-natalist policy would be normatively desirable, or even effective.
  Either way, the polity should be *able* to incentivize child rearing, if it so sees fit.

  #### Why Averaging Only May be Undesirable: Tax Breaks Favor the Big Spenders.

  Again, as in marriage, the value of the tax break depends on the distribution of consumption within the family.
  The starker the differences, the greater the benefit.
  Assume that children require relatively less consumption than adults, and are less prone to excessive consumption on their behalf:
  compared to the very big spenders on cars, yachts and houses, even a designer-clad toddler is relatively cheap.
  It follows that those very big spenders, taxed at higher rates will benefit the most from averaging their consumption with that of their (truly) smaller spender children.
  It is hard to defend normatively why of all potential parents the big spender should reap the greatest fiscal benefit for rearing a child.

  #### Add to the PCT: An Allowable Deduction for Children.

  Both of these shortcomings can be addressed by supplementing the PCT with an allowable deduction for children.
  Such a flat deduction would treat consumption on behalf of a child up to a certain amount as an investment into the future.
  It would be fully tax deductible.
  This could be accomplished by simply adding a fixed amount of annual saving for every dependent child to that household's Haig-Simons equation.
  An allowable deduction for children would create an extra incentive *independent* of the level of spending of the parents, so as long as they consume anything
  [^26]
  .

  The Formula for the PCT
  -----------------------

  Specifying the schedule and formulae for the PCT will require extensive econometric and fiscal research, as well as frequent adjustments during its introduction.
  I can only list the terms of the formulae here, and suggest some tentative criteria for each of the terms.

  #### Taxable Consumption in Real, not Nominal Terms.

  Taxable consumption is given by the (page ), with the addition of gifts and bequests made and received, imputed income and an allowable deduction for children.
  Taxable consumption is then averaged over the entire household.
  Taxable consumption should not be in nominal values for two reasons.

  First, nominal consumption would be subjected to inflation.
  If the schedule is constant, people pay ever more taxes by a dynamic called *cold progression*
  [^27]
  .

  Second, economies grow.
  As our economies get richer and richer, consumption should grow, too.
  Notwithstanding the need for a higher savings quota, there is no reason to tax consumption in absolute terms for all time.
  Rather, consumption should be taxed progressively in relation to overall production, or the size of the cake.

  For these reasons, taxable consumption should be denominated *relative* to a multi-year running average of GDP.
  [^28]

  #### Progressive Schedule.

  The progressive schedule, while open to a great deal of political discretion must satisfy the following conditions.

  ##### Sufficient Revenue.

  To be revenue neutral, or to raise more revenue for underprovided public goods and risk pools, the rates must be sufficiently high and sufficiently steep.
  Because discrete price elasticities of demand in positional or excessive consumption are unknown, revenues for any given schedule are hard to project without further econometric research.
  The schedule will likely require careful adjustment as it is introduced and actual price elasticities are observed.

  ##### Savings Rate.

  The schedule must be sufficiently steep to incentivize the democratically elected savings rate, taking into account real dissavings.
  Again, it is hard to project savings behavior for any given schedule without further econometric research or implementation in the real world.

  ##### Generational Incidence.

  To alleviate the triple taxation of old savers upon the introduction of the PCT, the schedule could be allowed to vary for people of different age.
  A term expressing the percentage of life expectancy lived under income taxation could be included in the formula to discount the tax burden for older savers.

  ##### Entry Bracket.

  The lowest bracket will be particularly hard to determine in width and rate.
  [^29]
  On the one hand, it must be sufficiently wide and sufficiently low rated to minimize the as per desideratum [\[des:low-price-floor\]](#des:low-price-floor){reference-type="ref" reference="des:low-price-floor"}.
  On the other hand, an entry bracket too wide in scope and too low in rate may allow too many small-spending people to free ride on the public goods and risk pools financed by everyone else.

  #### Design.

  For the PCT to garner popular support and to work its magic, intelligent design is key.

  ##### Fully Automatic.

  Both to enable instant marginal rates and to reduce administrative cost, the PCT liabilities should be calculated with minimal human discretion, and invoiced fully electronically.
  Since cash flows are already recorded at financial institutions it probably makes sense to interface them directly with tax administration and have them withdraw tax liabilities on a regular basis.
  Given modern information technology and enough time for careful development, an ideal PCT should work without people ever handing in a tax return or many other (paper) forms of any kind.
  The tax administration will establish which cash flow recipients qualify as investment.
  Citizens will indicate cash flows that are donations or gifts.
  All other cash outflows will be treated as consumption.
  Whenever consumers buy an officially recognized durable good, the respective price will accrue to their consumption over time according to a fixed depreciation schedule.
  Lists of durable goods and respective depreciation schedules already exist in developed tax administration.
  Whenever consumers buy owner-occupied housing (or some other extremely durable, owner-used good), they are charged with the imputed rental rate.
  Tax administrations would have to establish electronic lists with fair market rental rates for such goods.

  ##### Instant Marginal Rates.

  PCT liabilities must be invoiced much more often than income taxes.
  People cannot wait until the end of the year until they know how much consumption tax they paid on the last present they bought for Christmas.
  For the PCT to be transparent, and to reliably signal people against positional consumption, people need to know in real time their marginal rate of progressive consumption taxation at *every* possible consumption decision.
  Because the PCT is personally progressive the listed gross prices of goods in the store will have little resemblence to the net prices incurred to individual taxpayers.
  One apple does not have the same VAT rate for everyone, but it may have a tax rate of zero for one small-spending person, and a tax rate of 800% for the big spender next in line at the grocery store.
  [^30]
  Modern ICT (think mobile devices) should enable intelligent designs to inform people about their current marginal tax rate.

  ##### Running Averages.

  Annual invoicing of the PCT also makes little sense because that would cause lower PCT rates for everyone in January than in December of each year.
  At the other extreme, it also makes little sense to tax people for their consumption every day, or even every month.
  Not only would consumption be cheaper in the morning than in the evening, people would also be punished excessively for unavoidable, short-term spikes in their consumption.
  Under daily taxation, buying a suit on one day would be taxed at a higher rate, than buying the jacket and pants on different days.
  Under monthly taxation, a long summer vacation would be taxed at a higher rate than monthly weekend trips.
  This makes little sense because it violates the (page ).
  People must be able to shift consumption freely to some extent.
  In the real world, people probably also receive utility from a long summer vacation for a longer time than just the duration (let alone the infinitesimally short expensing) of the trip.
  Summer vacations, suits and other consumables cannot be practically depreciated.

  Instead, people should be taxed on running averages of their consumption over extended periods of time.
  At minimum, an annual, moving average of consumption will be required for meaningful and practical taxation of consumption.
  A lifetime average consumption, with significant discounting of long past consumption may also be worth consideration.

  Not All Progressive Consumption Taxes are Created Equal. {#sec:PCTTwins}
  ========================================================

  > *"The real and pressingly practical question for tax is not whether to have an income or a consumption tax, but what form of consumption tax to have.
  > The stakes in this battle are clear and dramatic:
  > the fate of progressivity in tax lies in the balance."*\
  > --- Edward J. @McCaffery2005 [817]

  The PCT has been considered and suggested many times in recent history.
  It was considered after World War I as a *graduated spendings tax* [@Bank2004 2], again in 1942 by Treasury Secretary Henry Morgenthau under the label of *graduated surtax on spending* and, most recently, in 1995 by Senators Sam Nunn (D-GA), Pete Domenici (R-NM) and Bob Kerrey (D-NE) as the Unlimited Savings Allowance (USA Tax).
  [^31]

<!-- 
  %also incliude the evil twins FairTax.org and x-tax

  %note that even Mankiw says that moving to a VAT regime (of not exactly PCT) can best be done and is arealdy by ever expanding 401k and so forth.
  %Just note that the problem is:
  %this doesnt tax consumption from dissaving.

  %cite someone that the only remaining choice is between a postpaid or prepaid consumption tax, and why that matters so very much.
  %That's the crime story here.
  %The evil twins are effectively postpaid.

  %Also note that there is nothing wrong per se with having a little bit of VAT in addition, just to make it easier to collect.
  %The lowest bracket can be collected as a VAT.
  %Maybe even higher than that with rebates, that might make it easier and a little more robust against avoidance. -->
  It is important to note that not all these, nor current proposals are created equal.
  They differ in important details from the PCT proposal suggested here.

  First, many PCT proposals, including the 1995 USA tax do not include dissavings in their definitions [@Bank2004 18].
  A PCT that exempts consumption out of debt or savings, leaves a colossal share of excessive consumption untouched.
  Such a PCT is very limited in its progression.

  Second, many PCT proposals are not radical enough in their departure from an income tax regime.
  They keep some of the old clutter and cause debilitating interactions and complications.
  The USA tax, for example, did not terminate the estate and gift taxes, even though these are *transfers of wealth*, not new consumption [@Bank2004 19].
  The resulting administrative complication (evaluation of illiquid goods) and necessary deductions to avoid double taxation of spent gifts and bequests made it an incoherent nightmare.
  [^32]

  #### The PCT's Evil Neocon Twin.

  A particularly brazen disfigurement of the ideal of progressive consumption taxation comes from the American Enterprise Institute (AEI), which sponsors and [markets](http://www.aei.org/outlook/29082) the *@Bradford X-tax* as a progressive consumption tax [@Bradford].
  The @Bradford1986 X-Tax is a two-tiered tax originally suggested in [-@Bradford1986].
  It comprises of a flat, European-style VAT with deductions for all wages, and a progressive wage tax.
  Why anyone would use the term "progressive consumption tax" to describe the Bradford X-Tax is hard to explain, except for sinister intent to create confusion.
  [^33]

  The Least Imperfect Tax {#sec:LeastImperfect}
  =======================

  Borrowing Churchill's classic adage, the PCT may not be the perfect tax, but for all the alternative taxes we know.
  It has two fundamental shortcomings.

  Work/Play, A Constructed and Diffuse Border On Which Taxation Depends {#sec:work-play}
  ---------------------------------------------------------------------

  The fundamental problem in bringing the PCT to the real world is that it depends on a very clear distinction between investment and consumption.
  The problem is:
  this "notion of a sharp division between pleasure-seeking and profit-seeking is alien to human psychology and essentially unrealistic" [@Bittker1973 203].
  Just like (page ) in (page ) the PCT depends on a distinction that does not unambiguously exist in the lives of people.
  
  
  %this is the big-ass homo-economicus question.
  %Include a somewhat extensive discussion, include extensive references, argue why tax (materialism) still matters.

  <!-- %McCaffery
  	%use this as a quote?
  	%People think taxation is a terribly mundane subject.
  %But what makes it fascinating is that taxation, in reality, is life.
  %If you know the position a person takes on taxes, you can tell their whole philosophy.
  %The tax code, once you get to know it, embodies all the essence of life:
  %greed, politics, power, goodness, charity.
  %Everything's in there.
  %That's why it's so hard to get a simplified tax code.
  %Life just isn't simple.
  %-FormerRead more at location 1376   • Delete this highlight
  	%Add a note -->
  

  Where PCT administration defines and enforces this boundary anyway, severe distortions, evasion and administrative complications necessarily ensue.
  The problem of identifying fringe benefits already exists under the income tax [@Graetz2009 1591], and they will become more severe as incentives for tax-free, excessive consumption increase.

  There is no easy or elegant fix to this.
  Tax administrations cannot fairly and simply establish whether an AC at the office, an extravagant business lunch or an executive MBA in an exotic location is an investment, or consumption.
  It is probably both, to some extent.

  These gazillions of loopholes for tax evasion cannot be elegantly closed, by one strike of tax administration genius.
  Instead, the PCT will require tax administrations to plug each and every one of them at a time, all the while not stifling economic activity and maintaining some degree of fairness.

  It appears that whenever government wants to tax progressively, it is, to varying degree forced into the role of central planner and micromanager of inequality.
  The PCT may just offer the least severe of these administrative nightmares, or at least, no worse than the nightmare of progressive income taxation [@Graetz2009 1595].

  Stratification, Elsewhere.
  --------------------------

  Notwithstanding its grandiose ambition to curtail positional consumption, the PCT will not do away with all harmful stratification in the modern world.
  People may simply find other avenues for the very same, very dysfunctional positional games.
  Straightforwardly, people can show off their wealth by displaying slowly depreciating durables, or even jewelry.
  Even when these are taxed on imputed rents, people can still play status games in all our immaterial dimensions of difference.
  With no notice to the taxman or your democratic polity, you can break *The Spirit Level* [@Pickett-2009-kx] through cultural distinction [@Bourdieu-1984-aa], romantic and sexual relationships [@Mazur-1993-aa] or anything else that makes us not only different, but also unequal.

  This is not so much a shortcoming of the PCT as it is the end of democratic, liberal policy.
  Whenever policy moves beyond material leveling, by prescribing habitus, or even whom people meet and mate, it risks poisoning the polity with totalitarian zeal.

  An Angel in Tax
  ---------------

  > *"I will not add fuel to think tank fires.
  > Complexity can wait.
  > The devil may indeed dwell in the details, but we first need to find an angel or two in the abstractions that govern tax."*\
  > --- Edward J. @McCaffery2002 [6f.]

  The limitations and problems of the PCT notwithstanding, it *is* the least imperfect tax.
  In the abstractions even more than in its implementation, these angels point to the PCT.

  [^1]: In Germany, earnings after interest, depreciation and amortization.

  [^2]: When a corporation hands out a dividend, the dividend is also [pit]{acronym-label="pit" acronym-form="singular+short"}ed.
      In some jurisdictions, [cit]{acronym-label="cit" acronym-form="singular+short"} is deductible from the [pit]{acronym-label="pit" acronym-form="singular+short"} on dividends.
      No taxation of dividends applies when the recipient is another corporation.

  [^3]: Payments into capital-based pension schemes are not straightforwardly taxes.
      Government may however choose to mandate or subsidize such payments to increase the savings rate.

  [^4]: Still, the VAT is prone to tax fraud.
      Organized crime gangs can extract money from governments by a strategy of *missing trader fraud*:
      Fraudulent importers buy zero-rated export goods from exporters in other jurisdictions to sell them with VAT to domestic buyers.
      The importing company then absconds (goes bankrupt) without forwarding the VAT to the government.
      Because domestic buyers are eligible for refunds of VAT if they add value to the good, the embezzled VAT by the fraudulent importer incurs loss to government.
      In *carousel fraud*, or, most recently *contra-trading* schemes, a greater number of conspiring firms pass around goods in circles to avoid detection of the original tax fraud.

  [^5]: Greater detail is provided in on the and are discussed in .

  [^6]: The analogy, which I take from [@McCaffery2005], is somewhat amiss, for the original Grasshopper does not earn much, but sings.

  [^7]: In the real world, payroll taxes are levied only on employees, and not on self-employed people.
      That practice *does* change relative prices of employed and self-employed work.
      Analytically, this discrimination is an aberration from a perfect payroll tax.
      In principle, self-employed people should be liable for a payroll tax on the wages they pay themselves.

  [^8]: Social insurance contributions as a selective payroll tax on capped labor incomes *do not* fall on all natural persons, but only some.
      Again, an ideal payroll tax would burden everyone.

  [^9]: This is *not* some kind of welfare-mother argument.
      It is not that lazy people cause structural unemployment and free-ride on the polity.
      Rather, the polity makes it systematically impossible for some of its members to participate gainfully in the economy.

  [^10]: Only a PCT, by virtue of its progressive schedule, will as argued in .

  [^11]: I take these lessons in "tax planning 101" --- only slightly tongue in cheek --- from @McCaffery2005's seminal piece on *A New Understanding of Tax* [-@McCaffery2005 888ff].

  [^12]: Recall that to have a capital income one first has to have a surplus of unconsumed labor income.

  [^13]: Sometimes, at the margin of local decisions public goods also become common goods or natural monopolies:
      that extra motorway feeder may be necessary only for a small number of logistically intensive firms (rival consumption) and local government may well negotiate with the interested firms on whether to build the road or not (exclusion).

  [^14]: This of course depends on a very gentle phasing in of the tax so as to allow producers to cheaply exit their production of excessive consumer goods, and cheaply enter another market.
      This requirement for the of the PCT is further discussed in .

  [^15]: ...even though few people will deny that much of autobahn gratification stems from overtaking other cars, if not people.

  [^16]: BMW's claim, *Freude am Fahren*.

  [^17]: In the extreme, government can even make the PCT a variable, progressive subsidy to low-income earners to spend.
      The PCT would then have a negative rate at the very bottom of the schedule:
      government would reward the first units of consumption with a small subsidy once the transaction is done (postpaid).
      Windfall effects would be minimal as people cannot direct the subsidy into further saving.

  [^18]: Who knows?
      --- Had they known about , and had they foreseen the coming wonders of electronic retail banking, they might have saved us all a lot of trouble.

  [^19]: For starters, desiderata are not (yet) comprehensively exhaustive and mutually exclusive (MECE).
      They are also not weighted.

  [^20]: A fully-fledged CBA would require ordinal, if not cardinal quantification of equity and efficiency.
      Quantifying the gains of the suggested superior tax choice, if possible at all, will be key to the further development of this project.
      For this, and other see further .

  [^21]: Whether this saving is implemented as a PAYGO, capital-based or entirely private scheme is of no relevance to the question of intergenerational incidence.

  [^22]: Note that this is the *only* reason under the PCT for the taxman to check the bookkeeping of incorporated firms.

  [^23]: When the progressive rates of donor and donee are very different, incentives will not be strictly symmetrically opposed.
      A big-spender donor has a greater incentive to inflate, than a small-spender donee has an incentive to deflate.
      Slightly false reporting of prices of gifts and some tax evasion may ensue.
      Where gifts and bequests are substantial and differences in progressive rates great, government may have to intervene and correct evaluations.

  [^24]: The residence principle in taxation is problematic when people frequently and for longer periods of time change their primary residence.
      If you live, spend and work "abroad", you depend on public goods (fire service), risk pools (disaster relief) and redistribution (social peace) in that country.
      In effect, you become part of that polity, no matter the citizenship regime or your legal status as resident alien.
      The residence principle in taxation is fundamentally at odds with a cosmopolitan lifestyle.

      Input and output congruency demand that whoever partakes in a polity pays, and votes in it, too [@Zurn-2000-aa].
      Progressive, of consumption demands that people pay for what they spend, irrespective of where they spend it.
      Even without international tax competition and evasion, these two norms can be reconciled only when all developed countries adopt the same progressive schedule, and the same base for taxation.

      The cosmopolitan contradictions to the residence principle are not germane to taxation.
      They are the principle condition a denationalized world, with no greater functional polity filling the void of the modern nation state.

      Taxation, like other policy areas, cannot respond to this change in itself.
      Without a greater polity, there will be no resolution to the contradictions of residence taxation.

  [^25]: For a different suggestion to transition to the PCT without corporate income taxation of foreign-owned firms, see .

  [^26]: With the addition of imputed income, all people consume something.
      The allowable deduction for children could, for example (partly) offset the costs of child care, whether done by a parent at home, or in daycare.

  [^27]: Again, the monetary dynamics of taxation cannot be addressed here.
      In income taxation, cold progression serves to dampen second-round effects of inflation.

  [^28]: Denominating taxable consumption relative to annual GDP would make the PCT procyclical.
      Short-term deviations from the long-term growth path should not matter.

  [^29]: The lowest, entry bracket of the PCT is the functional equivalent to the VAT.

  [^30]: This example makes obvious a seeming possibility for tax evasion:
      the big spender could give some cash to the small spender and have the small spender buy the apple on behalf of the big spender, at a much lower rate.

      The PCT should be relatively immune to this kind of tax evasion.
      Once the big spender has given her cash to the small spender, the small spender has no incentive, let alone legal obligation to buy the apple.
      The small spender can just keep the cash.

      The only way for the big spender to avoid consumption taxation on the price of the apple was to misreport her transaction to the small spender as a gift.
      It is then officially documented that the transaction was a gift, which, by legal definition carries no strings attached.
      The only option for the big spender to force the small spender to actually buy the apple is to report herself to the authorities for tax fraud and to declare the transaction as a taxable service ("buy me that apple"), not a gift.

      Given these incentives, the tax evasion deal is unlikely to ever occur.

  [^31]: For an extensive review of the history of progressive taxation of consumption, and the USA Tax in particular see @Seidman1997 [11ff]

  [^32]: The gift and estate tax were necessary under the disfigured USA tax because it had ignored dissavings.
      When consumption out of dissaving goes untaxed, tax evasion 101 ("buy, borrow, die") is operative.
      To get at least at some of the inherited and gifted wealth, the ugly backstops of income taxation (estate and gift tax) were kept.

  [^33]: [@Shaviro2004] delivers a particularly revealing example of conspicuous misrepresentation of the abstractions of tax and equity.
      At various points in his advocacy (desecration, really) of the "progressive consumption tax" (the Bradford X-Tax), he describes power, social standing or security through money as an instance of *money illusion* [-@Shaviro2004 106], argues that capital income is a meaningless category on the merits of a thought experiment in which a talented cook buys a restaurant and makes a fortune [-@Shaviro2004 100] and insists that infra-marginal returns are much like labor incomes because "one has only so much time and so many good ideas" [-@Shaviro2004 103].
