\mainmatter

# Introduction {#intro}

> One should always look for a possible alternative, and provide against it.
> It is the first rule of criminal investigation.
>
> --- Sherlock Holmes in Conan @Doyle1904's *The Adventure of Black Peter* [-@Doyle1904 567]

There is something fishy about our current historical moment, sometimes ominously referred to as "late capitalism" [first as description @Sombartmodernekapitalismus1902; then as prophetic critique @OffeSpatkapitalismusVersuchBegriffsbestimmung1972; @MandelLateCapitalism1978; today as snarky sarcasm @LowreyWhyPhraseLate] or "post(-truth) democracy" [@Crouch2004].

On the one hand, in absolute and aggregate terms, the developed world has never had it so good.
At least for now, and albeit threatened by a barrage of geopolitical risks and global imbalances, our global market economy continues to produce marvels of material prosperity.
10 years after the 2017ff Great Recession, many members of the Organization for Economic Cooperation and Development (OECD) report relatively healthy real gross domestic product (GDP) growth rates averaging 2.5% and harmonised unemployment rates (HURs) of around 5.3% in 2017.
<!-- TODO add proper citations -->
These mainstream economic indicators are highly imperfect [^bad_gdp], but they  suggest that far from collapsing under the weight of its ostensible internal contradictions, capitalism is still humming along.

[^bad_gdp]: Even if you accept a narrowly economic concept of societal prosperity, GDP is a fairly bad indicator.
It is widely cited as a measure of economic *growth*, though it actually measures only the volume of market *activity*.
Because there is no economy-wide balance sheet, *real* dissavings, be they earth quakes or environmental exploitation, are not included in the GDP.
In addition, GDP measurements over time are marred by technical difficulties in appropriately pricing the supposedly increased quality of goods and services, among other problems.

On the other hand, the material and institutional foundations of OECD welfare capitalisms appear to be crumbling beneath our feet.
Economic growth in the developed world, while still positive, appears to be slowing in the long run, perhaps never to return to the high rates of the catch-up during the post-war era.
Income and wealth inequality are rising, though some of that widening gap may be driven by smaller household sizes.
In the face of obscene riches, many people are still working harsh, back- or soul-breaking jobs and suffering from relative *and* absolute poverty.
Our economies also appear to be increasingly unsustainable.
In the medium term, macroeconomic imbalances and populist rule threaten global free trade, and renewed asset bubbles (real estate, corporate debt) and fresh systemic risks (index-replicating exchange-traded funds, ETFs) could burst, yet again, into economic crises, merely forestalled by low interest rates, excessive public or private debt and asset rallies.
In the long term, the real dissavings taken out against our planetary ecosystems, including, but not limited to CO2e-emissions, may come to roost as grave environmental degradation of our livelihoods.
At the same time, the institution traditionally tasked with reigning in the economy, the modern welfare state, appears severely constrained in its ability to redistribute market outcomes, to fund public goods and to internalize externalities.
Marred by an increasingly regressive tax base, high debt, homegrown inefficiencies and incompetence, as well as, recently, populist and illiberal upswings, the state seems to be supremely outmatched.
This disturbs the balance of state command and market economy, and may well fray the postwar social contract of relatively widely shared, stable growth, under largely private ownership of the means of production.

<!-- TODO add sources, VK: True for the whole paragraph, but not more details, it's just the introduction/big picture. -->

A similar conundrum besets the state of self-government.

On the one hand, this should be a golden age for democracy.
Citizens today are more formally educated than at any previous time, and they have ready access to realms of information that would put to shame the greatest libraries of yesteryear.
Formal and informal boundaries to citizen participation have fallen, and the electorate has become more demanding of its representatives and government.
New technologies, from cheap and easy web publishing to social media to distributed software systems have made it possible for ever greater numbers of citizens to make their voices heard, to organize themselves and to challenge existing institutions and incumbents.

On the other hand, citizens appear to be increasingly disaffected with democratic incumbents, or perhaps --- according to recent research --- even with democratic institutions.
Populism, illiberalism and outright xenophobia are on the rise in many OECD-countries, challenging both established parties and established democratic norms.
Voters appear to become more polarized, at least in some countries, and at some level of government.
Political debate, too, seems to fray, with increased tribalism, utter disregard for facts and a decline in civility.
Here too, the postwar social contract appears to be crumbling: liberal democracy, with its finely tuned balance of individual rights and collective obligations, guarded by an iron-clad rule of law is now under attack.

How, then, are we to square these seemingly antithetical diagnoses of our current historical moment?
Has there been some foul play with welfare capitalism and liberal democracy?
Or is this just the way the world works, bursting our delusional, progressive bubbles?

Critical social scientists, from @Marx-1867-aa to today's gloomy pronouncers of "post-democracy" [@Crouch2004] and "late capitalism" [@mountford2011] are always prone to suspect foul play.
They highlight ostensible contradictions of current economic and social arrangement, and contrast a deplorably imperfect present reality against preferable arrangements past or future [also see @Streeck2013; @NachtweyAbstiegsgesellschaftUberAufbegehren2016].
This ambition to mold evolved institutions, and sometimes human behavior itself, to birth a better world may have provided, if sometimes in a roundabout way, the emancipatory impetus for many progressive achievements, such as Bismarckian social insurance or universal suffrage but it has also fueled the hybris of social planners [see @SpuffordRedPlenty2011], and is associated with the evils of 20th century left authoritarianism [@Hayek1944; but compare @arendt_origins_1973].
<!-- TODO add meta reference to Bismarck -->
<!-- NOTE VK: fantastic transition! -->

By contrast, conservative and libertarian observers, from @Burke1790 and @Hayek-1960 to modern-day critics of democratic rule [@Caplan2007], liberal multiculturalism [@haidt_righteous_2012], rentier capitalism [@zingales2014capitalism] and economic utilitarianism [@McCloskeyBourgeoisVirtuesEthics2006] find nothing outrageous, let alone suspicious about welfare capitalism and liberal democracy in disarray.
From this vantage point, an overextended state and overly inclusive or demanding polity is simply crumbling under the weight of its unkept promises and collective action dysfunctions, as was to be expected all along.
Many, more moderate critics may be worried what the postwar compact might take with it, should it go down violently [see @acemoglu_why_2012].
But fearing collateral damage to the rule of law, property rights or even liberal democracy does not imply that there would be anything wrong with a retrenchment of state intervention.
<!-- TODO add citation for moderate critics -->
Conservative and libertarian viewpoints easily come across as curmudgeonly or even cynical, but they are ignored and disavowed in the much of the social science at all our peril. 
This healthy skepticism of man-made societal designs and respect for the wisdom contained in evolved, and therefore stable institutions must not be ignored.
In the extreme, however, conservatism and libertarianism risk collapsing entirely that what *is*, and *should* be, negating all collective political action in Panglossian tautology [@Voltaire1759].

We should interrogate our present situation through both ideological lenses --- and any other viewing aids not neatly foldable into these two camps --- if only to be aware of our blindspots, and perhaps, even to expand our moral horizons.
<!-- VK: which lenses? (repeat it)-->

Still, both approaches are equally limited in their scientific rigor.

Critical observers always assume we have been duped out of some better world and jump right to the "whodunnit" question.
In the extreme, historical materialism conflates entirely the questions of economic constraints and political causes, because it conveniently assumes the latter to be mere superstructure to the former [@popper_poverty_2013; compare @Marx1844].
The modern-day heirs of post-structuralism and associated post-isms take a similar tack when they define away, or straight up ignore such at least pragmatically useful concepts such as productivity, marginal use or even rational discourse as mere language permeated by power [see @Gibson-Graham2006 and @Peters2001; broadly @Laclau2014; distantly @Foucault-1972-aa].
Not only are concrete critiques of the supposedly corrupted intellectual apparatus undergirding, say, "neoliberalism" such as the first theorem of welfare economics [graphically by @Lerner1944; mathematically by @Lange1934; @Debreu1954] conspicuously hard to come by amidst all the intramural casuistry, but these nominally "political" theories are also surprisingly mum on policy for the here and now [see @Rorty1999].

Conversely, conservative or libertarian commentators reject the mere possibility of collectively decided improvements, and therefore will never open any investigation into the causes of, or culprits for what might otherwise be recognized as shortcomings.
<!-- TODO expand this, add references -->

Either way, assessments of our present situations become unfalsifiable.
The critical social scientist assumes *no* (relevant) exogenous constraints on collective designs, thus hermetically suspecting all limitations to be "inside jobs".
To the conservative, evolved institutions are *already* largely determined by inviolable exogenous limits and therefore leave little way for reform or wrongdoing.
The libertarian assumes that collective choice, however constrained, is *impossible* or undesirable to begin with, and therefore rejects any comparison of coercive institutions.

In the rare case that these strands of research engage each other at all, a fruitless shouting match ensues, about the proverbial half-empty, half-full, or un-fillable glasses, respectively.

This dead-end can be ameliorated by less ideologically committed, more empirically minded research, but never entirely avoided.
Because history does not afford proper experimental designs, positive science typically relies on longitudinal comparisons against some point in the past [e.g. @Streeck2013].
The limitations of these designs are best illustrated using quantitative variables, but may extend to qualitative observations as well.

These comparisons are complicated by the fact that in the past, all other things were emphatically *not* equal.
For example, consider seemingly widening inequality, frequently operationalised or surveyed as *household* income inequality [e.g. @Piketty2014].
Troublingly for these accounts, household size in much of the OECD-world has decreased substantially over the past decades, potentially contributing to inequality independently from economic or tax changes.
For instance, the otherwise increase in in income inequality in Germany from 1991 to 2007 is "strongly related" to changes in household composition [@Peichl2012: 118].
<!-- TODO find similar paper for the US -->
Of course, it is not clear whether we should take solace in supposedly exogeneously smaller, poorer households.
Smaller households may well, in part, reflect a preference for greater autonomy over greater household incomes, but they may also be, in part, an *effect*, not a *cause*, of broader economic shifts, such as increased job mobility, the decline of relatively well-paid manufacturing jobs or overhangs in marriage markets, or any number of other changes in the same time period.
Adjusting for changing household sizes is possible, but results appear to be highly sensitive to the some arbitrary choice of equivalence scales  [@Aaberge1998].
Similar problems beset even the painstakingly careful and seminal "Capital in the 20th Century" [@PikettyGoldhammer2014, but compare @McCloskey2014] or seemingly simple matters as to how to appropriately deflate increasing computing power in national accounts [@Schreyer2002].

Dig deep enough into the operationalisations, extend the time horizon long enough, accrue enough changes in context, and longitudinal studies turn increasingly on ontological and axiological choices, in the worst case reverting to an ideological Rohrschach tests.

These limitations at the margin notwithstanding, careful longitudinal research continues to be valuable, especially because it --- in contrast to more ideologically committed, self-referential works --- ensures that the social sciences remain a *cumulative* enterprise of discovery.

But, given our lingering disagreement, and the gravity of the crime in question, perhaps it is worthwhile to try another investigative strategy.
That is what I offer here.


# A Crime Story

<!-- VK: questions are not necessary, you made that clear before. -->
Why, in spite of all our technological marvels and economic wonders are we still plagued by widening inequality, poverty, instability and depleted commons?
Why, with all the information and levers of participation at our fingertips, are we so thoroughly confused about governing our mixed economies, and so perilously disaffected with the results our democratic rule produces?


This dissertation is fairly pedestrian.
I tread in some of the mundane minutiae of modernity;
initially the twists of tax, and later the details of democratic rule.
And yet, in that small print of the social contract, I have found a veritable crime story.

The story begins with (, p. ):
why, in the richest of countries, in the most enlightened of times (current day [oecd]{acronym-label="oecd" acronym-form="singular+short"}-world) do we still find ourselves amidst (, p. ):

1.  of welfare states, too constrained to elegantly improve upon the equity, efficiency and sustainability of markets,

2.  of democracies, too paralyzed to meaningfully rule their economies and

3.  consequently, of political equality and economic opportunity?

This lament alone does not mean there was crime:
maybe, these are no crises, but just facts of life, and a thorough investigation is unnecessary.
Likewise, we do not call in murder police when some centenarian does not wake up one morning.
However, at least, we task a doctor to establish a cause of death.
So it is with these three crises:
before any criminal investigation can start, I must establish a causal theory for constrained welfare, paralyzed democracy and rampant inequality.
I find that causal theory in the complex interactions of markets and plans, as they coexist in a (, p. ).
Specifically, I find that of the political institutions that make up an intact mixed economy, most to welfare, democracy and equality (, p. ).

This dissertation is staunchly reformist.
Just because a system may be in crisis, it does not require a revolutionary overhaul, nor does it warrant dialectical glee about its supposed inevitability.
I stick to the market economy *and* the welfare state, and merely tinker with tax to make them coexist better, and to mutual advantage.
There, I have found a scandal.

Our choice of tax can only be scandalous, let alone criminal, if there is, in fact, a better tax.
And so, in (p. ) I ask:
what makes a (, p. ) and what makes it (, p. )?
I evaluate all real and hypothetical taxes on these criteria, and find:
(progressive) taxes on the (unimproved) value of land and (postpaid) consumption are much than the ones we have (, p. ).
By comparison, our existing taxes on income and (prepaid) consumption appear staggeringly inefficient, inequitable and unsustainable.
Because the tax foundations of our mixed economies are thus sabotaged, our democracies must needlessly trade off efficiency, equity, and sustainability.

This dissertation is sociological, not just economic.
I cannot merely posit a suboptimal choice in tax, but I must theorize and test some social process to account for the supposedly suboptimal choice in tax.

is the social process that ought to rule collective choice (, p. ).
It, too, needs specification:
what it strive for (, p. ), and what it deliver (, p. )?
In the balance of these questions I find:
liberal, but deliberative democracy may be much than the representative institutions we have (, p. ).
By comparison, the status quo of pluralism appears to be a minimal formulation of liberal democracy, as skeptical about what people *can* do, as it is restrictive about what democracy *should* do.
Once a historical achievement, it today appears hopelessly outmatched by the vast complexity and tightly concentrated special interest of late capitalist society.


(p. ) investigates the link between .
I start by rounding up for suboptimal taxation (, p. ) and proceed --- as Holmes advises --- by the method of elimination.
First up:
democracy itself.
Maybe, "suboptimal" tax is, in fact, the *popular* choice.
Only if it is not, is there a failure of the political process to be puzzled over, and accounted for.
I suggest that tax choice depends on the *kind* of democracy.
Tax choice may suffer , because it is very complicated and offers tightly concentrated special interest (, p. ).
More broadly, the two crimes of suboptimal taxation and limited democracy are intimately related.
People might not just widely misunderstand taxation, but they might err systematically about the trade-offs of ruling a mixed economy.
These systematic misunderstandings under the dysfunctions of pluralism might interact with the unattractive alternatives of a dysfunctional tax regime to dramatically constrain any popular choice of tax, and divert the polity away from the equity, efficiency and sustainability they might otherwise prefer.
Democracy and taxation might be closely intertwined in their supposed mutual crises, but they also constitute two sides of the same coin that is the liberal-democratic, capitalist social contract.
Democracy concerns the making of collectively binding decisions, taxation is the chief means to implement these agreed-upon plans within the market exchanges of free agents.
Conversely, democracy legitimates tax and calls the trade-offs of the mixed economy, and taxation also shapes the material conditions under which people decide, and collects the resources to power policy.
Not surprisingly, democracy and taxation share , and their crises and reform hinge on the same questions of equality, justice, cooperation and human nature (, p. ).

This dissertation is also empirical.
To stay clear of hermetic ideology, and self-referential critique, I must get up from the normative armchair and show that really, a better democracy and better tax *are* related and *can* be had.

A good crime story cannot rely on conjecture alone, it needs supporting evidence.
I cannot provide an instrument of crime because history does not leave material what-ifs in its wake.
But I can try to capture these hypotheticals in an :
if ordinary
people, under an *alternative*, democratic process, choose an *alternative*, preferable tax, *that* would be as close to a smoking gun (, p. ) as it gets.
If, moreover, that experimental democracy can be shown to alleviate some of the dysfunctions of pluralism, and misunderstandings of the mixed economy, and if, consequently, through that democratic fora, people prefer an alternative tax, we know for sure that *some* crime *has* happened.



# A Desirable, Doable Hypothetical

If world history is still written in tax, as @Schumpeter believed, us democratic citizens, too, must be fluent in fiscalese, to live up to the emancipatory promise of modernity.
<!-- VK: "still written"? check transition to tax-->
If communicative action can heal the disagreement and confusion wrought as modernity differentiated System and Lifeworld, as @Habermas-1984 hopes, in our discourse on tax, too, universally acceptable validity claims instead of money and power must rule to uphold our faith in liberal democracy.

I here probe into one intersection of legitimate inputs and outputs of the social contract [compare @Scharpf1997]:
the discourse *on*, and economics *of* tax.

I ask, how --- if at all --- people under current democratic arrangements think and speak differently about tax, from how they *would* think and speak about it, if they lived under conditions of ideal speech.
<!-- not so much the speech with q any more ... -->
I test, how --- if at all --- people change their thinking and speech about tax, if they participate in a democratic process that is *closer* to the Habermasian ideal?
I hypothesize that --- as a result of *more* ideal speech --- people will prefer different taxes, including a PCT.
<!-- %rather than more, write closer to, more could be misunderstood -->

<!-- This is a crime story ... -->
<!-- . Introduction [based on introduction] -->
<!--    - why does any of the following matter? -->
<!--    - because the *welfare state (or mixed economy)* is based on good taxation, and taxation is in crisis. -->
<!--    - because *representative/pluralist democracy* faces structural (dealignment) and inherent challenges (public choice); tax is that issue where these problems intersect. -->
<!--    - these possible crises of democracy and taxation may have a profound effect on *social and political equality* -->


> **What if** there were alternative taxes, which afforded us more attractive tradeoffs between economic efficiency, equity and sustainability or other ends  
> **What if** we *could* agree on such alternative taxes, but *would not*, because we lacked the necessary information or suitable fora, and because our capacity for mutual reason-giving had been diminished by alienating inequality or clouded by special interest? -->

<!-- %Second, my research interest emerges from a sense of utter disconnect between political debate and the abstractions and interests governing the political economy.
%This dis-connect is evident in misleading sloganeering (‘Mehr Netto vom Brutto’, more net out of gross income), widespread superstitions (‘employers [sic!] pay half of social insurance’), bastard Keynesianism (‘consumption is good!’) or redistributive smoke grenades (‘we should tax companies’).
%At a deeper level, I wonder whether pluralist interest and electoral re-presentation can still be reasonably assumed to yield efficient and equitable policies, in an ever more complex world marred by cooperation problems. -->


## Structure of the Dissertation {#structure}

The following chapters follow a fairly conventional structure from theory to methods to results and conclusion, but the *status* of especially the first couple of chapters may be unclear to readers.
Out of substantive necessity, the references and disciplines in these first couple of chapters can be quite wide-ranging, though these are merely introductory (for the reader) and remedial (for the participants).
To clarify the role of these chapters, let me first situate them within the remainder of this dissertation.

This project is modeled on a straightforward experimental design, as it is frequently used in clinical studies.
However, because the study deals not with easily measurable biomarkers, but with subtleties of deliberation and the abstractions of tax, the design needs a little more conceptual groundwork.


Consider an analogous example to let me guide you through the following chapters:
A doctoral candidate in medicine wants to study how a daily morning exercise affects mindfulness.
In this exercise study, the absence (or presence) of the morning routine is the *independent variable* (IV), the kind and level of mindfulness the *dependent variable* (DV).
Analogously, in the present study, the participation in the CiviCon citizen conference is the *IV*, and changes in the subjectivities and preferences concerning taxation are the *DV*.[^no-rct]
<!-- TODO might cite some experimental design literature here -->

[^no-rct]: Proper experimental designs are often double-blind *randomly controlled trials* (RCT), but these additional rigors are not possible or deemed unnecessary for the present study on deliberation and taxation.

  - A fully **randomized treatment** is impossible, because participants in a deliberative forum will (and should) always be free to exit the sample.
  Because the universe of participants are all citizens, or even all human beings affected by the policy in question, even a reasonably representative quota sample will be hard to come by.
  Largely because of limited resource, the present study is a self-selected haphazard sample, described in more detail in chapter \@ref(civicon).
<!-- TODO ... is that the right reference? VK: it is.-->
  - A **control group** of non-participating citizens would be possible in the present study, but was not included because of limited resources.
  In any event, there were no expected background events or trends affecting the subjectivities concerning taxation of *both* treatment and control groups, so a control group was deemed dispensable.
  Whatever changes the participating citizens displayed are likely to be a result of the deliberation.
  - A **blind design** is impossible because participants will, by the nature of the treatment, always know whether they are participating in a deliberative forum, or not.
  There should be no *placebo* deliberations, though there may well be those formats worthy of such a label.
<!-- TODO refer to chapter were I diss other formats -->


Table: (\#tab:commented-toc) A Commented Table of Comments with Analogous Experimental Design

| Research Design Concept | Hypothetical Mindfulness Study | This Study | Chapter |
|-------------------------|-------------------------------------------------------------------------------------------------------------|-------------------------------------------------------------------------------------------------------------------------|----------------------|
| Research Topic | Exercise and mindfulness | Deliberative democracy and taxation | \@ref(intro) |
| Background | Stress and the body | Why taxation matters | \@ref(3-crises) |
| Theoretical Background | Diet (*mitahara*), body cleansing (*shatkarma*), breathing (*pranayama*) and some philosophical background | Optimality, Incidence, Haig-Simons Equivalence, Circular Flow, Personal Taxation as well as some axiology and ontology | \@ref(abstractions) |
| Operationalisation | 5 selected asanas (positions), including the rare *firefly pose* | Fundamental choices in taxation: base and schedule | \@ref(base-schedule) |
| Treatment regimen | In-Person group sessions at local gym | Weeklong deliberation with room and board and extensive learning phases | \@ref(civicon) |
| Measurement | - | Q Methodology | \@ref(q) |
| Field Report | - | Report from the CiviCon Citizen Conference | \@ref(field-report) |
| Results (Baseline) | - |  | \@ref(baseline) |
| Results (Treatment) | - |  | \@ref(treatment) |
| Discussion |  |  |  |
| Conclusion |  |  |  |

<!-- \ref{part:puzzle}
& 	\emph
&	\nameref{part:puzzle}
&	Proposal
&	\emph{Explicates the research gap.}

	The current crises and performance of both established democracy and welfare states can only be understood, when compared with desirable and doable hypotheticals in democratic fora and tax.
&	\pageref{part:puzzle}
\\

\emph{}
& 	\ref{chap:wanted}
&	\nameref{chap:wanted}
&	Foundations
&	\emph{Lays out the structure, epistemology, ontology and axioms of the dissertation.}

	Social scientists must ask not just what \emph{is}, but what \emph{could} be (First Order Theory) and explain why it is not (Second Order Theory).
	Such hypotheticals must be desirable and doable.
	Desirable and doable are defined.
&	\pageref{chap:wanted}
& 95
\\


\emph{}
&	\ref{chap:mixed-economy}
&	\nameref{chap:mixed-economy}
&	Theoretical Background
&	\emph{Explains for which ends, and by which means market and plan can coexist.}

	Welfare states are properly understood as mixed economies, where government supplements market outcomes by coercive plan.
&	\pageref{chap:mixed-economy}
& 90
\\

\emph{}
&	\ref{chap:3-crises}
&	\nameref{chap:3-crises}
&	Empirical Background
&	\emph{References empirical and theoretical findings on the intertwined crises of democracy, the welfare state and equality.}

	Established democracies are constrained, gridlocked and confused.
	Welfare states are unsustainable and/or defunct.
	Economic inequalities are widening.
&	\pageref{chap:3-crises}
& 65
\\


\emph{}
&	\ref{chap:tax-matters}
&	\nameref{chap:tax-matters}
&	Literature Review
&	\emph{Explains how tax matters to the mixed economy, welfare state and democracy.}

	Mixed economies rely on efficient and equitable taxation.
	Democratic government always faces trade-offs in designing welfare states.
	Voters must understand these alternatives, and all materially possible designs must be available for voters.
&	\pageref{chap:tax-matters}
& 80
\\

\emph{}
&	\ref{chap:hypotheticals-matter}
&	\nameref{chap:hypotheticals-matter}
&	Critique of the Literature
&	\emph{Without appreciating doable and desirable hypotheticals, social science becomes latently affirmative.}

	This is especially true for welfare state research.
	Absent a critical comparison to a hypothetical ideal mixed economy, the second-order account of welfare fails to explain most of the current shortcomings.

	%more text missing?
&\pageref{chap:hypotheticals-matter}
&60
\\

\emph{}
&	\ref{chap:testing-hypotheticals}
&	\nameref{chap:testing-hypotheticals}
&	Research Design
&	\emph{Describes the positive research design to make the hypotheticals empirically falsifiable.}

	Under a different (deliberative) democratic process, a random sample of ordinary voters will understand the mixed economy differently and prefer a different (progressive consumption, land-value) tax.
&	\pageref{chap:testing-hypotheticals}
&65
\\

\midrule

\ref{part:tax}
&	\emph{}
&	\nameref{part:tax}
&	Theory
&	\emph{Reviews mainstream economic thinking about desirable and doable taxation.}

	The first order theory of tax asks, and answers what the most desirable, but doable tax is.
&	\pageref{part:tax}
&
\\


\emph{}
&	\ref{chap:desirable-tax}
&	\nameref{chap:desirable-tax}
&	Theory (Review)
&	\emph{Reviews mainstream economic thinking about efficiency and equity of taxation.}

	A desirable tax offers one of the higher possible trade-offs between efficiency and equity.
&	\pageref{chap:desirable-tax}
& 80
\\


\emph{}
&	\ref{chap:doable-tax}
&	\nameref{chap:doable-tax}
&	Theory (Analysis)
&	\emph{Lists factual complications and contradictions of taxation.}

	A doable tax is personal, falls on inelastic bases, has a well-defined incidence, least affects liquidity choices and is agnostic towards the source of income.
&	\pageref{chap:doable-tax}
& 85
\\


\emph{}
&	\ref{chap:better-tax}
&	\nameref{chap:better-tax}
&	Theory (Synthesis)
&	\emph{Evaluates real and hypothetical taxes on the aforedeveloped criteria of desirability and doability.}
	A \glsfirst{pct} and \gls{lvt} emerge as by far the best, most desirable and doable taxes.
	Other, existing taxes violate efficiency, equity, or both and display manifold unintended consequences and unavoidable loopholes.
&	\pageref{chap:better-tax}
& 85
\\

\midrule

\ref{part:democracy}
&	\emph{}
&	\nameref{part:democracy}
&	Theory
&	\emph{Reviews normative, theoretical and empirical political science on democracy.}

	The first order theory of democracy asks, and answers what the most desirable, but doable form of democracy is.
&	\pageref{part:democracy}
&
\\

\emph{}
& 	\ref{chap:desirable-democracy}
&	\nameref{chap:desirable-democracy}
&	Theory (Review)
&	\emph{Briefly reviews normative political theory on democracy.}

	A desirable form of democracy provides effective participation, control of the agenda, voting equality and enlightened understanding \citep{Dahl-1989-aa}.
	%MN COMMENT: sehr spezifische Sichtweise der Demokratie; wieso soll ausgerechnet das das beste an der Demokartie sein? Was ist mit power, interest, praxis?
&	\pageref{chap:desirable-democracy}
& 10
\\

\emph{}
&	\ref{chap:doable-democracy}
&	\nameref{chap:doable-democracy}
&	Theory (Analysis)
&	\emph{Briefly reviews public choice theory and political psychology.}

	Some likely micro- and macropolitical dynamics divert real existing, formally democratic government from normative desiderata.
	Doable democracies face different, sometimes unattractive, trade-offs between participation, deliberation and political equality \citep{Fishkin2009}.
	In complex societies, the dysfunctions and trade-offs may be harsher, still.
&	\pageref{chap:doable-democracy}
& 10
\\


\emph{}
&	\ref{chap:better-democracy}
&	\nameref{chap:better-democracy}
&	Theory (Synthesis)
&	\emph{Briefly reiterates the deliberative theory of democracy, and describes prominent institutional designs.}

	Deliberative democracy promises to overcome many of the trade-offs and dysfunctions of pluralist democracy, by stressing intersubjective understanding and communicative action in lieu of pre-social preferences and power in speech.
&	\pageref{chap:better-democracy}
&10
\\

\midrule

\ref{part:tax-democracy}
& 	\emph{}
&	\nameref{part:tax-democracy}
& 	Theory (Original)
&	\emph{Develops a second order theory of democratic choice of tax.}

	Deliberative democracy is a good \emph{method} to test one explanation for the absence of a better tax.
	%MN Comment: nein, keine Methode -- das ist Fishkins Fehler
	Deliberative democracy is also \emph{more} than a method:
	deliberation and \gls{pct}/\gls{lvt} are conceptually related.

	Tax is a good \emph{case} to test deliberative democracy.
	%MN comment: wieso sollten wir sie testen?
	Tax is also \emph{more} than a case:
	it is \emph{the} social contract in capitalism.
&	\pageref{part:tax-democracy}
&10
\\


\emph{}
&	\ref{chap:no-better-tax}
&	\nameref{chap:no-better-tax}
& 	Theory (Original)
&	\emph{Reviews and develops alternative second order explanations for why we do not have a better tax.}

	We may not have a better tax, because progressive taxation is plagued by a global cooperation problem, because of path dependency, because of domestic political dysfunctions or, simply, because people do not want it.
	I try to falsify only the last explanation, and theorize how different democratic processes may alter, suppress or confuse the will of the sovereign.
&	\pageref{chap:no-better-tax}
&55
\\


\emph{}
&	\ref{chap:tax-under-pluralism}
&	\nameref{chap:tax-under-pluralism}
&	Theory (Hypotheses)
&	\emph{Hypothesizes falsifiable, popular misunderstandings of tax and the mixed economy that may divert voters away from the \gls{pct} and \gls{lvt}.}

	Voters incorrectly think
	\begin{inparaenum}
		\item that a mixed economy cannot have an arbitrary savings rate,
		\item that nominal variables reflect actual savings,
		\item that a mixed economy cannot have an arbitrary state-market mix,
		\item that non-natural persons can be taxed and
		\item fail to aggregate different taxes, indirect taxes and ``social contributions''
	\end{inparaenum}.%add hrefs to the above?
&	\pageref{chap:tax-under-pluralism}
&35
\\


\emph{}
&	\ref{chap:common-grounds}
&	\nameref{chap:common-grounds}
& 	Theory (Outlook)
&	\emph{Develops conceptual and theoretical linkages between the \gls{pct}, \gls{lvt} and deliberative democracy.}

	The \gls{pct}/\gls{lvt}  and deliberative democracy embody and enforce a similar standard of justice as fairness \citep{Rawls-1971}.
	The \gls{pct}/\gls{lvt} enable the kind of equality on which deliberative democracy relies.
	The \gls{pct}/\gls{lvt} and deliberative democracy both build, and require deep cooperation.
&	\pageref{chap:common-grounds}
&15 -->


We need to complicate this simple design only a little bit to bring it close the present study on deliberation and taxation, as shown in table \@ref(tab:commented-toc).

First, let us assume that our M.D. to be presents good reasons to concentrate on a *particular* kind of exercise, say, hatha yoga.
Perhaps, the aspiring doctor argues convincingly that hatha yoga is an especially promising treatment, or that it has been previously understudied, or that really, "exercise" without the kind of body-awareness honed by hatha yoga is a meaningless concept, likely to yield only spurious effects, if any.

So it is with this research on deliberation and taxation.
In chapter \@ref(3-crises) I argue that taxation is a key, yet understudied precondition for a functioning mixed-economy and that to be effective, deliberation needs to engage with highly structured and abstract topics such as tax.

Secondly, suppose that our M.D.-hopeful insists on teaching the participants not just some positions, but also other related practices such covering diet (*mitahara*), body cleansing (*shatkarma*), breathing (*pranayama*) as well as some philosophical background.
At this point, her supervisors get a little anxious and worry where this might all lead.
However, our medical student maintains that concentrating on exercise alone is alien to the tradition and shows how the elements of hatha yoga are neatly intertwined.
She is the first to admit that she is not an expert in philosophy, let alone buddhism, but she is confident that she can provide at least *some* helpful background for participants do understand the broader context.

Analogously, this dissertation also requires some deep background for participants and readers alike.
In chapter \@ref(abstractions), I rehearse a few selected abstractions of taxation and microeconomics, including optimality, incidence, the Haig-Simons equivalence of income, the circular flow of the economy and implications of personal taxation.
I describe why these are necessary concepts to any reasoned debate on taxation.
Because these concepts, along with their underlying ontological and axiological assumptions are also contentious, I also provide a working vocabulary of economic philosophy to explicate the ideological import of these concepts.

Thirdly, imagine that our medical student is also quite particular about proper postures and requires subjects to concentrate on, say, the somewhat obscure and demanding *firefly pose*, along with four other precisely defined positions, and nothing else.
Her supervisors wonder why she could not use simpler, more mainstream positions, such as the *downward-facing dog*, or *really*, just some plain breathing exercises.
The medical student counters that *only* these selected five positions, evolved over centuries, form a well-rounded exercise regimen and rehearses some biomechanical research to support her claim.

This dissertation, too, is quite particular about the taxes to be deliberated on.
In chapter \@(hypotheticals) I argue, citing some mainstream economic research, that there are only a few, fundamental choices in taxation, given by the interaction of base and schedule.
I show that these choices are highly consequential, irreducibly political, and therefore, essential for deliberating citizens.

Fourth, the medical student informs her supervisors that, *unfortunately* the planned study cannot be undertaken in the usual clinical setting, but that because of all the required instruction, she will need to meet participants in person every morning for a group session at a local gym, which she will decorate appropriately with sandalwood incense.[^centerpiece]
Aghast upon hearing this latest proposal, one of the supervisors resigns from the committee and vows to never supervise a student again who so much as mentions Eastern philosophy.
The student studies existing treatment regimens, and argues that an intensive intervention is the only way to do this research.
She also finds two other studies with similar treatments, one even flew participants out to a Caribbean yoga retreat.
The remaining supervisors stay on, perhaps just hoping that the philosophizing will now come to an end, and the study reach firmer ground.

[^centerpiece]: This part is actually factual.
    At the behest of the trained moderators, we installed a vaguely new-agey centerpiece at the deliberation venue.
    It worked wonders.
    <!-- TODO refer to picture in the appendix -->

This study too, required an unconventional treatment regimen.
In chapter \@(civicon) I explain why, instead of the more usual short and large-n deliberative fora, to study taxation, a longer and more intensive format is necessary.
I review existing deliberative fora, and argue why their experimental value remains limited.
I describe the design of the **CiviCon Citizen Conference** I hosted as part of this dissertation.

Fifth, our aspiring clinician recognizes that measuring "mindfulness", her DV, is quite tricky.
Existing survey instruments seem too closed-ended, but entirely qualitative methods do not seem scientific enough for her.
Instead, she finds a clever way to holistically measure *different* experiences of mindfulness, and records how they change during the course of the treatment.

Measuring *whether* a forum was deliberative, and if so, what the *substantive effects* of the deliberation were may be yet more vexing than quantifying "mindfulness".
In chapter \@(q), I review existing measurements for deliberative quality, as well as their results and, finding most of them unsatisfactory for the present needs, suggest an application of rarely used Q-Methodology.


## Theory as Treatment

<!-- TODO a research question chapter is missing in the above, and that is in fact where, well, what is tested would be listed -->

What may strike readers as odd about the first couple of chapters is that these are wide-ranging, but in no way original.
They have the feeling of a *textbook*.
This is by design, and follows from the remedial aspiration of deliberation itself.
<!-- TODO explain why it needs didactic reduction etc. -->

Emphatically, the content of the theory chapters is also *nowhere* subject to an empirical test in this dissertation.
Much like our hypothetical medical student would not test whether participants could successfully do a *firefly pose*, I never test whether participants understand the deadweight-loss (DWL) of taxation, let alone whether, under which circumstances or to what extent, this abstraction is a positive phenomenon.
All these chapters have the status of *justifying* and *explicating* the *treatment*, that is, the framing and briefing for the deliberative forum.

<!-- TODO
add plot here where/how these chapters feed into other objects/chapters, to really drive home how necessary they are.
this might be a bigraph, with the different chapters on both sides as nodes, edges with descriptions in the middle
explain that the econ101 in chap 1-3 is *both* for readers, and for civicon participants, *and* for items
-->

<!-- Precisely, what we ought to do in all these chapters, hence also the axiology and philosophical stuff, we need to find whatever is *contentious* behind first order Questions
for example, behind the CIT
but this can only happen at the end, its axiomatic, and this just needs some time to develop-->

<!-- This stuff is what makes this diss a little complicated, but it's also about the only thing that makes it worthwhile, and perhaps, original -->
<!-- we need to get a lot of first-order questions out of the way, it is necessary, but weird -->


## Theory as Didactic Reduction

<!-- we need tax and the background, because this all needs Philosophy
in way, what this all is, is citizen science -->

<!-- I *am* actually concentrating here; there is *lot* that is not mentioned here:
- monetary policy (because it is a technical issue, at least for now)
- spending side (completely different ballgame, ends up making the whole thing wayyy to big and loosy-goosy)
- you gotta do this, otherwise it gets too fluffy -->


## Theory as Explanandum

<!-- You need to have a first-order theory that you need to explain -->
<!-- maybe do the whole first/second oder business here -->

<!-- notice where literature review happens -->

<!-- %project description
%universe, cases, variables
%temporal, spatial, social limits-->

<!-- Before specifying a format to investigate this question, I must note some of the substantive desiderata of deliberation and taxation that any operationalization will have to reflect, if it is to maintain construct validity. -->


## Payoff

This is probably an unconventional, and possibly risky project, but it has promise, too.

If, given the right design, deliberative democracy can enable citizens to rule on complex issues, political scientists will have a very able, and attractive hypothetical to compare with, and deliberative experimenters should have more courage to venture out to more topics facing our sovereigns.
Not just as social scientists, but as citizens too, we must know whether the once historical achievement of aggregative democracy is now withering away under the assault of tightly concentrated special interest and obscuring complexity.
If it can show its stripes, deliberative democracy may well be our last, and also our best hope, to reveal the perils of pluralism, then to live up to our greater capacity for communicative action.

If, under a normatively more attractive democratic process, people were to resolve some misunderstandings about, and agree on different, but doable and desirable taxes, welfare state research and political economy would have to explain a much greater retrenchment and democratic failure.
Not only as social scientists, but as citizens, too, we must know that better tax we could agree on, and if it exists, what is keeping us from it.
Taxation, underneath it all, *is* the social contract [@SchumpeterSwedberg-1942-aa], and its vitality will determine the prospects for modern progress.


## It's a Long Story

This dissertation is, lastly, , despite it all (, p. ):
the crime remains unsolved, and I can point to no single societal culprit.
Maybe, that is for the better, as few good things ever come from such structuralist exorcisms.
There may be many reasons why we have no better tax, and the *kind* of democracy we have might plausibly be one of them.
That alone ought to worry us.

If, in fact, our pluralist democracies are becoming illegitimate and inefficient, their increasing failures will plague many arenas of collective choice other than taxation.
The death knells of legitimate and efficient pluralism --- complexity and tightly concentrated special interest --- *are* the conditions of late capitalist society.
I that taxation may just be one these policy fields in which the limits of pluralism show early, and clearly (, p. ).
Indeed, the entire story could be told the other way around, with popular rule as the corpse that found its master in the intricacies of tax.

This dissertation is fairly long and not very original.
Others already have, in different places and with different foci, written almost all that is contained in the next pages.
And yet, so far, no one has bothered to connect the dots.
That is what I offer here.

Raymond @Williams1992 has argued that the detective story appears at roughly the same time as sociology, and for the same reason:
to penetrate the modern world, as Conan Doyle's *Sherlock Holmes* does, "by an isolated rational intelligence" [@Williams1992 88], otherwise covered by London fogs, or compartmentalized by functional differentiation [@Durkheim-1893-aa].
And so it is with this crime story of taxation and democracy:
shrouded in nebulous complexity, pigeonholed into disjunct institutions and areas of expertise, it needs a lot of detective work to connect these dots.
To hear this case, I urge the reader to consider all of the evidence reviewed in this exposition, even if some of the detail might, at first, seem trivial.
It is not.
As Sherlock Holmes reminds us, "there is nothing so important as trifles" [@Doyle1891 238].
From the incidence of the [cit]{acronym-label="cit" acronym-form="singular+short"}, the liquidity effects of taxing property to the macro- and micropolitics of democracy and the sociobiology of fairness, cooperation and equality
--- these "trifles" are all important exhibits to make the case that democracy, taxation, and with it, all our modern lives, *could*, and therefore, *should* be better.

Some stories just cannot be told in the short form, and the story I have stumbled upon and here report may be one of those.
Luckily, detective stories can also be fun to read, and so, I hope, is this one.
