---
title: "Taxation and Democracy"
author: "Maximilian Held"
classoption: a4paper
output:
  pdf_document:
    fig_caption: yes
    keep_tex: yes
    number_sections: yes
    toc: yes
geometry: margin=1.5in
documentclass : memoir
lang: english
bibliography: ../held-library/held_library.bib
---

```{r preamble, echo = FALSE}
library(devtools)
library(knitr)
library(rmarkdown)
library(corrplot)
library(grid)  # needed, for, well, grids and arrows
library(gridExtra)  # needed for more grids
library(reshape2)
library(ggplot2)
install.packages(c("qmethod"), repos = NULL, type = "source")
library(qmethod)
# install_github("vqv/ggbiplot")
# library(ggbiplot)
install_github("kassambara/factoextra")
```

```{r setup-knitr, cache = FALSE, include = FALSE}
opts_knit$set(root.dir = normalizePath(getwd()))  # what does this do?
options(digits=2)
```

```{r q-method, message = FALSE, results = "hide", echo = FALSE}
knit("source/method-q.Rmd")
```

```{r results-factors, child="source/results-factors.Rmd"}
```


# References
